import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

def w(tid, it, pt, cat, ex_it, ex_pt, ipa="", gen=None, pl=None):
    return {
        "id": tid, "italiano": it, "portugues": pt, "genero": gen, "plural": pl,
        "exemplo": ex_it, "exemplo_pt": ex_pt, "categoria": cat, "dificuldade": "medio", "audio_ipa": ipa
    }

def append_to_existing(templo_num, new_words_data):
    path = os.path.join(OUT, "data", f"templo-{templo_num}.json")
    with open(path, "r", encoding="utf-8") as f:
        obj = json.load(f)
    
    current_count = len(obj["palavras"])
    for i, (it, pt, cat, ex_it, ex_pt, ipa, gen, pl) in enumerate(new_words_data, current_count + 1):
        tid = f"t{templo_num}_{i:03d}"
        obj["palavras"].append(w(tid, it, pt, cat, ex_it, ex_pt, ipa, gen, pl))
        
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"APPENDED templo-{templo_num}.json -- now has {len(obj['palavras'])} parole")

t34_add = [
    ("sfilacciato", "desfiado", "aggettivi", "Un orlo sfilacciato.", "Uma barra desfiada.", "/sfilatˈtʃato/", "m", "sfilacciati")
]

t35_add = [
    ("compostaggio", "compostagem", "soluzioni", "Il bidone del compostaggio.", "A lixeira da compostagem.", "/komposˈtaddʒo/", "m", "compostaggi"),
    ("esaurimento", "esgotamento", "problemi", "L'esaurimento delle risorse.", "O esgotamento dos recursos.", "/ezauriˈmento/", "m", "esaurimenti"),
    ("idrocarburo", "hidrocarboneto", "problemi", "L'uso di idrocarburi.", "O uso de hidrocarbonetos.", "/idrokarˈburo/", "m", "idrocarburi"),
    ("petrolio", "petróleo", "problemi", "Estrarre il petrolio.", "Extrair o petróleo.", "/peˈtrɔljo/", "m", "petroli"),
    ("combustibile", "combustível", "problemi", "Combustibile fossile.", "Combustível fóssil.", "/kombusˈtibile/", "m", "combustibili"),
    ("deforestazione", "desmatamento", "problemi", "La deforestazione avanza.", "O desmatamento avança.", "/deforestatˈtsjone/", "f", "deforestazioni"),
    ("biodiversità", "biodiversidade", "natura", "La perdita di biodiversità.", "A perda de biodiversidade.", "/bjodiversiˈta/", "f", "biodiversità"),
    ("serra", "estufa", "problemi", "L'effetto serra.", "O efeito estufa.", "/ˈsɛrra/", "f", "serre"),
    ("fotovoltaico", "fotovoltaico", "soluzioni", "Impianto fotovoltaico.", "Usina fotovoltaica.", "/fotovolˈtaiko/", "m", "fotovoltaici"),
    ("termico", "térmico", "problemi", "Inquinamento termico.", "Poluição térmica.", "/ˈtɛrmiko/", "m", "termici"),
    ("ecocidio", "ecocídio", "problemi", "Un vero ecocidio.", "Um verdadeiro ecocídio.", "/ekoˈtʃidjo/", "m", "ecocidi")
]

t36_add = [
    ("emoji", "emoji", "social", "Manda un'emoji.", "Mande um emoji.", "/eˈmɔdʒi/", "f", "emoji"),
    ("emoticon", "emoticon", "social", "Una vecchia emoticon.", "Um velho emoticon.", "/eˈmotikon/", "f", "emoticon"),
    ("avatar", "avatar", "social", "Scegli il tuo avatar.", "Escolha seu avatar.", "/ˈavatar/", "m", "avatar"),
    ("streaming", "streaming", "tecnologia", "Guardare in streaming.", "Assistir em streaming.", "/ˈstrimiŋ/", "m", "streaming"),
    ("podcast", "podcast", "tecnologia", "Ascoltare un podcast.", "Ouvir um podcast.", "/ˈpɔdkast/", "m", "podcast"),
    ("meme", "meme", "social", "Un meme divertente.", "Um meme divertido.", "/ˈmɛme/", "m", "meme"),
    ("gif", "gif", "social", "Inviare una gif.", "Enviar um gif.", "/dʒif/", "f", "gif"),
    ("spammer", "spammer", "tecnologia", "Segnala lo spammer.", "Denuncie o spammer.", "/ˈspammer/", "m", "spammer"),
    ("troll", "troll", "social", "Non nutrire i troll.", "Não alimente os trolls.", "/trɔl/", "m", "troll"),
    ("algoritmo", "algoritmo", "tecnologia", "L'algoritmo del social.", "O algoritmo da rede social.", "/alɡoˈritmo/", "m", "algoritmi"),
    ("crittografia", "criptografia", "tecnologia", "Crittografia end-to-end.", "Criptografia de ponta a ponta.", "/krittoɡraˈfia/", "f", "crittografie"),
    ("firewall", "firewall", "tecnologia", "Attivare il firewall.", "Ativar o firewall.", "/ˈfairwɔl/", "m", "firewall"),
    ("malware", "malware", "tecnologia", "Un malware pericoloso.", "Um malware perigoso.", "/ˈmalwɛr/", "m", "malware"),
    ("spyware", "spyware", "tecnologia", "Rimuovere lo spyware.", "Remover o spyware.", "/ˈspaiwɛr/", "m", "spyware"),
    ("phishing", "phishing", "tecnologia", "Una mail di phishing.", "Um e-mail de phishing.", "/ˈfiʃiŋ/", "m", "phishing"),
    ("server", "servidor", "tecnologia", "Il server è giù.", "O servidor caiu.", "/ˈsɛrver/", "m", "server")
]

t37_add = [
    ("reliquia", "relíquia", "oggetti", "Una reliquia sacra.", "Uma relíquia sagrada.", "/reˈlikwja/", "f", "reliquie"),
    ("ostia", "hóstia", "oggetti", "Ricevere l'ostia.", "Receber a hóstia.", "/ˈɔstja/", "f", "ostie"),
    ("calice", "cálice", "oggetti", "Il calice di vino.", "O cálice de vinho.", "/ˈkalitʃe/", "m", "calici"),
    ("turibolo", "turíbulo", "oggetti", "Agitare il turibolo.", "Agitar o turíbulo.", "/tuˈribolo/", "m", "turiboli"),
    ("messale", "missal", "oggetti", "Leggere il messale.", "Ler o missal.", "/mesˈsale/", "m", "messali"),
    ("paramento", "paramento", "oggetti", "I paramenti sacri.", "Os paramentos sagrados.", "/paraˈmento/", "m", "paramenti"),
    ("tabernacolo", "tabernáculo", "oggetti", "Il tabernacolo chiuso.", "O tabernáculo fechado.", "/taberˈnakolo/", "m", "tabernacoli"),
    ("navata", "nave (igreja)", "luoghi", "La navata centrale.", "A nave central.", "/naˈvata/", "f", "navate")
]

# T38: La Psicologia e la Mente (110 parole)
t38_data = [
    # Concetti base e mente
    ("mente", "mente", "psicologia", "La mente umana.", "A mente humana.", "/ˈmente/", "f", "menti"),
    ("psicologia", "psicologia", "psicologia", "Studiare psicologia.", "Estudar psicologia.", "/psikoloˈdʒia/", "f", "psicologie"),
    ("pensiero", "pensamento", "psicologia", "Un pensiero profondo.", "Um pensamento profundo.", "/penˈsjɛro/", "m", "pensieri"),
    ("coscienza", "consciência", "psicologia", "Avere la coscienza pulita.", "Ter a consciência limpa.", "/koʃˈʃɛntsa/", "f", "coscienze"),
    ("inconscio", "inconsciente", "psicologia", "I desideri dell'inconscio.", "Os desejos do inconsciente.", "/inˈkɔnʃo/", "m", "inconsci"),
    ("subconscio", "subconsciente", "psicologia", "Messaggi al subconscio.", "Mensagens ao subconsciente.", "/subˈkɔnʃo/", "m", "subconsci"),
    ("ragione", "razão", "psicologia", "Usare la ragione.", "Usar a razão.", "/raˈdʒone/", "f", "ragioni"),
    ("emozione", "emoção", "emozioni", "Un'emozione forte.", "Uma emoção forte.", "/emotˈtsjone/", "f", "emozioni"),
    ("sentimento", "sentimento", "emozioni", "Un sentimento puro.", "Um sentimento puro.", "/sentiˈmento/", "m", "sentimenti"),
    ("umore", "humor", "emozioni", "Oggi sono di buon umore.", "Hoje estou de bom humor.", "/uˈmore/", "m", "umori"),
    ("memoria", "memória", "psicologia", "Avere una buona memoria.", "Ter uma boa memória.", "/meˈmɔrja/", "f", "memorie"),
    ("ricordo", "lembrança", "psicologia", "Un bel ricordo d'infanzia.", "Uma bela lembrança de infância.", "/riˈkɔrdo/", "m", "ricordi"),
    ("intelligenza", "inteligência", "psicologia", "Test di intelligenza.", "Teste de inteligência.", "/intellidˈdʒɛntsa/", "f", "intelligenze"),
    ("personalità", "personalidade", "psicologia", "Ha una personalità forte.", "Tem uma personalidade forte.", "/personaliˈta/", "f", "personalità"),
    ("carattere", "caráter/temperamento", "psicologia", "Un brutto carattere.", "Um mau temperamento.", "/kaˈrattere/", "m", "caratteri"),
    ("comportamento", "comportamento", "psicologia", "Un comportamento strano.", "Um comportamento estranho.", "/komportaˈmento/", "m", "comportamenti"),
    # Emozioni e stati d'animo
    ("gioia", "alegria", "emozioni", "Saltare di gioia.", "Pular de alegria.", "/ˈdʒɔja/", "f", "gioie"),
    ("tristezza", "tristeza", "emozioni", "Un senso di tristezza.", "Um sentimento de tristeza.", "/trisˈtettsa/", "f", "tristezze"),
    ("rabbia", "raiva", "emozioni", "Esplodere di rabbia.", "Explodir de raiva.", "/ˈrabbja/", "f", "rabbie"),
    ("paura", "medo", "emozioni", "Avere paura del buio.", "Ter medo do escuro.", "/paˈura/", "f", "paure"),
    ("ansia", "ansiedade", "emozioni", "Soffrire di ansia.", "Sofrer de ansiedade.", "/ˈansja/", "f", "ansie"),
    ("stress", "estresse", "emozioni", "Lo stress del lavoro.", "O estresse do trabalho.", "/strɛs/", "m", "stress"),
    ("panico", "pânico", "emozioni", "Un attacco di panico.", "Um ataque de pânico.", "/ˈpaniko/", "m", "panichi"),
    ("angoscia", "angústia", "emozioni", "Un'angoscia profonda.", "Uma angústia profunda.", "/anˈɡɔʃʃa/", "f", "angosce"),
    ("sorpresa", "surpresa", "emozioni", "Una bella sorpresa.", "Uma bela surpresa.", "/sorˈpreza/", "f", "sorprese"),
    ("disgusto", "nojo", "emozioni", "Provare disgusto.", "Sentir nojo.", "/dizˈɡusto/", "m", "disgusti"),
    ("vergogna", "vergonha", "emozioni", "Provare vergogna.", "Sentir vergonha.", "/verˈɡoɲɲa/", "f", "vergogne"),
    ("senso di colpa", "sentimento de culpa", "emozioni", "Un forte senso di colpa.", "Um forte sentimento de culpa.", "/ˈsɛnso di ˈkolpa/", "m", "sensi di colpa"),
    ("invidia", "inveja", "emozioni", "L'invidia è una brutta bestia.", "A inveja é uma coisa feia.", "/inˈvidja/", "f", "invidie"),
    ("gelosia", "ciúme", "emozioni", "Una folle gelosia.", "Um ciúme louco.", "/dʒeloˈzia/", "f", "gelosie"),
    ("orgoglio", "orgulho", "emozioni", "Ferito nell'orgoglio.", "Ferido no orgulho.", "/orˈɡoʎʎo/", "m", "orgogli"),
    ("empatia", "empatia", "psicologia", "Provare empatia per gli altri.", "Sentir empatia pelos outros.", "/empaˈtia/", "f", "empatie"),
    ("simpatia", "simpatia", "psicologia", "Ispirare simpatia.", "Inspirar simpatia.", "/simpaˈtia/", "f", "simpatie"),
    ("antipatia", "antipatia", "psicologia", "Una leggera antipatia.", "Uma leve antipatia.", "/antipaˈtia/", "f", "antipatie"),
    # Disturbi e Terapie
    ("depressione", "depressão", "disturbi", "Soffrire di depressione.", "Sofrer de depressão.", "/depresˈsjone/", "f", "depressioni"),
    ("trauma", "trauma", "disturbi", "Un trauma infantile.", "Um trauma infantil.", "/ˈtrauma/", "m", "traumi"),
    ("fobia", "fobia", "disturbi", "Avere una fobia per i ragni.", "Ter uma fobia de aranhas.", "/foˈbia/", "f", "fobie"),
    ("ossessione", "obsessão", "disturbi", "Un'ossessione malsana.", "Uma obsessão doentia.", "/ossesˈsjone/", "f", "ossessioni"),
    ("dipendenza", "dependência/vício", "disturbi", "Dipendenza da internet.", "Dependência de internet.", "/dipenˈdɛntsa/", "f", "dipendenze"),
    ("allucinazione", "alucinação", "disturbi", "Avere un'allucinazione.", "Ter uma alucinação.", "/allutʃinatˈtsjone/", "f", "allucinazioni"),
    ("delirio", "delírio", "disturbi", "In preda al delirio.", "Em meio ao delírio.", "/deˈlirjo/", "m", "deliri"),
    ("terapia", "terapia", "terapie", "Andare in terapia.", "Ir à terapia.", "/teraˈpia/", "f", "terapie"),
    ("psicanalisi", "psicanálise", "terapie", "Una seduta di psicanalisi.", "Uma sessão de psicanálise.", "/psikaˈnalizi/", "f", "psicanalisi"),
    ("seduta", "sessão (terapia)", "terapie", "Una seduta settimanale.", "Uma sessão semanal.", "/seˈduta/", "f", "sedute"),
    ("psicologo", "psicólogo", "persone", "Parlarne con lo psicologo.", "Falar disso com o psicólogo.", "/psiˈkɔloɡo/", "m", "psicologi"),
    ("psichiatra", "psiquiatra", "persone", "Lo psichiatra prescrive farmaci.", "O psiquiatra prescreve remédios.", "/psiˈkjatra/", "m", "psichiatri"),
    ("paziente", "paciente", "persone", "Il paziente sul lettino.", "O paciente no divã.", "/patˈtsjɛnte/", "m/f", "pazienti"),
    ("lettino", "divã/maca", "oggetti", "Il lettino dello psicanalista.", "O divã do psicanalista.", "/letˈtino/", "m", "lettini"),
    # Verbi
    ("pensare", "pensar", "verbi", "Pensare al futuro.", "Pensar no futuro.", "/penˈsare/", None, None),
    ("ricordare", "lembrar", "verbi", "Ricordare il passato.", "Lembrar o passado.", "/rikorˈdare/", None, None),
    ("dimenticare", "esquecer", "verbi", "Dimenticare un nome.", "Esquecer um nome.", "/dimentiˈkare/", None, None),
    ("sentire", "sentir", "verbi", "Sentire un'emozione.", "Sentir uma emoção.", "/senˈtire/", None, None),
    ("provare", "sentir/experimentar", "verbi", "Provare dolore.", "Sentir dor.", "/proˈvare/", None, None),
    ("soffrire", "sofrer", "verbi", "Soffrire di solitudine.", "Sofrer de solidão.", "/sofˈfrire/", None, None),
    ("superare", "superar", "verbi", "Superare un trauma.", "Superar um trauma.", "/supeˈrare/", None, None),
    ("analizzare", "analisar", "verbi", "Analizzare i sogni.", "Analisar os sonhos.", "/analidˈdzare/", None, None),
    ("esprimere", "expressar", "verbi", "Esprimere i propri sentimenti.", "Expressar os próprios sentimenti.", "/esˈprimere/", None, None),
    ("reprimere", "reprimir", "verbi", "Reprimere la rabbia.", "Reprimir a raiva.", "/reˈprimere/", None, None),
    ("ascoltare", "escutar", "verbi", "Lo psicologo deve ascoltare.", "O psicólogo deve escutar.", "/askolˈtare/", None, None),
    ("capire", "entender", "verbi", "Capire se stessi.", "Entender a si mesmo.", "/kaˈpire/", None, None),
    ("immaginare", "imaginar", "verbi", "Immaginare una situazione.", "Imaginar uma situação.", "/immadʒiˈnare/", None, None),
    ("sognare", "sonhar", "verbi", "Sognare a occhi aperti.", "Sonhar acordado.", "/soɲˈɲare/", None, None),
    ("rilassarsi", "relaxar", "verbi", "Bisogna sapersi rilassare.", "É preciso saber relaxar.", "/rilasˈsarsi/", None, None),
    ("piangere", "chorar", "verbi", "Piangere di gioia.", "Chorar de alegria.", "/ˈpjandʒere/", None, None),
    ("ridere", "rir", "verbi", "Ridere di gusto.", "Rir com vontade.", "/ˈridere/", None, None),
    ("arrabbiarsi", "irritar-se", "verbi", "Arrabbiarsi per niente.", "Irritar-se por nada.", "/arrabˈbjarsi/", None, None),
    ("preoccuparsi", "preocupar-se", "verbi", "Preoccuparsi troppo.", "Preocupar-se demais.", "/preokkuˈparsi/", None, None),
    ("calmarsi", "acalmar-se", "verbi", "Cerca di calmarti.", "Tente se acalmar.", "/kalˈmarsi/", None, None),
    # Aggettivi e descrittori
    ("felice", "feliz", "aggettivi", "Un bambino felice.", "Um menino feliz.", "/feˈlitʃe/", "m", "felici"),
    ("triste", "triste", "aggettivi", "Una persona triste.", "Uma pessoa triste.", "/ˈtriste/", "m", "tristi"),
    ("arrabbiato", "irritado", "aggettivi", "Sono molto arrabbiato.", "Estou muito irritado.", "/arrabˈbjato/", "m", "arrabbiati"),
    ("calmo", "calmo", "aggettivi", "Rimanere calmo.", "Permanecer calmo.", "/ˈkalmo/", "m", "calmi"),
    ("nervoso", "nervoso", "aggettivi", "Essere nervoso per l'esame.", "Estar nervoso para a prova.", "/nerˈvozo/", "m", "nervosi"),
    ("ansioso", "ansioso", "aggettivi", "Un paziente ansioso.", "Um paciente ansioso.", "/anˈsjozo/", "m", "ansiosi"),
    ("depresso", "deprimido", "aggettivi", "Si sente depresso.", "Sente-se deprimido.", "/deˈprɛsso/", "m", "depressi"),
    ("sicuro", "seguro/confiante", "aggettivi", "Sicuro di sé.", "Confiante em si mesmo.", "/siˈkuro/", "m", "sicuri"),
    ("insicuro", "inseguro", "aggettivi", "Un adolescente insicuro.", "Um adolescente inseguro.", "/insiˈkuro/", "m", "insicuri"),
    ("timido", "tímido", "aggettivi", "Un ragazzo timido.", "Um menino tímido.", "/ˈtimido/", "m", "timidi"),
    ("estroverso", "extrovertido", "aggettivi", "Un carattere estroverso.", "Um temperamento extrovertido.", "/estroˈvɛrso/", "m", "estroversi"),
    ("introverso", "introvertido", "aggettivi", "Una ragazza introversa.", "Uma menina introvertida.", "/introˈvɛrso/", "m", "introversi"),
    ("ottimista", "otimista", "aggettivi", "Vedere il bicchiere mezzo pieno, è ottimista.", "Ver o copo meio cheio, é otimista.", "/ottiˈmista/", "m/f", "ottimisti"),
    ("pessimista", "pessimista", "aggettivi", "Un atteggiamento pessimista.", "Uma atitude pessimista.", "/pessiˈmista/", "m/f", "pessimisti"),
    ("razionale", "racional", "aggettivi", "Una scelta razionale.", "Uma escolha racional.", "/rattsjoˈnale/", "m", "razionali"),
    ("emotivo", "emotivo", "aggettivi", "Una persona emotiva.", "Uma pessoa emotiva.", "/emoˈtivo/", "m", "emotivi"),
    ("sensibile", "sensível", "aggettivi", "Un animo sensibile.", "Uma alma sensível.", "/senˈsibile/", "m", "sensibili"),
    ("folle", "louco/insano", "aggettivi", "Un gesto folle.", "Um gesto louco.", "/ˈfɔlle/", "m", "folli"),
    ("pazzo", "louco", "aggettivi", "Sembra pazzo.", "Parece louco.", "/ˈpattso/", "m", "pazzi"),
    ("saggio", "sábio", "aggettivi", "Un consiglio saggio.", "Um conselho sábio.", "/ˈsaddʒo/", "m", "saggi"),
    ("consapevole", "consciente", "aggettivi", "Essere consapevole dei rischi.", "Estar consciente dos riscos.", "/konsaˈpevole/", "m", "consapevoli"),
    ("inconscio", "inconsciente (adj)", "aggettivi", "Un riflesso inconscio.", "Um reflexo inconsciente.", "/inˈkɔnʃo/", "m", "inconsci"),
    ("mentale", "mental", "aggettivi", "Salute mentale.", "Saúde mental.", "/menˈtale/", "m", "mentali"),
    ("psicologico", "psicológico", "aggettivi", "Un blocco psicologico.", "Um bloqueio psicológico.", "/psikoˈlɔdʒiko/", "m", "psicologici"),
    ("comportamentale", "comportamental", "aggettivi", "Terapia comportamentale.", "Terapia comportamental.", "/komportamenˈtale/", "m", "comportamentali"),
    ("cognitivo", "cognitivo", "aggettivi", "Sviluppo cognitivo.", "Desenvolvimento cognitivo.", "/koɲɲiˈtivo/", "m", "cognitivi"),
    ("affettivo", "afetivo", "aggettivi", "Un legame affettivo.", "Um vínculo afetivo.", "/affetˈtivo/", "m", "affettivi"),
    ("compulsivo", "compulsivo", "aggettivi", "Acquisto compulsivo.", "Compra compulsiva.", "/kompulˈsivo/", "m", "compulsivi"),
    ("narcisista", "narcisista", "aggettivi", "Comportamento narcisista.", "Comportamento narcisista.", "/nartʃiˈzista/", "m/f", "narcisisti"),
    ("paranoico", "paranoico", "aggettivi", "Un pensiero paranoico.", "Um pensamento paranoico.", "/paraˈnɔiko/", "m", "paranoici")
]

# T39: L'Astronomia e lo Spazio (110 parole)
t39_data = [
    # Elementi dell'universo
    ("universo", "universo", "spazio", "L'origine dell'universo.", "A origem do universo.", "/uniˈvɛrso/", "m", "universi"),
    ("spazio", "espaço", "spazio", "Viaggiare nello spazio.", "Viajar no espaço.", "/ˈspattsjo/", "m", "spazi"),
    ("galassia", "galáxia", "spazio", "La galassia lontana.", "A galáxia distante.", "/ɡaˈlassja/", "f", "galassie"),
    ("via lattea", "via láctea", "spazio", "La nostra Via Lattea.", "A nossa Via Láctea.", "/ˈvia ˈlattea/", "f", None),
    ("sistema solare", "sistema solar", "spazio", "I pianeti del sistema solare.", "Os planetas do sistema solar.", "/sisˈtɛma soˈlare/", "m", "sistemi solari"),
    ("stella", "estrela", "spazio", "Una stella cadente.", "Uma estrela cadente.", "/ˈstella/", "f", "stelle"),
    ("sole", "sol", "spazio", "Il sole sorge.", "O sol nasce.", "/ˈsole/", "m", "soli"),
    ("luna", "lua", "spazio", "La luna piena.", "A lua cheia.", "/ˈluna/", "f", "lune"),
    ("pianeta", "planeta", "spazio", "Il pianeta rosso.", "O planeta vermelho.", "/pjaˈneta/", "m", "pianeti"),
    ("terra", "terra", "spazio", "Il pianeta Terra.", "O planeta Terra.", "/ˈtɛrra/", "f", "terre"),
    ("marte", "marte", "spazio", "La missione su Marte.", "A missão a Marte.", "/ˈmarte/", "m", None),
    ("giove", "júpiter", "spazio", "Giove è enorme.", "Júpiter é enorme.", "/ˈdʒɔve/", "m", None),
    ("saturno", "saturno", "spazio", "Gli anelli di Saturno.", "Os anéis de Saturno.", "/saˈturno/", "m", None),
    ("orbita", "órbita", "spazio", "Entrare in orbita.", "Entrar em órbita.", "/ˈɔrbita/", "f", "orbite"),
    ("satellite", "satélite", "spazio", "Il satellite artificiale.", "O satélite artificial.", "/saˈtɛllite/", "m", "satelliti"),
    ("cometa", "cometa", "spazio", "La coda della cometa.", "A cauda do cometa.", "/koˈmɛta/", "f", "comete"),
    ("asteroide", "asteroide", "spazio", "Un asteroide si avvicina.", "Um asteroide se aproxima.", "/asteˈrɔide/", "m", "asteroidi"),
    ("meteorite", "meteorito", "spazio", "Il cratere del meteorite.", "A cratera do meteorito.", "/meteoˈrite/", "m", "meteoriti"),
    ("buco nero", "buraco negro", "spazio", "Un buco nero supermassiccio.", "Um buraco negro supermaciço.", "/ˈbuko ˈnero/", "m", "buchi neri"),
    ("nebulosa", "nebulosa", "spazio", "Una nebulosa colorata.", "Uma nebulosa colorida.", "/nebuˈloza/", "f", "nebulose"),
    ("costellazione", "constelação", "spazio", "La costellazione di Orione.", "A constelação de Órion.", "/kostellatˈtsjone/", "f", "costellazioni"),
    ("zodiaco", "zodíaco", "spazio", "I segni dello zodiaco.", "Os signos do zodíaco.", "/dzoˈdiako/", "m", "zodiaci"),
    ("eclissi", "eclipse", "spazio", "Un'eclissi solare.", "Um eclipse solar.", "/eˈklissi/", "f", "eclissi"),
    ("gravità", "gravidade", "spazio", "L'assenza di gravità.", "A ausência de gravidade.", "/ɡraviˈta/", "f", "gravità"),
    ("vuoto", "vácuo", "spazio", "Il vuoto cosmico.", "O vácuo cósmico.", "/ˈvwɔto/", "m", "vuoti"),
    ("luce", "luz", "spazio", "L'anno luce.", "O ano-luz.", "/ˈlutʃe/", "f", "luci"),
    ("materia", "matéria", "spazio", "La materia oscura.", "A matéria escura.", "/maˈtɛrja/", "f", "materie"),
    ("polvere", "poeira", "spazio", "Polvere stellare.", "Poeira estelar.", "/ˈpolvere/", "f", "polveri"),
    ("radiazione", "radiação", "spazio", "Radiazione cosmica.", "Radiação cósmica.", "/radjatˈtsjone/", "f", "radiazioni"),
    # Esplorazione Spaziale
    ("astronauta", "astronauta", "esplorazione", "L'astronauta fluttua.", "O astronauta flutua.", "/astroˈnauta/", "m/f", "astronauti"),
    ("cosmonauta", "cosmonauta", "esplorazione", "Un cosmonauta russo.", "Um cosmonauta russo.", "/kozmoˈnauta/", "m/f", "cosmonauti"),
    ("navicella", "nave espacial", "esplorazione", "La navicella spaziale.", "A nave espacial.", "/naviˈtʃɛlla/", "f", "navicelle"),
    ("astronave", "espaçonave", "esplorazione", "Un'astronave aliena.", "Uma espaçonave alienígena.", "/astroˈnave/", "f", "astronavi"),
    ("razzo", "foguete", "esplorazione", "Il lancio del razzo.", "O lançamento do foguete.", "/ˈraddzo/", "m", "razzi"),
    ("missile", "míssil/foguete", "esplorazione", "Un missile balistico.", "Um míssil balístico.", "/ˈmissile/", "m", "missili"),
    ("sonda", "sonda", "esplorazione", "Una sonda inviata su Marte.", "Uma sonda enviada a Marte.", "/ˈsonda/", "f", "sonde"),
    ("rover", "rover", "esplorazione", "Il rover esplora il cratere.", "O rover explora a cratera.", "/ˈrover/", "m", "rover"),
    ("telescopio", "telescópio", "esplorazione", "Il telescopio spaziale Hubble.", "O telescópio espacial Hubble.", "/telesˈkɔpjo/", "m", "telescopi"),
    ("osservatorio", "observatório", "esplorazione", "L'osservatorio astronomico.", "O observatório astronômico.", "/osservaˈtɔrjo/", "m", "osservatori"),
    ("base", "base", "esplorazione", "La base spaziale.", "A base espacial.", "/ˈbaze/", "f", "basi"),
    ("stazione", "estação", "esplorazione", "La Stazione Spaziale Internazionale.", "A Estação Espacial Internacional.", "/statˈtsjone/", "f", "stazioni"),
    ("lancio", "lançamento", "esplorazione", "Pronti per il lancio.", "Prontos para o lançamento.", "/ˈlantʃo/", "m", "lanci"),
    ("decollo", "decolagem", "esplorazione", "Il decollo è perfetto.", "A decolagem é perfeita.", "/deˈkɔllo/", "m", "decolli"),
    ("atterraggio", "aterrissagem/pouso", "esplorazione", "L'atterraggio sulla Luna.", "O pouso na Lua.", "/atterˈraddʒo/", "m", "atterraggi"),
    ("allunaggio", "pouso lunar", "esplorazione", "Il primo allunaggio.", "O primeiro pouso lunar.", "/alluˈnaddʒo/", "m", "allunaggi"),
    ("missione", "missão", "esplorazione", "Una missione segreta.", "Uma missão secreta.", "/misˈsjone/", "f", "missioni"),
    ("equipaggio", "tripulação", "esplorazione", "L'equipaggio della navicella.", "A tripulação da nave.", "/ekwiˈpaddʒo/", "m", "equipaggi"),
    ("tuta", "traje (espacial)", "esplorazione", "La tuta spaziale.", "O traje espacial.", "/ˈtuta/", "f", "tute"),
    ("casco", "capacete", "esplorazione", "Il casco dell'astronauta.", "O capacete do astronauta.", "/ˈkasko/", "m", "caschi"),
    ("alieno", "alienígena", "esplorazione", "Un film sugli alieni.", "Um filme sobre alienígenas.", "/aˈljɛno/", "m", "alieni"),
    ("extraterrestre", "extraterrestre", "esplorazione", "Vita extraterrestre.", "Vida extraterrestre.", "/ɛkstraterˈrɛstre/", "m", "extraterrestri"),
    ("ufo", "óvni", "esplorazione", "Avvistamento di un ufo.", "Avistamento de um óvni.", "/ˈufo/", "m", "ufo"),
    # Scienze e Discipline
    ("astronomia", "astronomia", "scienze", "Studiare l'astronomia.", "Estudar a astronomia.", "/astronoˈmia/", "f", "astronomie"),
    ("astrofisica", "astrofísica", "scienze", "Ricerca in astrofisica.", "Pesquisa em astrofísica.", "/astroˈfizika/", "f", "astrofisiche"),
    ("cosmologia", "cosmologia", "scienze", "Le teorie della cosmologia.", "As teorias da cosmologia.", "/kozmoloˈdʒia/", "f", "cosmologie"),
    ("fisica", "física", "scienze", "Le leggi della fisica.", "As leis da física.", "/ˈfizika/", "f", "fisiche"),
    ("matematica", "matemática", "scienze", "Calcoli di matematica.", "Cálculos de matemática.", "/mateˈmatika/", "f", "matematiche"),
    # Verbi
    ("osservare", "observar", "verbi", "Osservare le stelle.", "Observar as estrelas.", "/osserˈvare/", None, None),
    ("scoprire", "descobrir", "verbi", "Scoprire un nuovo pianeta.", "Descobrir um novo planeta.", "/skoˈprire/", None, None),
    ("esplorare", "explorar", "verbi", "Esplorare lo spazio.", "Explorar o espaço.", "/esploˈrare/", None, None),
    ("lanciare", "lançar", "verbi", "Lanciare un satellite.", "Lançar um satélite.", "/lanˈtʃare/", None, None),
    ("decollare", "decolar", "verbi", "Il razzo decolla alle tre.", "O foguete decola às três.", "/dekolˈlare/", None, None),
    ("atterrare", "aterrissar", "verbi", "Atterrare su Marte.", "Aterrissar em Marte.", "/atterˈrare/", None, None),
    ("fluttuare", "flutuar", "verbi", "Fluttuare nell'aria.", "Flutuar no ar.", "/fluttuˈare/", None, None),
    ("orbitare", "orbitar", "verbi", "La Luna orbita intorno alla Terra.", "A Lua orbita ao redor da Terra.", "/orbiˈtare/", None, None),
    ("ruotare", "rodar/girar", "verbi", "La Terra ruota.", "A Terra gira.", "/rwoˈtare/", None, None),
    ("splendere", "brilhar", "verbi", "Il sole splende.", "O sol brilha.", "/ˈsplɛndere/", None, None),
    ("brillare", "brilhar", "verbi", "Le stelle brillano.", "As estrelas brilham.", "/brilˈlare/", None, None),
    ("cadere", "cair", "verbi", "Una stella cade.", "Uma estrela cai.", "/kaˈdere/", None, None),
    ("viaggiare", "viajar", "verbi", "Viaggiare nel tempo.", "Viajar no tempo.", "/vjadˈdʒare/", None, None),
    ("esplodere", "explodir", "verbi", "La stella esplode.", "A estrela explode.", "/esˈplɔdere/", None, None),
    ("attirare", "atrair", "verbi", "Il buco nero attira la luce.", "O buraco negro atrai a luz.", "/attiˈrare/", None, None),
    ("sopravvivere", "sobreviver", "verbi", "Sopravvivere su Marte.", "Sobreviver em Marte.", "/sopravˈvivere/", None, None),
    # Aggettivi e descrittori
    ("spaziale", "espacial", "aggettivi", "Stazione spaziale.", "Estação espacial.", "/spatˈtsjale/", "m", "spaziali"),
    ("stellare", "estelar", "aggettivi", "Polvere stellare.", "Poeira estelar.", "/stelˈlare/", "m", "stellari"),
    ("solare", "solar", "aggettivi", "Eclissi solare.", "Eclipse solar.", "/soˈlare/", "m", "solari"),
    ("lunare", "lunar", "aggettivi", "Cratere lunare.", "Cratera lunar.", "/luˈnare/", "m", "lunari"),
    ("cosmico", "cósmico", "aggettivi", "Radiazione cosmica.", "Radiação cósmica.", "/ˈkɔzmiko/", "m", "cosmici"),
    ("astronomico", "astronômico", "aggettivi", "Osservatorio astronomico.", "Observatório astronômico.", "/astroˈnɔmiko/", "m", "astronomici"),
    ("alieno", "alienígena (adj)", "aggettivi", "Una forma di vita aliena.", "Uma forma de vida alienígena.", "/aˈljɛno/", "m", "alieni"),
    ("infinito", "infinito", "aggettivi", "L'universo infinito.", "O universo infinito.", "/infiˈnito/", "m", "infiniti"),
    ("immenso", "imenso", "aggettivi", "Uno spazio immenso.", "Um espaço imenso.", "/imˈmɛnso/", "m", "immensi"),
    ("lontano", "distante/longe", "aggettivi", "Una galassia lontana.", "Uma galáxia distante.", "/lonˈtano/", "m", "lontani"),
    ("vicino", "próximo/perto", "aggettivi", "La stella più vicina.", "A estrela mais próxima.", "/viˈtʃino/", "m", "vicini"),
    ("luminoso", "luminoso", "aggettivi", "Un corpo luminoso.", "Um corpo luminoso.", "/lumiˈnozo/", "m", "luminosi"),
    ("oscuro", "escuro/obscuro", "aggettivi", "Materia oscura.", "Matéria escura.", "/osˈkuro/", "m", "oscuri"),
    ("vuoto", "vazio", "aggettivi", "Il profondo vuoto.", "O profundo vazio.", "/ˈvwɔto/", "m", "vuoti"),
    ("denso", "denso", "aggettivi", "Un gas molto denso.", "Um gás muito denso.", "/ˈdɛnso/", "m", "densi"),
    ("pesante", "pesado", "aggettivi", "Un elemento pesante.", "Um elemento pesado.", "/peˈzante/", "m", "pesanti"),
    ("leggero", "leve", "aggettivi", "Idrogeno, gas leggero.", "Hidrogênio, gás leve.", "/ledˈdʒɛro/", "m", "leggeri"),
    ("caldo", "quente", "aggettivi", "Una stella caldissima.", "Uma estrela muito quente.", "/ˈkaldo/", "m", "caldi"),
    ("freddo", "frio", "aggettivi", "Il freddo dello spazio.", "O frio do espaço.", "/ˈfreddo/", "m", "freddi"),
    ("abitabile", "habitável", "aggettivi", "Un pianeta abitabile.", "Um planeta habitável.", "/abiˈtabile/", "m", "abitabili"),
    ("inabitabile", "inabitável", "aggettivi", "Un ambiente inabitabile.", "Um ambiente inabitável.", "/inabiˈtabile/", "m", "inabitabili"),
    ("interstellare", "interestelar", "aggettivi", "Viaggio interstellare.", "Viagem interestelar.", "/interstelˈlare/", "m", "interstellari"),
    ("gravitazionale", "gravitacional", "aggettivi", "Forza gravitazionale.", "Força gravitacional.", "/ɡravitatsjoˈnale/", "m", "gravitazionali"),
    ("terrestre", "terrestre", "aggettivi", "L'orbita terrestre.", "A órbita terrestre.", "/terˈrɛstre/", "m", "terrestri")
]

# T40: L'Economia e la Finanza (110 parole)
t40_data = [
    # Concetti generali e Istituzioni
    ("economia", "economia", "finanza", "L'economia cresce.", "A economia cresce.", "/ekoˈnomja/", "f", "economie"),
    ("finanza", "finanças", "finanza", "Il mondo della finanza.", "O mundo das finanças.", "/fiˈnantsa/", "f", "finanze"),
    ("mercato", "mercado", "finanza", "Il mercato libero.", "O mercado livre.", "/merˈkato/", "m", "mercati"),
    ("borsa", "bolsa de valores", "finanza", "Giocare in borsa.", "Jogar na bolsa.", "/ˈborsa/", "f", "borse"),
    ("banca", "banco", "istituzioni", "Andare in banca.", "Ir ao banco.", "/ˈbanka/", "f", "banche"),
    ("azienda", "empresa", "istituzioni", "Un'azienda informatica.", "Uma empresa de informática.", "/adˈdzjɛnda/", "f", "aziende"),
    ("impresa", "empresa", "istituzioni", "Piccola e media impresa.", "Pequena e média empresa.", "/imˈpreza/", "f", "imprese"),
    ("società", "sociedade (empresa)", "istituzioni", "Una società per azioni.", "Uma sociedade anônima.", "/sotʃeˈta/", "f", "società"),
    ("multinazionale", "multinacional", "istituzioni", "Lavora in una multinazionale.", "Trabalha numa multinacional.", "/multinatsjoˈnale/", "f", "multinazionali"),
    ("stato", "estado", "istituzioni", "Le casse dello stato.", "Os cofres do estado.", "/ˈstato/", "m", "stati"),
    # Soldi e Strumenti Finanziari
    ("soldi", "dinheiro", "denaro", "Non ho soldi.", "Não tenho dinheiro.", "/ˈsɔldi/", "m", "soldi"),
    ("denaro", "dinheiro", "denaro", "Denaro contante.", "Dinheiro vivo.", "/deˈnaro/", "m", "denari"),
    ("contanti", "dinheiro em espécie", "denaro", "Pagare in contanti.", "Pagar em dinheiro.", "/konˈtanti/", "m", "contanti"),
    ("moneta", "moeda", "denaro", "Lancio della moneta.", "Lançamento da moeda.", "/moˈneta/", "f", "monete"),
    ("banconota", "nota (dinheiro)", "denaro", "Una banconota da dieci.", "Uma nota de dez.", "/bankoˈnɔta/", "f", "banconote"),
    ("spiccioli", "trocados", "denaro", "Hai degli spiccioli?", "Você tem uns trocados?", "/ˈspittʃoli/", "m", "spiccioli"),
    ("assegno", "cheque", "denaro", "Firmare un assegno.", "Assinar um cheque.", "/asˈseɲɲo/", "m", "assegni"),
    ("carta", "cartão", "denaro", "Carta di credito.", "Cartão de crédito.", "/ˈkarta/", "f", "carte"),
    ("bancomat", "cartão de débito/caixa eletrônico", "denaro", "Prelevare al bancomat.", "Sacar no caixa eletrônico.", "/ˈbankomat/", "m", "bancomat"),
    ("conto", "conta (bancária)", "denaro", "Aprire un conto corrente.", "Abrir uma conta corrente.", "/ˈkonto/", "m", "conti"),
    ("bonifico", "transferência", "denaro", "Fare un bonifico.", "Fazer uma transferência.", "/boˈnifiko/", "m", "bonifici"),
    ("prestito", "empréstimo", "denaro", "Chiedere un prestito.", "Pedir um empréstimo.", "/ˈprɛstito/", "m", "prestiti"),
    ("mutuo", "financiamento imobiliário", "denaro", "Il mutuo per la casa.", "O financiamento da casa.", "/ˈmutwo/", "m", "mutui"),
    ("tasso", "taxa", "denaro", "Tasso d'interesse.", "Taxa de juros.", "/ˈtasso/", "m", "tassi"),
    ("interesse", "juros", "denaro", "Pagare gli interessi.", "Pagar os juros.", "/inteˈrɛsse/", "m", "interessi"),
    ("azione", "ação (bolsa)", "finanza", "Comprare azioni.", "Comprar ações.", "/atˈtsjone/", "f", "azioni"),
    ("obbligazione", "obrigação/título", "finanza", "Investire in obbligazioni.", "Investir em títulos.", "/obbliɡatˈtsjone/", "f", "obbligazioni"),
    ("fondo", "fundo (investimento)", "finanza", "Fondo di investimento.", "Fundo de investimento.", "/ˈfondo/", "m", "fondi"),
    ("capitale", "capital", "finanza", "Avere un gran capitale.", "Ter um grande capital.", "/kapiˈtale/", "m", "capitali"),
    ("patrimonio", "patrimônio", "finanza", "Un patrimonio netto.", "Um patrimônio líquido.", "/patriˈmɔnjo/", "m", "patrimoni"),
    ("debito", "dívida", "finanza", "Avere un debito.", "Ter uma dívida.", "/ˈdebito/", "m", "debiti"),
    ("credito", "crédito", "finanza", "Una linea di credito.", "Uma linha de crédito.", "/ˈkredito/", "m", "crediti"),
    ("bilancio", "balanço", "finanza", "Il bilancio aziendale.", "O balanço da empresa.", "/biˈlantʃo/", "m", "bilanci"),
    ("fatturato", "faturamento", "finanza", "Aumentare il fatturato.", "Aumentar o faturamento.", "/fattuˈrato/", "m", "fatturati"),
    ("profitto", "lucro", "finanza", "Un buon profitto.", "Um bom lucro.", "/proˈfitto/", "m", "profitti"),
    ("guadagno", "ganho/lucro", "finanza", "Il margine di guadagno.", "A margem de lucro.", "/ɡwaˈdaɲɲo/", "m", "guadagni"),
    ("perdita", "perda/prejuízo", "finanza", "In perdita netta.", "Com prejuízo líquido.", "/ˈpɛrdita/", "f", "perdite"),
    ("spesa", "despesa", "finanza", "Tagliare le spese.", "Cortar as despesas.", "/ˈspeza/", "f", "spese"),
    ("entrata", "receita/entrada", "finanza", "Aumentare le entrate.", "Aumentar as receitas.", "/enˈtrata/", "f", "entrate"),
    ("tassa", "taxa/imposto", "finanza", "Pagare le tasse.", "Pagar os impostos.", "/ˈtassa/", "f", "tasse"),
    ("imposta", "imposto", "finanza", "Imposta sul reddito.", "Imposto de renda.", "/imˈpɔsta/", "f", "imposte"),
    ("reddito", "renda", "finanza", "Reddito annuo.", "Renda anual.", "/ˈrɛddito/", "m", "redditi"),
    ("stipendio", "salário", "finanza", "Ricevere lo stipendio.", "Receber o salário.", "/stiˈpɛndjo/", "m", "stipendi"),
    ("salario", "salário (operário)", "finanza", "Un salario minimo.", "Um salário mínimo.", "/saˈlarjo/", "m", "salari"),
    ("pensione", "aposentadoria", "finanza", "Andare in pensione.", "Se aposentar.", "/penˈsjone/", "f", "pensioni"),
    ("inflazione", "inflação", "finanza", "L'inflazione sale.", "A inflação sobe.", "/inflatˈtsjone/", "f", "inflazioni"),
    ("crisi", "crise", "finanza", "Crisi economica.", "Crise econômica.", "/ˈkrizi/", "f", "crisi"),
    ("crescita", "crescimento", "finanza", "Crescita economica.", "Crescimento econômico.", "/ˈkreʃʃita/", "f", "crescite"),
    ("sviluppo", "desenvolvimento", "finanza", "Fondi per lo sviluppo.", "Fundos para o desenvolvimento.", "/zviˈluppo/", "m", "sviluppi"),
    ("investimento", "investimento", "finanza", "Un ottimo investimento.", "Um ótimo investimento.", "/investiˈmento/", "m", "investimenti"),
    ("rischio", "risco", "finanza", "Un investimento a rischio.", "Um investimento de risco.", "/ˈriskjo/", "m", "rischi"),
    ("garanzia", "garantia", "finanza", "Offrire una garanzia.", "Oferecer uma garantia.", "/ɡaranˈtsia/", "f", "garanzie"),
    ("assicurazione", "seguro", "finanza", "L'assicurazione dell'auto.", "O seguro do carro.", "/assikuratˈtsjone/", "f", "assicurazioni"),
    ("fallimento", "falência", "finanza", "Dichiarare fallimento.", "Declarar falência.", "/falliˈmento/", "m", "fallimenti"),
    # Persone
    ("economista", "economista", "persone", "Il famoso economista.", "O famoso economista.", "/ekonoˈmista/", "m/f", "economisti"),
    ("banchiere", "banqueiro", "persone", "Un ricco banchiere.", "Um banqueiro rico.", "/banˈkjɛre/", "m", "banchieri"),
    ("investitore", "investidor", "persone", "Cercare investitori.", "Procurar investidores.", "/investiˈtore/", "m", "investitori"),
    ("azionista", "acionista", "persone", "L'assemblea degli azionisti.", "A assembleia dos acionistas.", "/attsjoˈnista/", "m/f", "azionisti"),
    ("imprenditore", "empresário", "persone", "Un giovane imprenditore.", "Um jovem empresário.", "/imprendiˈtore/", "m", "imprenditori"),
    ("socio", "sócio", "persone", "Socio d'affari.", "Sócio de negócios.", "/ˈsɔtʃo/", "m", "soci"),
    ("cliente", "cliente", "persone", "Il cliente ha ragione.", "O cliente tem razão.", "/kliˈɛnte/", "m/f", "clienti"),
    ("consumatore", "consumidor", "persone", "I diritti del consumatore.", "Os direitos do consumidor.", "/konsumaˈtore/", "m", "consumatori"),
    ("dipendente", "empregado/funcionário", "persone", "I dipendenti dell'azienda.", "Os funcionários da empresa.", "/dipenˈdɛnte/", "m", "dipendenti"),
    ("datore", "empregador", "persone", "Il datore di lavoro.", "O empregador.", "/daˈtore/", "m", "datori"),
    # Verbi
    ("pagare", "pagar", "verbi", "Pagare il conto.", "Pagar a conta.", "/paˈɡare/", None, None),
    ("comprare", "comprar", "verbi", "Comprare azioni.", "Comprar ações.", "/komˈprare/", None, None),
    ("vendere", "vender", "verbi", "Vendere a caro prezzo.", "Vender a preço caro.", "/ˈvendere/", None, None),
    ("spendere", "gastar", "verbi", "Spendere tutto.", "Gastar tudo.", "/ˈspɛndere/", None, None),
    ("risparmiare", "economizar/poupar", "verbi", "Risparmiare per il futuro.", "Poupar para o futuro.", "/risparˈmjare/", None, None),
    ("guadagnare", "ganhar (dinheiro)", "verbi", "Guadagnare bene.", "Ganhar bem.", "/ɡwadaɲˈɲare/", None, None),
    ("perdere", "perder", "verbi", "Perdere soldi in borsa.", "Perder dinheiro na bolsa.", "/ˈpɛrdere/", None, None),
    ("investire", "investir", "verbi", "Investire nel mattone.", "Investir em imóveis.", "/invesˈtire/", None, None),
    ("prestare", "emprestar (dar)", "verbi", "Prestare soldi a un amico.", "Emprestar dinheiro a um amigo.", "/presˈtare/", None, None),
    ("chiedere", "pedir/tomar emprestato", "verbi", "Chiedere un prestito.", "Pedir um empréstimo.", "/ˈkjɛdere/", None, None),
    ("prelevare", "sacar (dinheiro)", "verbi", "Prelevare dal bancomat.", "Sacar no caixa eletrônico.", "/preleˈvare/", None, None),
    ("versare", "depositar", "verbi", "Versare sul conto.", "Depositar na conta.", "/verˈsare/", None, None),
    ("finanziare", "financiar", "verbi", "Finanziare un progetto.", "Financiar um projeto.", "/finanˈtsjare/", None, None),
    ("assumere", "contratar", "verbi", "Assumere personale.", "Contratar pessoal.", "/asˈsumere/", None, None),
    ("licenziare", "demitir", "verbi", "Licenziare i dipendenti.", "Demitir os funcionários.", "/litʃenˈtsjare/", None, None),
    ("dichiarare", "declarar", "verbi", "Dichiarare le tasse.", "Declarar os impostos.", "/dikjaˈrare/", None, None),
    ("fallire", "falir", "verbi", "L'azienda è fallita.", "A empresa faliu.", "/falˈlire/", None, None),
    ("costare", "custar", "verbi", "Quanto costa?", "Quanto custa?", "/kosˈtare/", None, None),
    ("valutare", "avaliar", "verbi", "Valutare un immobile.", "Avaliar um imóvel.", "/valuˈtare/", None, None),
    ("scambiare", "trocar/cambiar", "verbi", "Scambiare valuta estera.", "Trocar moeda estrangeira.", "/skamˈbjare/", None, None),
    # Aggettivi
    ("economico", "econômico/barato", "aggettivi", "Crescita economica.", "Crescimento econômico.", "/ekoˈnɔmiko/", "m", "economici"),
    ("finanziario", "financeiro", "aggettivi", "Consulente finanziario.", "Consultor financeiro.", "/finanˈtsjarjo/", "m", "finanziari"),
    ("commerciale", "comercial", "aggettivi", "Centro commerciale.", "Centro comercial.", "/kommerˈtʃale/", "m", "commerciali"),
    ("pubblico", "público", "aggettivi", "Debito pubblico.", "Dívida pública.", "/ˈpubbliko/", "m", "pubblici"),
    ("privato", "privado", "aggettivi", "Settore privato.", "Setor privado.", "/priˈvato/", "m", "privati"),
    ("caro", "caro", "aggettivi", "Un prezzo caro.", "Um preço caro.", "/ˈkaro/", "m", "cari"),
    ("costoso", "custoso/caro", "aggettivi", "Un progetto costoso.", "Um projeto caro.", "/kosˈtozo/", "m", "costosi"),
    ("conveniente", "conveniente/vantajoso", "aggettivi", "Un'offerta conveniente.", "Uma oferta vantajosa.", "/konveˈnjɛnte/", "m", "convenienti"),
    ("redditizio", "rentável", "aggettivi", "Affare redditizio.", "Negócio rentável.", "/reddiˈtittsjo/", "m", "redditizi"),
    ("gratuito", "gratuito", "aggettivi", "Servizio gratuito.", "Serviço gratuito.", "/ɡraˈtuito/", "m", "gratuiti"),
    ("lordo", "bruto", "aggettivi", "Stipendio lordo.", "Salário bruto.", "/ˈlordo/", "m", "lordi"),
    ("netto", "líquido (valor)", "aggettivi", "Peso netto.", "Peso líquido.", "/ˈnetto/", "m", "netti"),
    ("fiscale", "fiscal", "aggettivi", "Anno fiscale.", "Ano fiscal.", "/fisˈkale/", "m", "fiscali"),
    ("ricco", "rico", "aggettivi", "Un uomo ricco.", "Um homem rico.", "/ˈrikko/", "m", "ricchi"),
    ("povero", "pobre", "aggettivi", "Un quartiere povero.", "Um bairro pobre.", "/ˈpɔvero/", "m", "poveri"),
    ("stabile", "estável", "aggettivi", "Prezzo stabile.", "Preço estável.", "/ˈstabile/", "m", "stabili"),
    ("instabile", "instável", "aggettivi", "Mercato instabile.", "Mercado instável.", "/insˈtabile/", "m", "instabili"),
    ("nazionale", "nacional", "aggettivi", "Banca nazionale.", "Banco nacional.", "/natsjoˈnale/", "m", "nazionali"),
    ("internazionale", "internacional", "aggettivi", "Commercio internazionale.", "Comércio internacional.", "/internatsjoˈnale/", "m", "internazionali"),
    ("globale", "global", "aggettivi", "Economia globale.", "Economia global.", "/ɡloˈbale/", "m", "globali")
]

# T41: La Filosofia e il Pensiero (110 parole)
t41_data = [
    # Concetti Fondamentali
    ("filosofia", "filosofia", "concetti", "Studiare la filosofia.", "Estudar a filosofia.", "/filozoˈfia/", "f", "filosofie"),
    ("pensiero", "pensamento", "concetti", "Il pensiero di Socrate.", "O pensamento de Sócrates.", "/penˈsjɛro/", "m", "pensieri"),
    ("idea", "ideia", "concetti", "Il mondo delle idee.", "O mundo das ideias.", "/iˈdɛa/", "f", "idee"),
    ("ragione", "razão", "concetti", "La pura ragione.", "A pura razão.", "/raˈdʒone/", "f", "ragioni"),
    ("verità", "verdade", "concetti", "Cercare la verità.", "Buscar a verdade.", "/veriˈta/", "f", "verità"),
    ("realtà", "realidade", "concetti", "Che cos'è la realtà?", "O que é a realidade?", "/realˈta/", "f", "realtà"),
    ("essere", "ser (subst.)", "concetti", "L'essere e il nulla.", "O ser e o nada.", "/ˈɛssere/", "m", "esseri"),
    ("esistenza", "existência", "concetti", "Il senso dell'esistenza.", "O sentido da existência.", "/ezisˈtɛntsa/", "f", "esistenze"),
    ("natura", "natureza", "concetti", "La natura umana.", "A natureza humana.", "/naˈtura/", "f", "nature"),
    ("anima", "alma", "concetti", "L'immortalità dell'anima.", "A imortalidade da alma.", "/ˈanima/", "f", "anime"),
    ("mente", "mente", "concetti", "La mente e il corpo.", "A mente e o corpo.", "/ˈmente/", "f", "menti"),
    ("corpo", "corpo", "concetti", "Il corpo fisico.", "O corpo físico.", "/ˈkɔrpo/", "m", "corpi"),
    ("materia", "matéria", "concetti", "Forma e materia.", "Forma e matéria.", "/maˈtɛrja/", "f", "materie"),
    ("spirito", "espírito", "concetti", "Lo spirito assoluto.", "O espírito absoluto.", "/ˈspirito/", "m", "spiriti"),
    ("conoscenza", "conhecimento", "concetti", "La teoria della conoscenza.", "A teoria do conhecimento.", "/konoʃˈʃɛntsa/", "f", "conoscenze"),
    ("sapienza", "sabedoria", "concetti", "Amare la sapienza.", "Amar a sabedoria.", "/saˈpjɛntsa/", "f", "sapienze"),
    ("saggezza", "sabedoria (prática)", "concetti", "La saggezza degli antichi.", "A sabedoria dos antigos.", "/sadˈdʒettsa/", "f", "saggezze"),
    ("etica", "ética", "discipline", "L'etica morale.", "A ética moral.", "/ˈɛtika/", "f", "etiche"),
    ("morale", "moral", "discipline", "Il giudizio morale.", "O julgamento moral.", "/moˈrale/", "f", "morali"),
    ("logica", "lógica", "discipline", "La logica formale.", "A lógica formal.", "/ˈlɔdʒika/", "f", "logiche"),
    ("estetica", "estética", "discipline", "L'estetica del bello.", "A estética do belo.", "/esˈtɛtika/", "f", "estetiche"),
    ("metafisica", "metafísica", "discipline", "Studiare la metafisica.", "Estudar a metafísica.", "/metaˈfizika/", "f", "metafisiche"),
    ("ontologia", "ontologia", "discipline", "L'ontologia dell'essere.", "A ontologia do ser.", "/ontoloˈdʒia/", "f", "ontologie"),
    ("epistemologia", "epistemologia", "discipline", "L'epistemologia della scienza.", "A epistemologia da ciência.", "/epistemoloˈdʒia/", "f", "epistemologie"),
    # Concetti Astratti e Strumenti del Pensiero
    ("concetto", "conceito", "concetti", "Un concetto astratto.", "Um conceito abstrato.", "/konˈtʃɛtto/", "m", "concetti"),
    ("teoria", "teoria", "concetti", "La teoria platonica.", "A teoria platônica.", "/teoˈria/", "f", "teorie"),
    ("ipotesi", "hipótese", "concetti", "Un'ipotesi di lavoro.", "Uma hipótese de trabalho.", "/iˈpɔtezi/", "f", "ipotesi"),
    ("tesi", "tese", "concetti", "Dimostrare la tesi.", "Demonstrar a tese.", "/ˈtɛzi/", "f", "tesi"),
    ("antitesi", "antítese", "concetti", "Tesi, antitesi, sintesi.", "Tese, antítese, síntese.", "/anˈtitezi/", "f", "antitesi"),
    ("sintesi", "síntese", "concetti", "La sintesi finale.", "A síntese final.", "/ˈsintezi/", "f", "sintesi"),
    ("principio", "princípio", "concetti", "Il principio di non contraddizione.", "O princípio da não contradição.", "/prinˈtʃipjo/", "m", "principi"),
    ("causa", "causa", "concetti", "Causa ed effetto.", "Causa e efeito.", "/ˈkauza/", "f", "cause"),
    ("effetto", "efeito", "concetti", "Ogni causa ha un effetto.", "Toda causa tem um efeito.", "/efˈfɛtto/", "m", "effetti"),
    ("fine", "fim/finalidade", "concetti", "Il fine giustifica i mezzi.", "O fim justifica os meios.", "/ˈfine/", "m", "fini"),
    ("mezzo", "meio (instrumento)", "concetti", "Il mezzo per arrivare.", "O meio para chegar.", "/ˈmɛddzo/", "m", "mezzi"),
    ("spazio", "espaço", "concetti", "Lo spazio e il tempo.", "O espaço e o tempo.", "/ˈspattsjo/", "m", "spazi"),
    ("tempo", "tempo", "concetti", "Il tempo fugge.", "O tempo foge.", "/ˈtɛmpo/", "m", "tempi"),
    ("libertà", "liberdade", "concetti", "La libertà di scelta.", "A liberdade de escolha.", "/liberˈta/", "f", "libertà"),
    ("necessità", "necessidade", "concetti", "Agire per necessità.", "Agir por necessidade.", "/netʃessiˈta/", "f", "necessità"),
    ("volontà", "vontade", "concetti", "La volontà di potenza.", "A vontade de potência.", "/volonˈta/", "f", "volontà"),
    ("destino", "destino", "concetti", "Credere nel destino.", "Acreditar no destino.", "/desˈtino/", "m", "destini"),
    ("caso", "acaso", "concetti", "Frutto del caso.", "Fruto do acaso.", "/ˈkazo/", "m", "casi"),
    ("dovere", "dever", "concetti", "Il senso del dovere.", "O sentido do dever.", "/doˈvere/", "m", "doveri"),
    ("diritto", "direito", "concetti", "Il diritto naturale.", "O direito natural.", "/diˈritto/", "m", "diritti"),
    ("giustizia", "justiça", "concetti", "La virtù della giustizia.", "A virtude da justiça.", "/dʒusˈtittsja/", "f", "giustizie"),
    ("virtù", "virtude", "concetti", "La virtù e il vizio.", "A virtude e o vício.", "/virˈtu/", "f", "virtù"),
    ("vizio", "vício", "concetti", "Un brutto vizio.", "Um feio vício.", "/ˈvittsjo/", "m", "vizi"),
    ("bene", "bem (o bem)", "concetti", "Fare il bene.", "Fazer o bem.", "/ˈbɛne/", "m", "beni"),
    ("male", "mal (o mal)", "concetti", "Il problema del male.", "O problema do mal.", "/ˈmale/", "m", "mali"),
    ("felicità", "felicidade", "concetti", "La ricerca della felicità.", "A busca da felicidade.", "/felitʃiˈta/", "f", "felicità"),
    ("dolore", "dor", "concetti", "Il dolore dell'esistenza.", "A dor da existência.", "/doˈlore/", "m", "dolori"),
    ("piacere", "prazer", "concetti", "Il principio di piacere.", "O princípio de prazer.", "/pjaˈtʃere/", "m", "piaceri"),
    ("dubbio", "dúvida", "concetti", "Il dubbio metodico.", "A dúvida metódica.", "/ˈdubbjo/", "m", "dubbi"),
    ("certezza", "certeza", "concetti", "Non ho nessuna certezza.", "Não tenho nenhuma certeza.", "/tʃerˈtettsa/", "f", "certezze"),
    ("paradosso", "paradoxo", "concetti", "Il paradosso del mentitore.", "O paradoxo do mentiroso.", "/paraˈdɔsso/", "m", "paradossi"),
    ("dilemma", "dilema", "concetti", "Un dilemma morale.", "Um dilema moral.", "/diˈlɛmma/", "m", "dilemmi"),
    ("mito", "mito", "concetti", "Il mito della caverna.", "O mito da caverna.", "/ˈmito/", "m", "miti"),
    ("dialogo", "diálogo", "concetti", "I dialoghi platonici.", "Os diálogos platônicos.", "/diˈaloɡo/", "m", "dialoghi"),
    ("critica", "crítica", "concetti", "La critica della ragion pura.", "A crítica da razão pura.", "/ˈkritika/", "f", "critiche"),
    # Persone e Correnti
    ("filosofo", "filósofo", "persone", "Aristotele è un filosofo.", "Aristóteles é um filósofo.", "/fiˈlɔzofo/", "m", "filosofi"),
    ("pensatore", "pensador", "persone", "Un grande pensatore.", "Um grande pensador.", "/pensaˈtore/", "m", "pensatori"),
    ("maestro", "mestre", "persone", "Il maestro insegna.", "O mestre ensina.", "/maˈɛstro/", "m", "maestri"),
    ("allievo", "aluno/discípulo", "persone", "L'allievo supera il maestro.", "O aluno supera o mestre.", "/alˈljɛvo/", "m", "allievi"),
    ("sofista", "sofista", "persone", "Il discorso del sofista.", "O discurso do sofista.", "/soˈfista/", "m", "sofisti"),
    ("idealismo", "idealismo", "correnti", "L'idealismo tedesco.", "O idealismo alemão.", "/ideaˈlizmo/", "m", "idealismi"),
    ("empirismo", "empirismo", "correnti", "L'empirismo inglese.", "O empirismo inglês.", "/empiˈrizmo/", "m", "empirismi"),
    ("razionalismo", "racionalismo", "correnti", "Il razionalismo di Cartesio.", "O racionalismo de Descartes.", "/rattsjonaˈlizmo/", "m", "razionalismi"),
    ("esistenzialismo", "existencialismo", "correnti", "L'esistenzialismo di Sartre.", "O existencialismo de Sartre.", "/ezistentsjaˈlizmo/", "m", "esistenzialismi"),
    ("nichilismo", "niilismo", "correnti", "Il nichilismo moderno.", "O niilismo moderno.", "/nikiˈlizmo/", "m", "nichilismi"),
    # Verbi
    ("pensare", "pensar", "verbi", "Penso, dunque sono.", "Penso, logo existo.", "/penˈsare/", None, None),
    ("riflettere", "refletir", "verbi", "Riflettere sulla vita.", "Refletir sobre a vida.", "/riˈflɛttere/", None, None),
    ("ragionare", "raciocinar", "verbi", "Ragionare con la propria testa.", "Raciocinar com a própria cabeça.", "/radʒoˈnare/", None, None),
    ("dubitare", "duvidar", "verbi", "Dubitare di tutto.", "Duvidar de tudo.", "/dubiˈtare/", None, None),
    ("credere", "acreditar/crer", "verbi", "Credere nella verità.", "Crer na verdade.", "/ˈkredere/", None, None),
    ("conoscere", "conhecer", "verbi", "Conoscere se stessi.", "Conhecer a si mesmo.", "/koˈnoʃʃere/", None, None),
    ("comprendere", "compreender", "verbi", "Comprendere il mondo.", "Compreender o mundo.", "/komˈprɛndere/", None, None),
    ("giudicare", "julgar", "verbi", "Non giudicare le azioni.", "Não julgar as ações.", "/dʒudiˈkare/", None, None),
    ("dimostrare", "demonstrar", "verbi", "Dimostrare una teoria.", "Demonstrar uma teoria.", "/dimosˈtrare/", None, None),
    ("dedurre", "deduzir", "verbi", "Dedurre la conclusione.", "Deduzir a conclusão.", "/deˈdurre/", None, None),
    ("indurre", "induzir", "verbi", "Indurre un principio.", "Induzir um princípio.", "/inˈdurre/", None, None),
    ("spiegare", "explicar", "verbi", "Spiegare il fenomeno.", "Explicar o fenômeno.", "/spjeˈɡare/", None, None),
    ("sostenere", "sustentar/apoiar", "verbi", "Sostenere una tesi.", "Sustentar uma tese.", "/sosteˈnere/", None, None),
    ("negare", "negar", "verbi", "Negare l'evidenza.", "Negar a evidência.", "/neˈɡare/", None, None),
    ("affermare", "afirmar", "verbi", "Affermare il vero.", "Afirmar o verdadeiro.", "/afferˈmare/", None, None),
    # Aggettivi e Descrittori
    ("filosofico", "filosófico", "aggettivi", "Un dibattito filosofico.", "Um debate filosófico.", "/filoˈzɔfiko/", "m", "filosofici"),
    ("astratto", "abstrato", "aggettivi", "Un concetto astratto.", "Um conceito abstrato.", "/asˈtratto/", "m", "astratti"),
    ("concreto", "concreto", "aggettivi", "Un esempio concreto.", "Um exemplo concreto.", "/konˈkrɛto/", "m", "concreti"),
    ("assoluto", "absoluto", "aggettivi", "La verità assoluta.", "A verdade absoluta.", "/assoˈluto/", "m", "assoluti"),
    ("relativo", "relativo", "aggettivi", "Tutto è relativo.", "Tudo é relativo.", "/relaˈtivo/", "m", "relativi"),
    ("universale", "universal", "aggettivi", "Una legge universale.", "Uma lei universal.", "/univerˈsale/", "m", "universali"),
    ("particolare", "particular", "aggettivi", "Un caso particolare.", "Um caso particular.", "/partikoˈlare/", "m", "particolari"),
    ("razionale", "racional", "aggettivi", "Essere razionale.", "Ser racional.", "/rattsjoˈnale/", "m", "razionali"),
    ("irrazionale", "irracional", "aggettivi", "Una paura irrazionale.", "Um medo irracional.", "/irrattsjoˈnale/", "m", "irrazionali"),
    ("soggettivo", "subjetivo", "aggettivi", "Il giudizio è soggettivo.", "O julgamento é subjetivo.", "/soddʒetˈtivo/", "m", "soggettivi"),
    ("oggettivo", "objetivo", "aggettivi", "Un fatto oggettivo.", "Um fato objetivo.", "/oddʒetˈtivo/", "m", "oggettivi"),
    ("empirico", "empírico", "aggettivi", "Il metodo empirico.", "O método empírico.", "/emˈpiriko/", "m", "empirici"),
    ("teorico", "teórico", "aggettivi", "Un modello teorico.", "Um modelo teórico.", "/teˈɔriko/", "m", "teorici"),
    ("pratico", "prático", "aggettivi", "La ragion pratica.", "A razão prática.", "/ˈpratiko/", "m", "pratici"),
    ("morale", "moral (adj)", "aggettivi", "Un obbligo morale.", "Uma obrigação moral.", "/moˈrale/", "m", "morali"),
    ("etico", "ético", "aggettivi", "Un problema etico.", "Um problema ético.", "/ˈɛtiko/", "m", "etici"),
    ("giusto", "justo", "aggettivi", "Ciò che è giusto.", "O que é justo.", "/ˈdʒusto/", "m", "giusti"),
    ("sbagliato", "errado", "aggettivi", "Ciò che è sbagliato.", "O que é errado.", "/zbaˈʎʎato/", "m", "sbagliati"),
    ("vero", "verdadeiro", "aggettivi", "È vero o falso?", "É verdadeiro ou falso?", "/ˈvero/", "m", "veri"),
    ("falso", "falso", "aggettivi", "Un sillogismo falso.", "Um silogismo falso.", "/ˈfalso/", "m", "falsi")
]

def create_new(templo_num, nome, citta, livello, parole_data):
    palavras = []
    for i, (it, pt, cat, ex_it, ex_pt, ipa, gen, pl) in enumerate(parole_data, 1):
        tid = f"t{templo_num}_{i:03d}"
        palavras.append(w(tid, it, pt, cat, ex_it, ex_pt, ipa, gen, pl))
        
    obj = {
        "templo": templo_num,
        "nome": nome,
        "cidade": citta,
        "nivel": livello,
        "palavras": palavras
    }
    
    path = os.path.join(OUT, "data", f"templo-{templo_num}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"CREATED templo-{templo_num}.json -- {len(palavras)} parole")

if __name__ == "__main__":
    append_to_existing(34, t34_add)
    append_to_existing(35, t35_add)
    append_to_existing(36, t36_add)
    append_to_existing(37, t37_add)
    
    create_new(38, "La Psicologia e la Mente", "Bologna", "B2", t38_data)
    create_new(39, "L'Astronomia e lo Spazio", "Pisa", "C1", t39_data)
    create_new(40, "L'Economia e la Finanza", "Milano", "C1", t40_data)
    create_new(41, "La Filosofia e il Pensiero", "Roma", "C2", t41_data)
