import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

def w(tid, it, pt, cat, ex_it, ex_pt, ipa="", gen=None, pl=None):
    return {
        "id": tid, "italiano": it, "portugues": pt, "genero": gen, "plural": pl,
        "exemplo": ex_it, "exemplo_pt": ex_pt, "categoria": cat, "dificuldade": "difficile", "audio_ipa": ipa
    }

# T42: La Letteratura Classica (110 parole)
t42_data = [
    # Opere e Autori
    ("letteratura", "literatura", "letteratura", "La letteratura italiana.", "A literatura italiana.", "/letteraˈtura/", "f", "letterature"),
    ("classico", "clássico", "letteratura", "Un classico della letteratura.", "Um clássico da literatura.", "/ˈklassiko/", "m", "classici"),
    ("poema", "poema/épico", "letteratura", "Il poema epico.", "O poema épico.", "/poˈɛma/", "m", "poemi"),
    ("poesia", "poesia", "letteratura", "Una poesia d'amore.", "Uma poesia de amor.", "/poeˈzia/", "f", "poesie"),
    ("romanzo", "romance (livro)", "letteratura", "Un romanzo storico.", "Um romance histórico.", "/roˈmandzo/", "m", "romanzi"),
    ("racconto", "conto/relato", "letteratura", "Un racconto breve.", "Um conto curto.", "/rakˈkonto/", "m", "racconti"),
    ("novella", "novela/conto", "letteratura", "Le novelle di Boccaccio.", "As novelas de Boccaccio.", "/noˈvɛlla/", "f", "novelle"),
    ("tragedia", "tragédia", "letteratura", "Una tragedia greca.", "Uma tragédia grega.", "/traˈdʒɛdja/", "f", "tragedie"),
    ("commedia", "comédia", "letteratura", "La Divina Commedia.", "A Divina Comédia.", "/komˈmɛdja/", "f", "commedie"),
    ("dramma", "drama", "letteratura", "Un dramma teatrale.", "Um drama teatral.", "/ˈdramma/", "m", "drammi"),
    ("opera", "obra", "letteratura", "L'opera omnia.", "A obra completa.", "/ˈɔpera/", "f", "opere"),
    ("capolavoro", "obra-prima", "letteratura", "Il capolavoro di Dante.", "A obra-prima de Dante.", "/kapolaˈvoro/", "m", "capolavori"),
    ("autore", "autor", "persone", "L'autore del libro.", "O autor do livro.", "/auˈtore/", "m", "autori"),
    ("scrittore", "escritor", "persone", "Uno scrittore famoso.", "Um escritor famoso.", "/skritˈtore/", "m", "scrittori"),
    ("poeta", "poeta", "persone", "Il sommo poeta.", "O sumo poeta.", "/poˈɛta/", "m", "poeti"),
    ("narratore", "narrador", "persone", "Il narratore onnisciente.", "O narrador onisciente.", "/narraˈtore/", "m", "narratori"),
    ("protagonista", "protagonista", "personaggi", "Il protagonista della storia.", "O protagonista da história.", "/protagoˈnista/", "m/f", "protagonisti"),
    ("antagonista", "antagonista", "personaggi", "L'antagonista principale.", "O antagonista principal.", "/antagoˈnista/", "m/f", "antagonisti"),
    ("personaggio", "personagem", "personaggi", "Un personaggio complesso.", "Um personagem complexo.", "/personˈaddʒo/", "m", "personaggi"),
    ("eroe", "herói", "personaggi", "L'eroe tragico.", "O herói trágico.", "/eˈrɔe/", "m", "eroi"),
    # Elementi letterari
    ("trama", "enredo/trama", "elementi", "La trama del romanzo.", "O enredo do romance.", "/ˈtrama/", "f", "trame"),
    ("capitolo", "capítulo", "elementi", "Il primo capitolo.", "O primeiro capítulo.", "/kaˈpitolo/", "m", "capitoli"),
    ("verso", "verso", "elementi", "Scrivere in versi.", "Escrever em versos.", "/ˈvɛrso/", "m", "versi"),
    ("strofa", "estrofe", "elementi", "La prima strofa.", "A primeira estrofe.", "/ˈstrɔfa/", "f", "strofe"),
    ("rima", "rima", "elementi", "Una rima baciata.", "Uma rima emparelhada.", "/ˈrima/", "f", "rime"),
    ("prosa", "prosa", "elementi", "Scrivere in prosa.", "Escrever em prosa.", "/ˈprɔza/", "f", "prose"),
    ("metrica", "métrica", "elementi", "La metrica latina.", "A métrica latina.", "/ˈmɛtrika/", "f", "metriche"),
    ("stile", "estilo", "elementi", "Lo stile dell'autore.", "O estilo do autor.", "/ˈstile/", "m", "stili"),
    ("metafora", "metáfora", "figure", "Una bellissima metafora.", "Uma belíssima metáfora.", "/meˈtafora/", "f", "metafore"),
    ("similitudine", "símile/comparação", "figure", "Usare una similitudine.", "Usar uma comparação.", "/similiˈtudine/", "f", "similitudini"),
    ("allegoria", "alegoria", "figure", "Un'allegoria complessa.", "Uma alegoria complexa.", "/alleɡoˈria/", "f", "allegorie"),
    ("ironia", "ironia", "figure", "Sottile ironia.", "Sutil ironia.", "/iroˈnia/", "f", "ironie"),
    ("sarcasmo", "sarcasmo", "figure", "Pieno di sarcasmo.", "Cheio de sarcasmo.", "/sarˈkazmo/", "m", "sarcasmi"),
    ("satira", "sátira", "letteratura", "Fare della satira.", "Fazer sátira.", "/ˈsatira/", "f", "satire"),
    ("epica", "épica", "letteratura", "L'epica antica.", "A épica antiga.", "/ˈɛpika/", "f", "epiche"),
    ("lirica", "lírica", "letteratura", "La lirica greca.", "A lírica grega.", "/ˈlirika/", "f", "liriche"),
    ("dialogo", "diálogo", "elementi", "Un dialogo serrato.", "Um diálogo acirrado.", "/diˈaloɡo/", "m", "dialoghi"),
    ("monologo", "monólogo", "elementi", "Un lungo monologo.", "Um longo monólogo.", "/moˈnɔloɡo/", "m", "monologhi"),
    ("citazione", "citação", "elementi", "Una citazione famosa.", "Uma citação famosa.", "/tʃitatˈtsjone/", "f", "citazioni"),
    ("introduzione", "introdução", "elementi", "L'introduzione al libro.", "A introdução ao livro.", "/introdutˈtsjone/", "f", "introduzioni"),
    ("prefazione", "prefácio", "elementi", "La prefazione dell'autore.", "O prefácio do autor.", "/prefatˈtsjone/", "f", "prefazioni"),
    ("epilogo", "epílogo", "elementi", "L'epilogo della storia.", "O epílogo da história.", "/eˈpiloɡo/", "m", "epiloghi"),
    ("incipit", "íncipit/início", "elementi", "Un incipit memorabile.", "Um início memorável.", "/ˈintʃipit/", "m", "incipit"),
    ("finale", "final", "elementi", "Un finale a sorpresa.", "Um final surpresa.", "/fiˈnale/", "m", "finali"),
    ("lettura", "leitura", "azione", "Buona lettura.", "Boa leitura.", "/letˈtura/", "f", "letture"),
    ("scrittura", "escrita", "azione", "La scrittura creativa.", "A escrita criativa.", "/skritˈtura/", "f", "scritture"),
    ("biblioteca", "biblioteca", "luoghi", "Studiare in biblioteca.", "Estudar na biblioteca.", "/bibljoˈtɛka/", "f", "biblioteche"),
    ("archivio", "arquivo", "luoghi", "Un vecchio archivio.", "Um velho arquivo.", "/arˈkivjo/", "m", "archivi"),
    ("manoscritto", "manuscrito", "oggetti", "Un manoscritto antico.", "Um manuscrito antigo.", "/manosˈkritto/", "m", "manoscritti"),
    ("pergamena", "pergaminho", "oggetti", "Scritto su pergamena.", "Escrito em pergaminho.", "/perɡaˈmɛna/", "f", "pergamene"),
    # Verbi
    ("leggere", "ler", "verbi", "Leggere un libro.", "Ler um livro.", "/ˈlɛddʒere/", None, None),
    ("scrivere", "escrever", "verbi", "Scrivere un romanzo.", "Escrever um romance.", "/ˈskrivere/", None, None),
    ("narrare", "narrar", "verbi", "Narrare le gesta.", "Narrar os feitos.", "/narˈrare/", None, None),
    ("raccontare", "contar", "verbi", "Raccontare una storia.", "Contar uma história.", "/rakkonˈtare/", None, None),
    ("descrivere", "descrever", "verbi", "Descrivere un paesaggio.", "Descrever uma paisagem.", "/desˈkrivere/", None, None),
    ("citare", "citar", "verbi", "Citare Dante.", "Citar Dante.", "/tʃiˈtare/", None, None),
    ("recitare", "recitar/atuar", "verbi", "Recitare una poesia.", "Recitar uma poesia.", "/retʃiˈtare/", None, None),
    ("pubblicare", "publicar", "verbi", "Pubblicare un saggio.", "Publicar um ensaio.", "/pubbliˈkare/", None, None),
    ("stampare", "imprimir", "verbi", "Stampare un volume.", "Imprimir um volume.", "/stamˈpare/", None, None),
    ("tradurre", "traduzir", "verbi", "Tradurre dal latino.", "Traduzir do latim.", "/traˈdurre/", None, None),
    ("sfogliare", "folhear", "verbi", "Sfogliare le pagine.", "Folhear as páginas.", "/sfoˈʎʎare/", None, None),
    ("dedicare", "dedicar", "verbi", "Dedicare il libro.", "Dedicar o livro.", "/dediˈkare/", None, None),
    ("interpretare", "interpretar", "verbi", "Interpretare il testo.", "Interpretar o texto.", "/interpreˈtare/", None, None),
    ("immaginare", "imaginar", "verbi", "Immaginare mondi.", "Imaginar mundos.", "/immadʒiˈnare/", None, None),
    ("ispirare", "inspirar", "verbi", "Ispirare il poeta.", "Inspirar o poeta.", "/ispiˈrare/", None, None),
    ("emozionare", "emocionar", "verbi", "Il racconto mi emoziona.", "O conto me emociona.", "/emotsjoˈnare/", None, None),
    ("tramandare", "transmitir (tradição)", "verbi", "Tramandare ai posteri.", "Transmitir aos pósteros.", "/tramanˈdare/", None, None),
    ("declamare", "declamar", "verbi", "Declamare dei versi.", "Declamar uns versos.", "/deklaˈmare/", None, None),
    ("evocare", "evocar", "verbi", "Evocare un'immagine.", "Evocar uma imagem.", "/evoˈkare/", None, None),
    ("inventare", "inventar", "verbi", "Inventare una scusa.", "Inventar uma desculpa.", "/invenˈtare/", None, None),
    # Aggettivi e descrittori
    ("letterario", "literário", "aggettivi", "Un premio letterario.", "Um prêmio literário.", "/letteˈrarjo/", "m", "letterari"),
    ("classico", "clássico (adj)", "aggettivi", "Il mondo classico.", "O mundo clássico.", "/ˈklassiko/", "m", "classici"),
    ("antico", "antigo", "aggettivi", "Un testo antico.", "Um texto antigo.", "/anˈtiko/", "m", "antichi"),
    ("moderno", "moderno", "aggettivi", "Un autore moderno.", "Um autor moderno.", "/moˈdɛrno/", "m", "moderni"),
    ("contemporaneo", "contemporâneo", "aggettivi", "Arte contemporanea.", "Arte contemporânea.", "/kontempoˈraneo/", "m", "contemporanei"),
    ("epico", "épico", "aggettivi", "Una battaglia epica.", "Uma batalha épica.", "/ˈɛpiko/", "m", "epici"),
    ("lirico", "lírico", "aggettivi", "Un tono lirico.", "Um tom lírico.", "/ˈliriko/", "m", "lirici"),
    ("drammatico", "dramático", "aggettivi", "Un evento drammatico.", "Um evento dramático.", "/dramˈmatiko/", "m", "drammatici"),
    ("comico", "cômico", "aggettivi", "Un attore comico.", "Um ator cômico.", "/ˈkɔmiko/", "m", "comici"),
    ("tragico", "trágico", "aggettivi", "Un destino tragico.", "Um destino trágico.", "/ˈtradʒiko/", "m", "tragici"),
    ("romantico", "romântico", "aggettivi", "Il periodo romantico.", "O período romântico.", "/roˈmantiko/", "m", "romantici"),
    ("realista", "realista", "aggettivi", "Un romanzo realista.", "Um romance realista.", "/reaˈlista/", "m/f", "realisti"),
    ("fantastico", "fantástico", "aggettivi", "Un racconto fantastico.", "Um conto fantástico.", "/fanˈtastiko/", "m", "fantastici"),
    ("storico", "histórico", "aggettivi", "Un romanzo storico.", "Um romance histórico.", "/ˈstɔriko/", "m", "storici"),
    ("poetico", "poético", "aggettivi", "Un linguaggio poetico.", "Uma linguagem poética.", "/poˈɛtiko/", "m", "poetici"),
    ("prosastico", "prosaico", "aggettivi", "Uno stile prosastico.", "Um estilo prosaico.", "/proˈzastiko/", "m", "prosastici"),
    ("immaginario", "imaginário", "aggettivi", "Un mondo immaginario.", "Um mundo imaginário.", "/immadʒiˈnarjo/", "m", "immaginari"),
    ("affascinante", "fascinante", "aggettivi", "Una storia affascinante.", "Uma história fascinante.", "/affaʃʃiˈnante/", "m", "affascinanti"),
    ("noioso", "chato/entediante", "aggettivi", "Un libro noioso.", "Um livro chato.", "/noˈjozo/", "m", "noiosi"),
    ("profondo", "profundo", "aggettivi", "Un significato profondo.", "Um significado profundo.", "/proˈfondo/", "m", "profondi"),
    ("superficiale", "superficial", "aggettivi", "Una lettura superficiale.", "Uma leitura superficial.", "/superfiˈtʃale/", "m", "superficiali"),
    ("originale", "original", "aggettivi", "Un'idea originale.", "Uma ideia original.", "/oridʒiˈnale/", "m", "originali"),
    ("banale", "banal", "aggettivi", "Una trama banale.", "Um enredo banal.", "/baˈnale/", "m", "banali"),
    ("inedito", "inédito", "aggettivi", "Un manoscritto inedito.", "Um manuscrito inédito.", "/iˈnɛdito/", "m", "inediti"),
    ("postumo", "póstumo", "aggettivi", "Un'opera postuma.", "Uma obra póstuma.", "/ˈpɔstumo/", "m", "postumi"),
    ("immortale", "imortal", "aggettivi", "Un'opera immortale.", "Uma obra imortal.", "/immorˈtale/", "m", "immortali"),
    ("celebrità", "celebridade", "persone", "L'autore è una celebrità.", "O autor é uma celebridade.", "/tʃelebriˈta/", "f", "celebrità"),
    ("eloquente", "eloquente", "aggettivi", "Un discorso eloquente.", "Um discurso eloquente.", "/eloˈkwɛnte/", "m", "eloquenti"),
    ("retorico", "retórico", "aggettivi", "Una domanda retorica.", "Uma pergunta retórica.", "/reˈtɔriko/", "m", "retorici"),
    ("narrativo", "narrativo", "aggettivi", "Testo narrativo.", "Texto narrativo.", "/narraˈtivo/", "m", "narrativi")
]

# T43: I Miti e le Leggende (110 parole)
t43_data = [
    # Creature e Divinità
    ("mito", "mito", "mitologia", "Un mito greco.", "Um mito grego.", "/ˈmito/", "m", "miti"),
    ("leggenda", "lenda", "mitologia", "La leggenda di Re Artù.", "A lenda do Rei Arthur.", "/ledˈdʒɛnda/", "f", "leggende"),
    ("dio", "deus", "divinità", "Il dio del tuono.", "O deus do trovão.", "/ˈdio/", "m", "dei"),
    ("dea", "deusa", "divinità", "La dea dell'amore.", "A deusa do amor.", "/ˈdɛa/", "f", "dee"),
    ("semidio", "semideus", "divinità", "Ercole era un semidio.", "Hércules era um semideus.", "/semiˈdio/", "m", "semidei"),
    ("titano", "titã", "divinità", "Il titano Crono.", "O titã Cronos.", "/tiˈtano/", "m", "titani"),
    ("ninfa", "ninfa", "creature", "Le ninfe dei boschi.", "As ninfas dos bosques.", "/ˈninfa/", "f", "ninfe"),
    ("sirena", "sereia", "creature", "Il canto della sirena.", "O canto da sereia.", "/siˈrɛna/", "f", "sirene"),
    ("drago", "dragão", "creature", "Il drago sputa fuoco.", "O dragão cospe fogo.", "/ˈdraɡo/", "m", "draghi"),
    ("mostro", "monstro", "creature", "Un mostro marino.", "Um monstro marinho.", "/ˈmostro/", "m", "mostri"),
    ("gigante", "gigante", "creature", "Il gigante Golia.", "O gigante Golias.", "/dʒiˈɡante/", "m", "giganti"),
    ("ciclope", "ciclope", "creature", "Polifemo era un ciclope.", "Polifemo era um ciclope.", "/tʃiˈklɔpe/", "m", "ciclopi"),
    ("centauro", "centauro", "creature", "Il saggio centauro.", "O sábio centauro.", "/tʃenˈtauro/", "m", "centauri"),
    ("minotauro", "minotauro", "creature", "Il labirinto del minotauro.", "O labirinto do minotauro.", "/minoˈtauro/", "m", "minotauri"),
    ("fenice", "fênix", "creature", "Risorge come l'Araba Fenice.", "Renasce como a Fênix.", "/feˈnitʃe/", "f", "fenici"),
    ("vampiro", "vampiro", "creature", "Un vampiro beve sangue.", "Um vampiro bebe sangue.", "/vamˈpiro/", "m", "vampiri"),
    ("licantropo", "lobisomem", "creature", "La luna piena e il licantropo.", "A lua cheia e o lobisomem.", "/liˈkantropo/", "m", "licantropi"),
    ("fantasma", "fantasma", "creature", "Un castello coi fantasmi.", "Um castelo com fantasmas.", "/fanˈtazma/", "m", "fantasmi"),
    ("mago", "mago", "creature", "Il mago Merlino.", "O mago Merlin.", "/ˈmaɡo/", "m", "maghi"),
    ("strega", "bruxa", "creature", "La strega cattiva.", "A bruxa má.", "/ˈstreɡa/", "f", "streghe"),
    ("fata", "fada", "creature", "La fata madrina.", "A fada madrinha.", "/ˈfata/", "f", "fate"),
    ("orco", "ogro", "creature", "L'orco mangia i bambini.", "O ogro come as crianças.", "/ˈorko/", "m", "orchi"),
    ("elfo", "elfo", "creature", "L'elfo del bosco.", "O elfo da floresta.", "/ˈɛlfo/", "m", "elfi"),
    ("nano", "anão", "creature", "I sette nani.", "Os sete anões.", "/ˈnano/", "m", "nani"),
    # Luoghi e Elementi Magici
    ("olimpo", "olimpo", "luoghi", "Gli dei dell'Olimpo.", "Os deuses do Olimpo.", "/oˈlimpo/", "m", None),
    ("ade", "hades/submundo", "luoghi", "Il regno dell'Ade.", "O reino de Hades.", "/ˈade/", "m", None),
    ("tartaro", "tártaro", "luoghi", "Gettato nel Tartaro.", "Jogado no Tártaro.", "/ˈtartaro/", "m", None),
    ("labirinto", "labirinto", "luoghi", "Il labirinto di Cnosso.", "O labirinto de Cnossos.", "/labiˈrinto/", "m", "labirinti"),
    ("oracolo", "oráculo", "luoghi", "L'oracolo di Delfi.", "O oráculo de Delfos.", "/oˈrakolo/", "m", "oracoli"),
    ("tempio", "templo", "luoghi", "Il tempio di Apollo.", "O templo de Apolo.", "/ˈtɛmpjo/", "m", "tempi"),
    ("altare", "altar", "luoghi", "Un sacrificio sull'altare.", "Um sacrifício no altar.", "/alˈtare/", "m", "altari"),
    ("spada", "espada", "oggetti", "La spada nella roccia.", "A espada na pedra.", "/ˈspada/", "f", "spade"),
    ("scudo", "escudo", "oggetti", "Lo scudo magico.", "O escudo mágico.", "/ˈskudo/", "m", "scudi"),
    ("arco", "arco", "oggetti", "L'arco e le frecce.", "O arco e as flechas.", "/ˈarko/", "m", "archi"),
    ("tridente", "tridente", "oggetti", "Il tridente di Nettuno.", "O tridente de Netuno.", "/triˈdɛnte/", "m", "tridenti"),
    ("pozione", "poção", "oggetti", "Una pozione magica.", "Uma poção mágica.", "/potˈtsjone/", "f", "pozioni"),
    ("incantesimo", "feitiço/encantamento", "oggetti", "Lanciare un incantesimo.", "Lançar um feitiço.", "/inkanˈtezimo/", "m", "incantesimi"),
    ("maledizione", "maldição", "oggetti", "Una terribile maledizione.", "Uma terrível maldição.", "/maleditˈtsjone/", "f", "maledizioni"),
    ("profezia", "profecia", "oggetti", "Una profezia oscura.", "Uma profecia sombria.", "/profeˈtsia/", "f", "profezie"),
    ("sacrificio", "sacrifício", "oggetti", "Un sacrificio umano.", "Um sacrifício humano.", "/sakriˈfitʃo/", "m", "sacrifici"),
    ("offerta", "oferenda", "oggetti", "Un'offerta agli dei.", "Uma oferenda aos deuses.", "/ofˈfɛrta/", "f", "offerte"),
    ("talismano", "talismã", "oggetti", "Un talismano protettivo.", "Um talismã protetor.", "/talizˈmano/", "m", "talismani"),
    ("amuleto", "amuleto", "oggetti", "Un amuleto portafortuna.", "Um amuleto da sorte.", "/amuˈleto/", "m", "amuleti"),
    ("tesoro", "tesouro", "oggetti", "Il tesoro nascosto.", "O tesouro escondido.", "/teˈzɔro/", "m", "tesori"),
    # Concetti Mitologici
    ("destino", "destino", "concetti", "Le Moire tessono il destino.", "As Moiras tecem o destino.", "/desˈtino/", "m", "destini"),
    ("fato", "fado/destino", "concetti", "Non si sfugge al fato.", "Não se foge ao destino.", "/ˈfato/", "m", "fati"),
    ("immortalità", "imortalidade", "concetti", "Il dono dell'immortalità.", "O dom da imortalidade.", "/immortaliˈta/", "f", "immortalità"),
    ("eternità", "eternidade", "concetti", "Durerà per l'eternità.", "Durará por toda a eternidade.", "/eterniˈta/", "f", "eternità"),
    ("gloria", "glória", "concetti", "Cercare la gloria in battaglia.", "Buscar a glória na batalha.", "/ˈɡlɔrja/", "f", "glorie"),
    ("vendetta", "vingança", "concetti", "La vendetta degli dei.", "A vingança dos deuses.", "/venˈdetta/", "f", "vendette"),
    ("castigo", "castigo/punição", "concetti", "Il castigo divino.", "O castigo divino.", "/kasˈtiɡo/", "m", "castighi"),
    ("peccato", "pecado (hybris)", "concetti", "L'orgoglio è un peccato.", "O orgulho é um pecado.", "/pekˈkato/", "m", "peccati"),
    ("eroismo", "heroísmo", "concetti", "Un atto di eroismo.", "Um ato de heroísmo.", "/eroˈizmo/", "m", "eroismi"),
    ("metamorfosi", "metamorfose", "concetti", "La metamorfosi di Ovidio.", "A metamorfose de Ovídio.", "/metaˈmɔrfozi/", "f", "metamorfosi"),
    # Verbi
    ("creare", "criar", "verbi", "Creare l'universo.", "Criar o universo.", "/kreˈare/", None, None),
    ("distruggere", "destruir", "verbi", "Distruggere la città.", "Destruir a cidade.", "/disˈtruddʒere/", None, None),
    ("trasformare", "transformar", "verbi", "Trasformarsi in animale.", "Transformar-se em animal.", "/trasforˈmare/", None, None),
    ("ingannare", "enganar", "verbi", "Ingannare gli dei.", "Enganar os deuses.", "/inɡanˈnare/", None, None),
    ("combattere", "combater/lutar", "verbi", "Combattere il drago.", "Lutar com o dragão.", "/komˈbattere/", None, None),
    ("sconfiggere", "derrotar", "verbi", "Sconfiggere il mostro.", "Derrotar o monstro.", "/skonˈfiddʒere/", None, None),
    ("sacrificare", "sacrificar", "verbi", "Sacrificare un ariete.", "Sacrificar um carneiro.", "/sakrifiˈkare/", None, None),
    ("predire", "predizer", "verbi", "Predire il futuro.", "Predizer o futuro.", "/preˈdire/", None, None),
    ("apparire", "aparecer", "verbi", "Apparve un fantasma.", "Apareceu um fantasma.", "/appaˈrire/", None, None),
    ("scomparire", "desaparecer", "verbi", "Scomparire nel nulla.", "Desaparecer no nada.", "/skompaˈrire/", None, None),
    ("evocare", "evocar", "verbi", "Evocare gli spiriti.", "Evocar os espíritos.", "/evoˈkare/", None, None),
    ("pregare", "rezar", "verbi", "Pregare gli dei.", "Rezar aos deuses.", "/preˈɡare/", None, None),
    ("maledire", "amaldiçoar", "verbi", "Maledire un nemico.", "Amaldiçoar um inimigo.", "/maleˈdire/", None, None),
    ("benedire", "abençoar", "verbi", "Gli dei ti benedicano.", "Os deuses te abençoem.", "/beneˈdire/", None, None),
    ("incantare", "encantar", "verbi", "Incantare con la magia.", "Encantar com a magia.", "/inkanˈtare/", None, None),
    ("risorgere", "ressuscitar/renascer", "verbi", "Risorgere dalle ceneri.", "Renascer das cinzas.", "/riˈzordʒere/", None, None),
    ("punire", "punir", "verbi", "Punire l'arroganza.", "Punir a arrogância.", "/puˈnire/", None, None),
    ("salvare", "salvar", "verbi", "Salvare la principessa.", "Salvar a princesa.", "/salˈvare/", None, None),
    ("sfidare", "desafiar", "verbi", "Sfidare il destino.", "Desafiar o destino.", "/sfiˈdare/", None, None),
    ("venerare", "venerar", "verbi", "Venerare una divinità.", "Venerar uma divindade.", "/veneˈrare/", None, None),
    # Aggettivi e descrittori
    ("mitologico", "mitológico", "aggettivi", "Una figura mitologica.", "Uma figura mitológica.", "/mitoˈlɔdʒiko/", "m", "mitologici"),
    ("leggendario", "lendário", "aggettivi", "Un eroe leggendario.", "Um herói lendário.", "/leddʒenˈdarjo/", "m", "leggendari"),
    ("divino", "divino", "aggettivi", "Il potere divino.", "O poder divino.", "/diˈvino/", "m", "divini"),
    ("sacro", "sagrado", "aggettivi", "Un bosco sacro.", "Um bosque sagrado.", "/ˈsakro/", "m", "sacri"),
    ("magico", "mágico", "aggettivi", "Un anello magico.", "Um anel mágico.", "/ˈmadʒiko/", "m", "magici"),
    ("soprannaturale", "sobrenatural", "aggettivi", "Forze soprannaturali.", "Forças sobrenaturais.", "/soprannatuˈrale/", "m", "soprannaturali"),
    ("immortale", "imortal", "aggettivi", "Gli dei sono immortali.", "Os deuses são imortais.", "/immorˈtale/", "m", "immortali"),
    ("mortale", "mortal", "aggettivi", "Un semplice mortale.", "Um simples mortal.", "/morˈtale/", "m", "mortali"),
    ("eroico", "heroico", "aggettivi", "Un gesto eroico.", "Um gesto heroico.", "/eˈrɔiko/", "m", "eroici"),
    ("mostruoso", "monstruoso", "aggettivi", "Un aspetto mostruoso.", "Um aspecto monstruoso.", "/mosˈtrwozo/", "m", "mostruosi"),
    ("fatato", "fabuloso/encantado", "aggettivi", "Un regno fatato.", "Um reino encantado.", "/faˈtato/", "m", "fatati"),
    ("oscuro", "escuro/sombrio", "aggettivi", "Una selva oscura.", "Uma selva sombria.", "/osˈkuro/", "m", "oscuri"),
    ("luminoso", "luminoso", "aggettivi", "Un dio luminoso.", "Um deus luminoso.", "/lumiˈnozo/", "m", "luminosi"),
    ("invincibile", "invencível", "aggettivi", "Un guerriero invincibile.", "Um guerreiro invencível.", "/invinˈtʃibile/", "m", "invincibili"),
    ("vulnerabile", "vulnerável", "aggettivi", "Il tallone vulnerabile.", "O calcanhar vulnerável.", "/vulneˈrabile/", "m", "vulnerabili"),
    ("misterioso", "misterioso", "aggettivi", "Un oracolo misterioso.", "Um oráculo misterioso.", "/misteˈrjozo/", "m", "misteriosi"),
    ("terribile", "terrível", "aggettivi", "Una maledizione terribile.", "Uma maldição terrível.", "/terˈribile/", "m", "terribili"),
    ("potente", "poderoso", "aggettivi", "Un mago molto potente.", "Um mago muito poderoso.", "/poˈtɛnte/", "m", "potenti"),
    ("onnipotente", "onipotente", "aggettivi", "Un dio onnipotente.", "Um deus onipotente.", "/onnipoˈtɛnte/", "m", "onnipotenti"),
    ("crudele", "cruel", "aggettivi", "Un re crudele.", "Um rei cruel.", "/kruˈdɛle/", "m", "crudeli")
]

# T44: Il Diritto e la Legge (110 parole)
t44_data = [
    # Concetti generali e Istituzioni
    ("diritto", "direito", "giurisprudenza", "Studiare diritto.", "Estudar direito.", "/diˈritto/", "m", "diritti"),
    ("legge", "lei", "giurisprudenza", "La legge è uguale per tutti.", "A lei é igual para todos.", "/ˈleddʒe/", "f", "leggi"),
    ("giustizia", "justiça", "giurisprudenza", "Chiedere giustizia.", "Pedir justiça.", "/dʒusˈtittsja/", "f", "giustizie"),
    ("tribunale", "tribunal", "istituzioni", "Andare in tribunale.", "Ir ao tribunal.", "/tribuˈnale/", "m", "tribunali"),
    ("corte", "corte/tribunal", "istituzioni", "La Corte Suprema.", "A Suprema Corte.", "/ˈkorte/", "f", "corti"),
    ("processo", "processo/julgamento", "giurisprudenza", "Iniziare il processo.", "Iniciar o processo.", "/proˈtʃɛsso/", "m", "processi"),
    ("causa", "processo judicial/causa", "giurisprudenza", "Vincere una causa.", "Vencer uma causa.", "/ˈkauza/", "f", "cause"),
    ("sentenza", "sentença", "giurisprudenza", "Emettere la sentenza.", "Emitir a sentença.", "/senˈtɛntsa/", "f", "sentenze"),
    ("verdetto", "veredicto", "giurisprudenza", "Il verdetto della giuria.", "O veredicto do júri.", "/verˈdetto/", "m", "verdetti"),
    ("appello", "apelação/recurso", "giurisprudenza", "Fare appello.", "Fazer apelação.", "/apˈpɛllo/", "m", "appelli"),
    ("codice", "código", "giurisprudenza", "Codice penale.", "Código penal.", "/ˈkɔditʃe/", "m", "codici"),
    ("costituzione", "constituição", "giurisprudenza", "La costituzione italiana.", "A constituição italiana.", "/kostitutˈtsjone/", "f", "costituzioni"),
    ("reato", "crime", "crimini", "Commettere un reato.", "Cometer um crime.", "/reˈato/", "m", "reati"),
    ("crimine", "crime", "crimini", "Un crimine violento.", "Um crime violento.", "/ˈkrimine/", "m", "crimini"),
    ("delitto", "delito/crime", "crimini", "La scena del delitto.", "A cena do crime.", "/deˈlitto/", "m", "delitti"),
    ("furto", "furto/roubo", "crimini", "Denunciare un furto.", "Denunciar um furto.", "/ˈfurto/", "m", "furti"),
    ("rapina", "roubo/assalto", "crimini", "Rapina in banca.", "Assalto a banco.", "/raˈpina/", "f", "rapine"),
    ("omicidio", "homicídio", "crimini", "Accusato di omicidio.", "Acusado de homicídio.", "/omiˈtʃidjo/", "m", "omicidi"),
    ("frode", "fraude", "crimini", "Frode fiscale.", "Fraude fiscal.", "/ˈfrɔde/", "f", "frodi"),
    ("truffa", "golpe/fraude", "crimini", "Subire una truffa.", "Sofrer um golpe.", "/ˈtruffa/", "f", "truffe"),
    ("corruzione", "corrupção", "crimini", "Lotta alla corruzione.", "Luta contra a corrupção.", "/korrutˈtsjone/", "f", "corruzioni"),
    ("pena", "pena/castigo", "giurisprudenza", "La pena di morte.", "A pena de morte.", "/ˈpena/", "f", "pene"),
    ("prigione", "prisão", "istituzioni", "Andare in prigione.", "Ir para a prisão.", "/priˈdʒone/", "f", "prigioni"),
    ("carcere", "cárcere", "istituzioni", "Il carcere duro.", "O cárcere duro.", "/ˈkartʃere/", "m", "carceri"),
    ("cella", "cela", "istituzioni", "Chiuso in cella.", "Trancado na cela.", "/ˈtʃɛlla/", "f", "celle"),
    ("multa", "multa", "giurisprudenza", "Prendere una multa.", "Levar uma multa.", "/ˈmulta/", "f", "multe"),
    ("cauzione", "fiança", "giurisprudenza", "Pagare la cauzione.", "Pagar a fiança.", "/kauˈtsjone/", "f", "cauzioni"),
    ("prova", "prova/evidência", "giurisprudenza", "Non ci sono prove.", "Não há provas.", "/ˈprɔva/", "f", "prove"),
    ("indizio", "indício", "giurisprudenza", "Un grave indizio.", "Um grave indício.", "/inˈdittsjo/", "m", "indizi"),
    ("alibi", "álibi", "giurisprudenza", "Avere un alibi di ferro.", "Ter um álibi de ferro.", "/ˈalibi/", "m", "alibi"),
    ("testimone", "testemunha", "persone", "Il testimone chiave.", "A testemunha chave.", "/testiˈmɔne/", "m/f", "testimoni"),
    ("testimonianza", "testemunho", "giurisprudenza", "Una falsa testimonianza.", "Um falso testemunho.", "/testimoˈnjantsa/", "f", "testimonianze"),
    ("giuria", "júri", "istituzioni", "I membri della giuria.", "Os membros do júri.", "/dʒuˈria/", "f", "giurie"),
    ("querela", "queixa-crime", "giurisprudenza", "Ritirare la querela.", "Retirar a queixa.", "/kweˈrɛla/", "f", "querele"),
    ("denuncia", "denúncia", "giurisprudenza", "Fare una denuncia.", "Fazer uma denúncia.", "/deˈnuntʃa/", "f", "denunce"),
    ("contratto", "contrato", "giurisprudenza", "Firmare il contratto.", "Assinar o contrato.", "/konˈtratto/", "m", "contratti"),
    ("accordo", "acordo", "giurisprudenza", "Raggiungere un accordo.", "Chegar a um acordo.", "/akˈkɔrdo/", "m", "accordi"),
    ("testamento", "testamento", "giurisprudenza", "Leggere il testamento.", "Ler o testamento.", "/testaˈmento/", "m", "testamenti"),
    ("divorzio", "divórcio", "giurisprudenza", "Chiedere il divorzio.", "Pedir o divórcio.", "/diˈvɔrtsjo/", "m", "divorzi"),
    ("eredità", "herança", "giurisprudenza", "Lasciare in eredità.", "Deixar como herança.", "/erediˈta/", "f", "eredità"),
    ("patrimonio", "patrimônio", "giurisprudenza", "Dichiarazione dei redditi e patrimonio.", "Declaração de renda e patrimônio.", "/patriˈmɔnjo/", "m", "patrimoni"),
    # Persone del diritto
    ("giudice", "juiz", "persone", "Il giudice decide.", "O juiz decide.", "/ˈdʒuditʃe/", "m", "giudici"),
    ("magistrato", "magistrado", "persone", "Il magistrato indaga.", "O magistrado investiga.", "/madʒisˈtrato/", "m", "magistrati"),
    ("avvocato", "advogado", "persone", "L'avvocato difensore.", "O advogado de defesa.", "/avvoˈkato/", "m", "avvocati"),
    ("pubblico ministero", "promotor público", "persone", "Il pubblico ministero accusa.", "O promotor acusa.", "/ˈpubbliko minisˈtɛro/", "m", "pubblici ministeri"),
    ("imputato", "réu/acusado", "persone", "L'imputato è innocente.", "O réu é inocente.", "/impuˈtato/", "m", "imputati"),
    ("colpevole", "culpado", "persone", "Il vero colpevole.", "O verdadeiro culpado.", "/kolˈpevole/", "m/f", "colpevoli"),
    ("vittima", "vítima", "persone", "La vittima del furto.", "A vítima do roubo.", "/ˈvittima/", "f", "vittime"),
    ("poliziotto", "policial", "persone", "Chiamare un poliziotto.", "Chamar um policial.", "/politˈtsjɔtto/", "m", "poliziotti"),
    ("carabiniere", "policial (carabiniere)", "persone", "Arrestato dai carabinieri.", "Preso pelos carabinieri.", "/karabiˈnjɛre/", "m", "carabinieri"),
    ("detenuto", "detento/preso", "persone", "I diritti dei detenuti.", "Os direitos dos presos.", "/deteˈnuto/", "m", "detenuti"),
    ("notaio", "tabelião/notário", "persone", "Andare dal notaio.", "Ir ao tabelião.", "/noˈtajo/", "m", "notai"),
    ("esperto", "perito/especialista", "persone", "Il parere dell'esperto.", "A opinião do perito.", "/esˈpɛrto/", "m", "esperti"),
    # Verbi legali
    ("giudicare", "julgar", "verbi", "Giudicare in tribunale.", "Julgar no tribunal.", "/dʒudiˈkare/", None, None),
    ("accusare", "acusar", "verbi", "Accusare di furto.", "Acusar de roubo.", "/akkuˈzare/", None, None),
    ("difendere", "defender", "verbi", "Difendere l'imputato.", "Defender o réu.", "/diˈfɛndere/", None, None),
    ("condannare", "condenar", "verbi", "Condannare al carcere.", "Condenar à prisão.", "/kondanˈnare/", None, None),
    ("assolvere", "absolver", "verbi", "Assolvere per mancanza di prove.", "Absolver por falta de provas.", "/asˈsɔlvere/", None, None),
    ("arrestare", "prender/prender", "verbi", "Arrestare il ladro.", "Prender o ladrão.", "/arresˈtare/", None, None),
    ("indagare", "investigar", "verbi", "La polizia indaga.", "A polícia investiga.", "/indaˈɡare/", None, None),
    ("interrogare", "interrogar", "verbi", "Interrogare il sospetto.", "Interrogar o suspeito.", "/interroˈɡare/", None, None),
    ("testimoniare", "testemunhar", "verbi", "Testimoniare il falso.", "Testemunhar o falso.", "/testimoˈnjare/", None, None),
    ("denunciare", "denunciar", "verbi", "Denunciare il fatto.", "Denunciar o fato.", "/denunˈtʃare/", None, None),
    ("confessare", "confessar", "verbi", "Confessare il crimine.", "Confessar o crime.", "/konfesˈsare/", None, None),
    ("appellarsi", "apelar", "verbi", "Appellarsi alla corte.", "Apelar à corte.", "/appelˈlarsi/", None, None),
    ("firmare", "assinar", "verbi", "Firmare il contratto.", "Assinar o contrato.", "/firˈmare/", None, None),
    ("legalizzare", "legalizar", "verbi", "Legalizzare il documento.", "Legalizar o documento.", "/leɡalidˈdzare/", None, None),
    ("abrogare", "abrogar/revogar", "verbi", "Abrogare una legge.", "Revogar uma lei.", "/abroˈɡare/", None, None),
    ("violare", "violar", "verbi", "Violare le regole.", "Violar as regras.", "/vjoˈlare/", None, None),
    ("punire", "punir", "verbi", "Punire severamente.", "Punir severamente.", "/puˈnire/", None, None),
    ("risarcire", "indenizar", "verbi", "Risarcire i danni.", "Indenizar os danos.", "/rizarˈtʃire/", None, None),
    ("vietare", "proibir", "verbi", "È vietato fumare.", "É proibido fumar.", "/vjeˈtare/", None, None),
    ("consentire", "permitir", "verbi", "Non è consentito.", "Não é permitido.", "/konsenˈtire/", None, None),
    # Aggettivi e descrittori
    ("legale", "legal", "aggettivi", "Un'azione legale.", "Uma ação legal.", "/leˈɡale/", "m", "legali"),
    ("illegale", "ilegal", "aggettivi", "Traffico illegale.", "Tráfico ilegal.", "/illeˈɡale/", "m", "illegali"),
    ("giusto", "justo", "aggettivi", "Un processo giusto.", "Um processo justo.", "/ˈdʒusto/", "m", "giusti"),
    ("ingiusto", "injusto", "aggettivi", "Una condanna ingiusta.", "Uma condenação injusta.", "/inˈdʒusto/", "m", "ingiusti"),
    ("innocente", "inocente", "aggettivi", "Dichiararsi innocente.", "Declarar-se inocente.", "/innoˈtʃɛnte/", "m", "innocenti"),
    ("colpevole", "culpado (adj)", "aggettivi", "Essere colpevole.", "Ser culpado.", "/kolˈpevole/", "m", "colpevoli"),
    ("civile", "civil", "aggettivi", "Diritto civile.", "Direito civil.", "/tʃiˈvile/", "m", "civili"),
    ("penale", "penal", "aggettivi", "Diritto penale.", "Direito penal.", "/peˈnale/", "m", "penali"),
    ("costituzionale", "constitucional", "aggettivi", "Diritto costituzionale.", "Direito constitucional.", "/kostitutsjoˈnale/", "m", "costituzionali"),
    ("amministrativo", "administrativo", "aggettivi", "Diritto amministrativo.", "Direito administrativo.", "/amministraˈtivo/", "m", "amministrativi"),
    ("criminale", "criminoso", "aggettivi", "Banda criminale.", "Quadrilha criminosa.", "/krimiˈnale/", "m", "criminali"),
    ("sospetto", "suspeito", "aggettivi", "Un pacco sospetto.", "Um pacote suspeito.", "/sosˈpɛtto/", "m", "sospetti"),
    ("imparziale", "imparcial", "aggettivi", "Un giudice imparziale.", "Um juiz imparcial.", "/imparˈtsjale/", "m", "imparziali"),
    ("valido", "válido", "aggettivi", "Un contratto valido.", "Um contrato válido.", "/ˈvalido/", "m", "validi"),
    ("nullo", "nulo", "aggettivi", "Contratto nullo.", "Contrato nulo.", "/ˈnullo/", "m", "nulli"),
    ("obbligatorio", "obrigatório", "aggettivi", "È obbligatorio per legge.", "É obrigatório por lei.", "/obbliɡaˈtɔrjo/", "m", "obbligatori"),
    ("facoltativo", "facultativo/opcional", "aggettivi", "Un modulo facoltativo.", "Um formulário opcional.", "/fakoltaˈtivo/", "m", "facoltativi"),
    ("illecito", "ilícito", "aggettivi", "Arricchimento illecito.", "Enriquecimento ilícito.", "/ilˈletʃito/", "m", "illeciti"),
    ("legittimo", "legítimo", "aggettivi", "Un erede legittimo.", "Um herdeiro legítimo.", "/leˈdʒittimo/", "m", "legittimi"),
    ("illegittimo", "ilegítimo", "aggettivi", "Un figlio illegittimo.", "Um filho ilegítimo.", "/illedˈdʒittimo/", "m", "illegittimi"),
    ("severo", "severo", "aggettivi", "Una pena severa.", "Uma pena severa.", "/seˈvɛro/", "m", "severi"),
    ("mite", "brando/leve", "aggettivi", "Una condanna mite.", "Uma condenação leve.", "/ˈmite/", "m", "miti"),
    ("urgente", "urgente", "aggettivi", "Una causa urgente.", "Uma causa urgente.", "/urˈdʒɛnte/", "m", "urgenti"),
    ("clandestino", "clandestino", "aggettivi", "Lavoratore clandestino.", "Trabalhador clandestino.", "/klandesˈtino/", "m", "clandestini"),
    ("anonimo", "anônimo", "aggettivi", "Denuncia anonima.", "Denúncia anônima.", "/aˈnɔnimo/", "m", "anonimi"),
    ("falso", "falso", "aggettivi", "Documento falso.", "Documento falso.", "/ˈfalso/", "m", "falsi"),
    ("autentico", "autêntico/verdadeiro", "aggettivi", "Firma autentica.", "Assinatura autêntica.", "/auˈtɛntiko/", "m", "autentici"),
    ("pubblico", "público", "aggettivi", "Atto pubblico.", "Ato público.", "/ˈpubbliko/", "m", "pubblici")
]

def create_new(templo_num, nome, citta, livello, parole_data):
    palavras = []
    for i, (it, pt, cat, ex_it, ex_pt, ipa, gen, pl) in enumerate(parole_data, 1):
        tid = f"t{templo_num}_{i:03d}"
        palavras.append(w(tid, it, pt, cat, ex_it, ex_pt, ipa, gen, pl))
        
    obj = {
        "templo": templo_num,
        "nome": nome,
        "cidade": citta,
        "nivel": livello,
        "palavras": palavras
    }
    
    path = os.path.join(OUT, "data", f"templo-{templo_num}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"CREATED templo-{templo_num}.json -- {len(palavras)} parole")

if __name__ == "__main__":
    create_new(42, "La Letteratura Classica", "Firenze", "C1", t42_data)
    create_new(43, "I Miti e le Leggende", "Siracusa", "B2", t43_data)
    create_new(44, "Il Diritto e la Legge", "Roma", "C1", t44_data)
