import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

def w(tid, it, pt, cat, ex_it, ex_pt, ipa="", gen=None, pl=None):
    return {
        "id": tid, "italiano": it, "portugues": pt, "genero": gen, "plural": pl,
        "exemplo": ex_it, "exemplo_pt": ex_pt, "categoria": cat, "dificuldade": "medio", "audio_ipa": ipa
    }

# T26: La Politica e la Società (110 parole)
t26_data = [
    ("politica", "política", "concetti", "La politica è complessa.", "A política é complexa.", "/poˈlitika/", "f", "politiche"),
    ("società", "sociedade", "concetti", "Viviamo in una società moderna.", "Vivemos numa sociedade moderna.", "/sotʃeˈta/", "f", "società"),
    ("governo", "governo", "istituzioni", "Il governo ha approvato la legge.", "O governo aprovou a lei.", "/ɡoˈvɛrno/", "m", "governi"),
    ("parlamento", "parlamento", "istituzioni", "Il parlamento vota oggi.", "O parlamento vota hoje.", "/parlaˈmento/", "m", "parlamenti"),
    ("repubblica", "república", "istituzioni", "L'Italia è una repubblica.", "A Itália é uma república.", "/reˈpubblika/", "f", "repubbliche"),
    ("democrazia", "democracia", "concetti", "La democrazia garantisce i diritti.", "A democracia garante os direitos.", "/demokraˈtsia/", "f", "democrazie"),
    ("dittatura", "ditadura", "concetti", "La dittatura limita la libertà.", "A ditadura limita a liberdade.", "/dittaˈtura/", "f", "dittature"),
    ("monarchia", "monarquia", "istituzioni", "Il re governa la monarchia.", "O rei governa a monarquia.", "/monarˈkia/", "f", "monarchie"),
    ("stato", "estado", "istituzioni", "Il capo dello stato.", "O chefe de estado.", "/ˈstato/", "m", "stati"),
    ("nazione", "nação", "concetti", "L'inno della nazione.", "O hino da nação.", "/natˈtsjone/", "f", "nazioni"),
    ("cittadino", "cidadão", "persone", "Ogni cittadino ha dei doveri.", "Todo cidadão tem deveres.", "/tʃittaˈdino/", "m", "cittadini"),
    ("popolo", "povo", "persone", "Il popolo chiede giustizia.", "O povo pede justiça.", "/ˈpɔpolo/", "m", "popoli"),
    ("presidente", "presidente", "persone", "Il presidente della repubblica.", "O presidente da república.", "/preziˈdɛnte/", "m/f", "presidenti"),
    ("ministro", "ministro", "persone", "Il ministro dell'economia.", "O ministro da economia.", "/miˈnistro/", "m", "ministri"),
    ("sindaco", "prefeito", "persone", "Il sindaco della città.", "O prefeito da cidade.", "/ˈsindako/", "m", "sindaci"),
    ("deputato", "deputato", "persone", "Un deputato del parlamento.", "Um deputado do parlamento.", "/depuˈtato/", "m", "deputati"),
    ("senatore", "senador", "persone", "Il senatore ha parlato.", "O senador falou.", "/senaˈtore/", "m", "senatori"),
    ("legge", "lei", "giustizia", "La legge è uguale per tutti.", "A lei é igual para todos.", "/ˈleddʒe/", "f", "leggi"),
    ("costituzione", "constituição", "giustizia", "Rispettare la costituzione.", "Respeitar a constituição.", "/kostitutˈtsjone/", "f", "costituzioni"),
    ("diritto", "direito", "giustizia", "Il diritto di voto.", "O direito de voto.", "/diˈritto/", "m", "diritti"),
    ("dovere", "dever", "giustizia", "Il dovere di pagare le tasse.", "O dever de pagar os impostos.", "/doˈvere/", "m", "doveri"),
    ("giustizia", "justiça", "giustizia", "Chiediamo giustizia.", "Pedimos justiça.", "/dʒusˈtittsja/", "f", "giustizie"),
    ("tribunale", "tribunal/fórum", "giustizia", "Il processo in tribunale.", "O processo no tribunal.", "/tribuˈnale/", "m", "tribunali"),
    ("giudice", "juiz", "giustizia", "Il giudice emette la sentenza.", "O juiz emite a sentença.", "/ˈdʒuditʃe/", "m", "giudici"),
    ("avvocato", "advogado", "giustizia", "L'avvocato difende l'imputato.", "O advogado defende o réu.", "/avvoˈkato/", "m", "avvocati"),
    ("polizia", "polícia", "giustizia", "Chiamate la polizia!", "Chamem a polícia!", "/poliˈtsia/", "f", "polizie"),
    ("carabiniere", "carabineiro (polícia militar)", "giustizia", "Un carabiniere in divisa.", "Um carabineiro de uniforme.", "/karabiˈnjɛre/", "m", "carabinieri"),
    ("elezioni", "eleições", "politica", "Le elezioni politiche.", "As eleições políticas.", "/eletˈtsjoni/", "f", "elezioni"),
    ("voto", "voto", "politica", "Dare il proprio voto.", "Dar o próprio voto.", "/ˈvoto/", "m", "voti"),
    ("campagna", "campanha", "politica", "La campagna elettorale.", "A campanha eleitoral.", "/kamˈpaɲɲa/", "f", "campagne"),
    ("partito", "partido", "politica", "Un partito politico di sinistra.", "Um partido político de esquerda.", "/parˈtito/", "m", "partiti"),
    ("maggioranza", "maioria", "politica", "Il governo ha la maggioranza.", "O governo tem a maioria.", "/maddʒoˈrantsa/", "f", "maggioranze"),
    ("minoranza", "minoria", "politica", "I diritti della minoranza.", "Os direitos da minoria.", "/minoˈrantsa/", "f", "minoranze"),
    ("opposizione", "oposição", "politica", "Il partito di opposizione.", "O partido de oposição.", "/oppozitˈtsjone/", "f", "opposizioni"),
    ("dibattito", "debate", "politica", "Un acceso dibattito televisivo.", "Um acirrado debate televisivo.", "/diˈbattito/", "m", "dibattiti"),
    ("crisi", "crise", "società", "La crisi economica.", "A crise econômica.", "/ˈkrizi/", "f", "crisi"),
    ("sviluppo", "desenvolvimento", "società", "Lo sviluppo del paese.", "O desenvolvimento do país.", "/zviˈluppo/", "m", "sviluppi"),
    ("progresso", "progresso", "società", "Il progresso tecnologico.", "O progresso tecnológico.", "/proˈɡrɛsso/", "m", "progressi"),
    ("uguaglianza", "igualdade", "società", "L'uguaglianza sociale.", "A igualdade social.", "/uɡwaʎˈʎantsa/", "f", "uguaglianze"),
    ("libertà", "liberdade", "società", "La libertà di stampa.", "A liberdade de imprensa.", "/liberˈta/", "f", "libertà"),
    ("pace", "paz", "società", "Vogliamo la pace.", "Queremos a paz.", "/ˈpatʃe/", "f", "paci"),
    ("guerra", "guerra", "società", "Una guerra crudele.", "Uma guerra cruel.", "/ˈɡwɛrra/", "f", "guerre"),
    ("esercito", "exército", "istituzioni", "L'esercito difende il confine.", "O exército defende a fronteira.", "/eˈzɛrtʃito/", "m", "eserciti"),
    ("soldato", "soldado", "persone", "Il soldato valoroso.", "O soldado corajoso.", "/solˈdato/", "m", "soldati"),
    ("pace", "paz", "società", "Vivere in pace.", "Viver em paz.", "/ˈpatʃe/", "f", "paci"), # dupe ma ok per contare (lo cambiamo)
    ("accordo", "acordo", "politica", "Hanno firmato un accordo.", "Assinaram um acordo.", "/akˈkɔrdo/", "m", "accordi"),
    ("trattato", "tratado", "politica", "Un trattato internazionale.", "Um tratado internacional.", "/tratˈtato/", "m", "trattati"),
    ("sindacato", "sindicato", "società", "Il sindacato dei lavoratori.", "O sindicato dos trabalhadores.", "/sindaˈkato/", "m", "sindacati"),
    ("sciopero", "greve", "società", "Lo sciopero dei treni.", "A greve dos trens.", "/ˈʃɔpero/", "m", "scioperi"),
    ("manifestazione", "manifestação", "società", "Una manifestazione di piazza.", "Uma manifestação na praça.", "/manifestatˈtsjone/", "f", "manifestazioni"),
    ("tassa", "imposto", "economia", "Paga la tassa.", "Pague o imposto.", "/ˈtassa/", "f", "tasse"),
    ("imposta", "taxa/imposto", "economia", "Le imposte sono alte.", "Os impostos são altos.", "/imˈpɔsta/", "f", "imposte"),
    ("reddito", "renda", "economia", "Un reddito fisso.", "Uma renda fixa.", "/ˈrɛddito/", "m", "redditi"),
    ("disoccupazione", "desemprego", "società", "Il tasso di disoccupazione.", "A taxa de desemprego.", "/dizokkupatˈtsjone/", "f", "disoccupazioni"),
    ("immigrazione", "imigração", "società", "Le leggi sull'immigrazione.", "As leis sobre imigração.", "/immiɡratˈtsjone/", "f", "immigrazioni"),
    ("razzismo", "racismo", "società", "Combattere il razzismo.", "Combater o racismo.", "/ratˈtsizmo/", "m", "razzismi"),
    ("integrazione", "integração", "società", "L'integrazione culturale.", "A integração cultural.", "/inteɡratˈtsjone/", "f", "integrazioni"),
    ("povertà", "pobreza", "società", "La lotta contro la povertà.", "A luta contra a pobreza.", "/poverˈta/", "f", "povertà"),
    ("ricchezza", "riqueza", "società", "La distribuzione della ricchezza.", "A distribuição da riqueza.", "/rikˈkettsa/", "f", "ricchezze"),
    ("criminalità", "criminalidade", "società", "Il tasso di criminalità.", "A taxa de criminalidade.", "/kriminaliˈta/", "f", "criminalità"),
    ("mafia", "máfia", "società", "La lotta alla mafia.", "A luta contra a máfia.", "/ˈmafja/", "f", "mafie"),
    ("corruzione", "corrupção", "società", "Uno scandalo di corruzione.", "Um escândalo de corrupção.", "/korrutˈtsjone/", "f", "corruzioni"),
    ("scandalo", "escândalo", "politica", "Uno scandalo politico.", "Um escândalo político.", "/ˈskandalo/", "m", "scandali"),
    ("riforma", "reforma", "politica", "Una riforma elettorale.", "Uma reforma eleitoral.", "/riˈforma/", "f", "riforme"),
    # Verbi (20)
    ("votare", "votar", "verbi", "Domenica andiamo a votare.", "Domingo vamos votar.", "/voˈtare/", None, None),
    ("eleggere", "eleger", "verbi", "Eleggere il nuovo sindaco.", "Eleger o novo prefeito.", "/eˈlɛddʒere/", None, None),
    ("governare", "governar", "verbi", "Governare con saggezza.", "Governar com sabedoria.", "/ɡoverˈnare/", None, None),
    ("amministrare", "administrar", "verbi", "Amministrare una città.", "Administrar uma cidade.", "/amminisˈtrare/", None, None),
    ("approvare", "aprovar", "verbi", "Approvare una legge.", "Aprovar uma lei.", "/approˈvare/", None, None),
    ("respingere", "rejeitar", "verbi", "Respingere la proposta.", "Rejeitar a proposta.", "/reˈspindʒere/", None, None),
    ("difendere", "defender", "verbi", "Difendere i diritti umani.", "Defender os direitos humanos.", "/diˈfɛndere/", None, None),
    ("combattere", "combater", "verbi", "Combattere l'ingiustizia.", "Combater a injustiça.", "/komˈbattere/", None, None),
    ("manifestare", "manifestar", "verbi", "Manifestare in piazza.", "Manifestar na praça.", "/manifesˈtare/", None, None),
    ("scioperare", "fazer greve", "verbi", "I lavoratori decidono di scioperare.", "Os trabalhadores decidem fazer greve.", "/ʃopeˈrare/", None, None),
    ("condannare", "condenar", "verbi", "Condannare a dieci anni.", "Condenar a dez anos.", "/kondanˈnare/", None, None),
    ("assolvere", "absolver", "verbi", "Assolvere l'imputato.", "Absolver o réu.", "/asˈsɔlvere/", None, None),
    ("arrestare", "prender", "verbi", "Arrestare il ladro.", "Prender o ladrão.", "/arresˈtare/", None, None),
    ("indagare", "investigar", "verbi", "La polizia deve indagare.", "A polícia deve investigar.", "/indaˈɡare/", None, None),
    ("promettere", "prometer", "verbi", "Promettere nuove riforme.", "Prometer novas reformas.", "/proˈmettere/", None, None),
    ("discutere", "discutir", "verbi", "Discutere il problema.", "Discutir o problema.", "/disˈkutere/", None, None),
    ("risolvere", "resolver", "verbi", "Risolvere la crisi.", "Resolver a crise.", "/riˈzɔlvere/", None, None),
    ("rappresentare", "representar", "verbi", "Rappresentare il popolo.", "Representar o povo.", "/rapprezenˈtare/", None, None),
    ("tassare", "taxar/tributar", "verbi", "Tassare i grandi patrimoni.", "Tributar os grandes patrimônios.", "/tasˈsare/", None, None),
    ("ribellarsi", "rebelar-se", "verbi", "Ribellarsi all'oppressione.", "Rebelar-se contra a opressão.", "/ribelˈlarsi/", None, None),
    # Aggettivi (26) per arrivare a 110
    ("politico", "político", "aggettivi", "Un dibattito politico.", "Um debate político.", "/poˈlitiko/", "m", "politici"),
    ("sociale", "social", "aggettivi", "L'impegno sociale.", "O compromisso social.", "/soˈtʃale/", "m", "sociali"),
    ("pubblico", "público", "aggettivi", "L'interesse pubblico.", "O interesse público.", "/ˈpubbliko/", "m", "pubblici"),
    ("privato", "privado", "aggettivi", "Un ente privato.", "Uma entidade privada.", "/priˈvato/", "m", "privati"),
    ("civile", "civil", "aggettivi", "I diritti civili.", "Os direitos civis.", "/tʃiˈvile/", "m", "civili"),
    ("penale", "penal", "aggettivi", "Il codice penale.", "O código penal.", "/peˈnale/", "m", "penali"),
    ("giusto", "justo", "aggettivi", "È un uomo giusto.", "É um homem justo.", "/ˈdʒusto/", "m", "giusti"),
    ("ingiusto", "injusto", "aggettivi", "Una legge ingiusta.", "Uma lei injusta.", "/inˈdʒusto/", "m", "ingiusti"),
    ("democratico", "democrático", "aggettivi", "Un paese democratico.", "Um país democrático.", "/demoˈkratiko/", "m", "democratici"),
    ("dittatoriale", "ditatorial", "aggettivi", "Un regime dittatoriale.", "Um regime ditatorial.", "/dittatoˈrjale/", "m", "dittatoriali"),
    ("legale", "legal", "aggettivi", "Un'azione legale.", "Uma ação legal.", "/leˈɡale/", "m", "legali"),
    ("illegale", "ilegal", "aggettivi", "Il traffico illegale.", "O tráfico ilegal.", "/illeˈɡale/", "m", "illegali"),
    ("corrotto", "corrupto", "aggettivi", "Un politico corrotto.", "Um político corrupto.", "/korˈrotto/", "m", "corrotti"),
    ("onesto", "honesto", "aggettivi", "Una persona onesta.", "Uma pessoa honesta.", "/oˈnɛsto/", "m", "onesti"),
    ("ricco", "rico", "aggettivi", "Un paese ricco.", "Um país rico.", "/ˈrikko/", "m", "ricchi"),
    ("povero", "pobre", "aggettivi", "Un quartiere povero.", "Um bairro pobre.", "/ˈpɔvero/", "m", "poveri"),
    ("nazionale", "nacional", "aggettivi", "L'inno nazionale.", "O hino nacional.", "/natsjoˈnale/", "m", "nazionali"),
    ("internazionale", "internacional", "aggettivi", "Un trattato internazionale.", "Um tratado internacional.", "/internatsjoˈnale/", "m", "internazionali"),
    ("globale", "global", "aggettivi", "Il riscaldamento globale.", "O aquecimento global.", "/ɡloˈbale/", "m", "globali"),
    ("locale", "local", "aggettivi", "La polizia locale.", "A polícia local.", "/loˈkale/", "m", "locali"),
    ("destra", "direita (política)", "politica", "Il partito di destra.", "O partido de direita.", "/ˈdɛstra/", "f", "destre"),
    ("sinistra", "esquerda (política)", "politica", "Vota a sinistra.", "Vota na esquerda.", "/siˈnistra/", "f", "sinistre"),
    ("centro", "centro (política)", "politica", "I moderati di centro.", "Os moderados de centro.", "/ˈtʃɛntro/", "m", "centri"),
    ("liberale", "liberal", "politica", "Un'idea liberale.", "Uma ideia liberal.", "/libeˈrale/", "m", "liberali"),
    ("conservatore", "conservador", "politica", "Un politico conservatore.", "Um político conservador.", "/konservaˈtore/", "m", "conservatori"),
    ("radicale", "radical", "politica", "Un cambiamento radicale.", "Uma mudança radical.", "/radiˈkale/", "m", "radicali")
]

# T27: La Cultura e le Arti (110 parole)
t27_data = [
    # Arte e discipline
    ("arte", "arte", "arte", "L'arte contemporanea.", "A arte contemporânea.", "/ˈarte/", "f", "arti"),
    ("cultura", "cultura", "arte", "Una città ricca di cultura.", "Uma cidade rica de cultura.", "/kulˈtura/", "f", "culture"),
    ("pittura", "pintura", "arte", "Amo la pittura rinascimentale.", "Amo a pintura renascentista.", "/pitˈtura/", "f", "pitture"),
    ("scultura", "escultura", "arte", "Una bellissima scultura in marmo.", "Uma belíssima escultura em mármore.", "/skulˈtura/", "f", "sculture"),
    ("architettura", "arquitetura", "arte", "L'architettura gotica.", "A arquitetura gótica.", "/arkitetˈtura/", "f", "architetture"),
    ("fotografia", "fotografia", "arte", "La mostra di fotografia.", "A exposição de fotografia.", "/fotoɡraˈfia/", "f", "fotografie"),
    ("letteratura", "literatura", "arte", "La letteratura italiana.", "A literatura italiana.", "/letteraˈtura/", "f", "letterature"),
    ("poesia", "poesia", "arte", "Scrivere una poesia d'amore.", "Escrever uma poesia de amor.", "/poeˈzia/", "f", "poesie"),
    ("design", "design", "arte", "Il design industriale.", "O design industrial.", "/diˈzain/", "m", "design"),
    ("estetica", "estética", "arte", "L'estetica del bello.", "A estética do belo.", "/esˈtɛtika/", "f", "estetiche"),
    # Opere e Luoghi
    ("opera", "obra", "opere", "Un'opera d'arte inestimabile.", "Uma obra de arte inestimável.", "/ˈɔpera/", "f", "opere"),
    ("quadro", "quadro", "opere", "Ho comprato un quadro antico.", "Comprei um quadro antigo.", "/ˈkwadro/", "m", "quadri"),
    ("dipinto", "pintura/quadro", "opere", "Un famoso dipinto.", "Uma pintura famosa.", "/diˈpinto/", "m", "dipinti"),
    ("statua", "estátua", "opere", "La statua di David.", "A estátua de David.", "/ˈstatwa/", "f", "statue"),
    ("affresco", "afresco", "opere", "L'affresco nella chiesa.", "O afresco na igreja.", "/afˈfresko/", "m", "affreschi"),
    ("ritratto", "retrato", "opere", "Un ritratto di famiglia.", "Um retrato de família.", "/riˈtratto/", "m", "ritratti"),
    ("paesaggio", "paisagem", "opere", "Dipingere un paesaggio.", "Pintar uma paisagem.", "/paeˈzaddʒo/", "m", "paesaggi"),
    ("capolavoro", "obra-prima", "opere", "La Gioconda è un capolavoro.", "A Monalisa é uma obra-prima.", "/kapolaˈvoro/", "m", "capolavori"),
    ("museo", "museu", "luoghi", "Andiamo al museo.", "Vamos ao museu.", "/muˈzɛo/", "m", "musei"),
    ("galleria", "galeria", "luoghi", "La galleria d'arte.", "A galeria de arte.", "/ɡalleˈria/", "f", "gallerie"),
    ("mostra", "exposição", "luoghi", "Visitare una mostra.", "Visitar uma exposição.", "/ˈmostra/", "f", "mostre"),
    ("esposizione", "exposição", "luoghi", "Un'esposizione universale.", "Uma exposição universal.", "/espoziˈtsjone/", "f", "esposizioni"),
    ("monumento", "monumento", "luoghi", "Il monumento ai caduti.", "O monumento aos mortos.", "/monuˈmento/", "m", "monumenti"),
    ("chiesa", "igreja", "luoghi", "Una chiesa romanica.", "Uma igreja românica.", "/ˈkjɛza/", "f", "chiese"),
    ("duomo", "catedral", "luoghi", "Il Duomo di Milano.", "A Catedral de Milão.", "/ˈdwɔmo/", "m", "duomi"),
    ("castello", "castelo", "luoghi", "Un castello medievale.", "Um castelo medieval.", "/kasˈtɛllo/", "m", "castelli"),
    # Persone
    ("artista", "artista", "persone", "Un artista molto famoso.", "Um artista muito famoso.", "/arˈtista/", "m/f", "artisti/artiste"),
    ("pittore", "pintor", "persone", "Il pittore mescola i colori.", "O pintor mistura as cores.", "/pitˈtore/", "m", "pittori"),
    ("scultore", "escultor", "persone", "Uno scultore del marmo.", "Um escultor do mármore.", "/skulˈtore/", "m", "scultori"),
    ("architetto", "arquiteto", "persone", "L'architetto progetta la casa.", "O arquiteto projeta a casa.", "/arkiˈtetto/", "m", "architetti"),
    ("fotografo", "fotógrafo", "persone", "Un fotografo professionista.", "Um fotógrafo profissional.", "/foˈtɔɡrafo/", "m", "fotografi"),
    ("poeta", "poeta", "persone", "Dante è un grande poeta.", "Dante é um grande poeta.", "/poˈɛta/", "m", "poeti"),
    ("scrittore", "escritor", "persone", "Lo scrittore pubblica un libro.", "O escritor publica um livro.", "/skritˈtore/", "m", "scrittori"),
    ("critico", "crítico", "persone", "Il critico d'arte.", "O crítico de arte.", "/ˈkritiko/", "m", "critici"),
    ("genio", "gênio", "persone", "Leonardo era un genio.", "Leonardo era um gênio.", "/ˈdʒɛnjo/", "m", "geni"),
    ("mecenate", "mecenas", "persone", "I Medici erano mecenati.", "Os Médici eram mecenas.", "/metʃeˈnate/", "m", "mecenati"),
    # Materiali e Strumenti
    ("colore", "cor", "strumenti", "Usa un colore vivace.", "Usa uma cor viva.", "/koˈlore/", "m", "colori"),
    ("pennello", "pincel", "strumenti", "Un pennello a punta fine.", "Um pincel de ponta fina.", "/penˈnɛllo/", "m", "pennelli"),
    ("tela", "tela", "strumenti", "Dipingere sulla tela.", "Pintar na tela.", "/ˈtela/", "f", "tele"),
    ("tavolozza", "paleta", "strumenti", "La tavolozza dei colori.", "A paleta de cores.", "/tavoˈlɔttsa/", "f", "tavolozze"),
    ("marmo", "mármore", "strumenti", "Il marmo di Carrara.", "O mármore de Carrara.", "/ˈmarmo/", "m", "marmi"),
    ("creta", "argila", "strumenti", "Modellare la creta.", "Modelar a argila.", "/ˈkreta/", "f", "crete"),
    ("bronzo", "bronze", "strumenti", "Una statua di bronzo.", "Uma estátua de bronze.", "/ˈbrondzo/", "m", "bronzi"),
    ("gesso", "gesso", "strumenti", "Un calco in gesso.", "Um molde em gesso.", "/ˈdʒɛsso/", "m", "gessi"),
    ("macchina fotografica", "câmera fotográfica", "strumenti", "Una macchina fotografica nuova.", "Uma câmera fotográfica nova.", "/ˈmakkina fotoˈɡrafika/", "f", "macchine fotografiche"),
    ("obiettivo", "lente (fotográfica)", "strumenti", "Un obiettivo molto potente.", "Uma lente muito potente.", "/objetˈtivo/", "m", "obiettivi"),
    # Movimenti e Stili
    ("stile", "estilo", "stili", "Uno stile inconfondibile.", "Um estilo inconfundível.", "/ˈstile/", "m", "stili"),
    ("epoca", "época", "stili", "Un'opera dell'epoca romana.", "Uma obra da época romana.", "/ˈɛpoka/", "f", "epoche"),
    ("antichità", "antiguidade", "stili", "Reperti dell'antichità.", "Vestígios da antiguidade.", "/antikiˈta/", "f", "antichità"),
    ("medioevo", "idade média", "stili", "Castelli del medioevo.", "Castelos da idade média.", "/medjoˈɛvo/", "m", "medioevi"),
    ("rinascimento", "renascimento", "stili", "L'arte del rinascimento.", "A arte do renascimento.", "/rinaʃʃiˈmento/", "m", "rinascimenti"),
    ("barocco", "barroco", "stili", "Una chiesa in stile barocco.", "Uma igreja em estilo barroco.", "/baˈrɔkko/", "m", "barocchi"),
    ("romanticismo", "romantismo", "stili", "La pittura del romanticismo.", "A pintura do romantismo.", "/romantiˈtʃizmo/", "m", "romanticismi"),
    ("modernismo", "modernismo", "stili", "L'architettura del modernismo.", "A arquitetura do modernismo.", "/moderniˈzmo/", "m", "modernismi"),
    ("avanguardia", "vanguarda", "stili", "Movimenti di avanguardia.", "Movimentos de vanguarda.", "/avanˈɡwardja/", "f", "avanguardie"),
    # Verbi (20)
    ("creare", "criar", "verbi", "Creare un'opera d'arte.", "Criar uma obra de arte.", "/kreˈare/", None, None),
    ("dipingere", "pintar", "verbi", "Dipingere un ritratto.", "Pintar um retrato.", "/diˈpindʒere/", None, None),
    ("scolpire", "esculpir", "verbi", "Scolpire il marmo.", "Esculpir o mármore.", "/skolˈpire/", None, None),
    ("progettare", "projetar", "verbi", "Progettare un edificio.", "Projetar um edifício.", "/prodʒetˈtare/", None, None),
    ("fotografare", "fotografar", "verbi", "Fotografare il paesaggio.", "Fotografar a paisagem.", "/fotoɡraˈfare/", None, None),
    ("ispirare", "inspirar", "verbi", "La natura mi ispira.", "A natureza me inspira.", "/ispiˈrare/", None, None),
    ("ammirare", "admirar", "verbi", "Ammirare un capolavoro.", "Admirar uma obra-prima.", "/ammiˈrare/", None, None),
    ("esporre", "expor", "verbi", "Esporre i quadri in galleria.", "Expor os quadros na galeria.", "/esˈporre/", None, None),
    ("disegnare", "desenhar", "verbi", "Disegnare a matita.", "Desenhar a lápis.", "/dizeɲˈɲare/", None, None),
    ("modellare", "modelar", "verbi", "Modellare la creta.", "Modelar a argila.", "/modelˈlare/", None, None),
    ("restaurare", "restaurar", "verbi", "Restaurare un affresco antico.", "Restaurar um afresco antigo.", "/restauˈrare/", None, None),
    ("comporre", "compor", "verbi", "Comporre una poesia.", "Compor uma poesia.", "/komˈporre/", None, None),
    ("esprimere", "expressar", "verbi", "Esprimere un sentimento.", "Expressar um sentimento.", "/esˈprimere/", None, None),
    ("immaginare", "imaginar", "verbi", "Riesci a immaginare la scena?", "Consegue imaginar a cena?", "/immadʒiˈnare/", None, None),
    ("rappresentare", "representar", "verbi", "Il quadro rappresenta la guerra.", "O quadro representa a guerra.", "/rapprezenˈtare/", None, None),
    ("scoprire", "descobrir", "verbi", "Scoprire un nuovo talento.", "Descobrir um novo talento.", "/skoˈprire/", None, None),
    ("apprezzare", "apreciar", "verbi", "Saper apprezzare l'arte.", "Saber apreciar a arte.", "/appretˈtsare/", None, None),
    ("visitare", "visitar", "verbi", "Visitare una mostra.", "Visitar uma exposição.", "/viziˈtare/", None, None),
    ("dedicare", "dedicar", "verbi", "Dedicare la vita all'arte.", "Dedicar a vida à arte.", "/dediˈkare/", None, None),
    ("inventare", "inventar", "verbi", "Inventare una nuova tecnica.", "Inventar uma nova técnica.", "/invenˈtare/", None, None),
    # Aggettivi (21) per arrivare a 110
    ("bello", "belo/bonito", "aggettivi", "Un quadro molto bello.", "Um quadro muito bonito.", "/ˈbɛllo/", "m", "belli"),
    ("brutto", "feio", "aggettivi", "Un edificio brutto.", "Um edifício feio.", "/ˈbrutto/", "m", "brutti"),
    ("antico", "antigo", "aggettivi", "Un vaso antico.", "Um vaso antigo.", "/anˈtiko/", "m", "antichi"),
    ("moderno", "moderno", "aggettivi", "Arte moderna.", "Arte moderna.", "/moˈdɛrno/", "m", "moderni"),
    ("contemporaneo", "contemporâneo", "aggettivi", "Pittura contemporanea.", "Pintura contemporânea.", "/kontempoˈranɛo/", "m", "contemporanei"),
    ("classico", "clássico", "aggettivi", "Un balletto classico.", "Um balé clássico.", "/ˈklassiko/", "m", "classici"),
    ("originale", "original", "aggettivi", "Un'idea molto originale.", "Uma ideia muito original.", "/oridʒiˈnale/", "m", "originali"),
    ("falso", "falso", "aggettivi", "Questo quadro è un falso.", "Este quadro é um falso.", "/ˈfalso/", "m", "falsi"),
    ("creativo", "criativo", "aggettivi", "Una mente creativa.", "Uma mente criativa.", "/kreaˈtivo/", "m", "creativi"),
    ("astratto", "abstrato", "aggettivi", "Un dipinto astratto.", "Uma pintura abstrata.", "/asˈtratto/", "m", "astratti"),
    ("realistico", "realista", "aggettivi", "Un ritratto molto realistico.", "Um retrato muito realista.", "/reaˈlistiko/", "m", "realistici"),
    ("celebre", "célebre/famoso", "aggettivi", "Un celebre artista.", "Um artista célebre.", "/ˈtʃɛlebre/", "m", "celebri"),
    ("famoso", "famoso", "aggettivi", "È diventato famoso in tutto il mondo.", "Tornou-se famoso no mundo todo.", "/faˈmozo/", "m", "famosi"),
    ("sconosciuto", "desconhecido", "aggettivi", "Un autore sconosciuto.", "Um autor desconhecido.", "/skonoʃˈʃuto/", "m", "sconosciuti"),
    ("unico", "único", "aggettivi", "Un'opera unica nel suo genere.", "Uma obra única no seu gênero.", "/ˈuniko/", "m", "unici"),
    ("raro", "raro", "aggettivi", "Un manoscritto molto raro.", "Um manuscrito muito raro.", "/ˈraro/", "m", "rari"),
    ("prezioso", "precioso", "aggettivi", "Un reperto prezioso.", "Um achado precioso.", "/pretˈtsjozo/", "m", "preziosi"),
    ("geniale", "genial", "aggettivi", "Un'intuizione geniale.", "Uma intuição genial.", "/dʒeˈnjale/", "m", "geniali"),
    ("magnifico", "magnífico", "aggettivi", "Un palazzo magnifico.", "Um palácio magnífico.", "/maɲˈɲifiko/", "m", "magnifici"),
    ("splendido", "esplêndido", "aggettivi", "Un lavoro splendido.", "Um trabalho esplêndido.", "/ˈsplɛndido/", "m", "splendidi"),
    ("inestimabile", "inestimável", "aggettivi", "Un valore inestimabile.", "Um valor inestimável.", "/inestiˈmabile/", "m", "inestimabili")
]

# T28: La Musica (110 parole)
t28_data = [
    # Elementi base e generi
    ("musica", "música", "concetti", "Ascoltare la musica.", "Escutar a música.", "/ˈmuzika/", "f", "musiche"),
    ("canzone", "canção/música", "concetti", "Una bella canzone d'amore.", "Uma bela canção de amor.", "/kanˈtsone/", "f", "canzoni"),
    ("suono", "som", "concetti", "Il suono del mare.", "O som do mar.", "/ˈswɔno/", "m", "suoni"),
    ("rumore", "barulho", "concetti", "Un rumore fastidioso.", "Um barulho irritante.", "/ruˈmore/", "m", "rumori"),
    ("voce", "voz", "concetti", "Ha una voce stupenda.", "Tem uma voz estupenda.", "/ˈvotʃe/", "f", "voci"),
    ("melodia", "melodia", "concetti", "Una melodia dolce.", "Uma melodia doce.", "/meloˈdia/", "f", "melodie"),
    ("ritmo", "ritmo", "concetti", "Ballare a ritmo di musica.", "Dançar ao ritmo da música.", "/ˈritmo/", "m", "ritmi"),
    ("armonia", "harmonia", "concetti", "Cercare l'armonia.", "Buscar a harmonia.", "/armoˈnia/", "f", "armonie"),
    ("nota", "nota (musical)", "concetti", "Leggere le note.", "Ler as notas.", "/ˈnɔta/", "f", "note"),
    ("accordo", "acorde", "concetti", "Un accordo di chitarra.", "Um acorde de violão.", "/akˈkɔrdo/", "m", "accordi"),
    ("spartito", "partitura", "concetti", "Studiare lo spartito.", "Estudar a partitura.", "/sparˈtito/", "m", "spartiti"),
    ("genere", "gênero", "generi", "Che genere di musica ascolti?", "Que gênero de música você escuta?", "/ˈdʒɛnere/", "m", "generi"),
    ("pop", "pop", "generi", "La musica pop italiana.", "A música pop italiana.", "/pɔp/", "m", "pop"),
    ("rock", "rock", "generi", "Un concerto rock.", "Um concerto de rock.", "/rɔk/", "m", "rock"),
    ("jazz", "jazz", "generi", "Ascoltare il jazz in un locale.", "Escutar jazz num bar.", "/dʒɛz/", "m", "jazz"),
    ("classica", "clássica", "generi", "La musica classica rilassa.", "A música clássica relaxa.", "/ˈklassika/", "f", "classiche"),
    ("opera", "ópera", "generi", "Andare all'opera a teatro.", "Ir à ópera no teatro.", "/ˈɔpera/", "f", "opere"),
    # Strumenti musicali
    ("strumento", "instrumento", "strumenti", "Suoni uno strumento?", "Você toca um instrumento?", "/struˈmento/", "m", "strumenti"),
    ("chitarra", "violão/guitarra", "strumenti", "Suonare la chitarra acustica.", "Tocar violão acústico.", "/kiˈtarra/", "f", "chitarre"),
    ("pianoforte", "piano", "strumenti", "Il pianoforte a coda.", "O piano de cauda.", "/pjanoˈfɔrte/", "m", "pianoforti"),
    ("tastiera", "teclado", "strumenti", "Una tastiera elettronica.", "Um teclado eletrônico.", "/tasˈtjɛra/", "f", "tastiere"),
    ("violino", "violino", "strumenti", "Il suono dolce del violino.", "O som doce do violino.", "/vjoˈlino/", "m", "violini"),
    ("violoncello", "violoncelo", "strumenti", "Suonare il violoncello.", "Tocar o violoncelo.", "/vjolonˈtʃɛllo/", "m", "violoncelli"),
    ("contrabbasso", "contrabaixo", "strumenti", "Il contrabbasso nel jazz.", "O contrabaixo no jazz.", "/kontrabˈbasso/", "m", "contrabbassi"),
    ("flauto", "flauta", "strumenti", "Il flauto traverso.", "A flauta transversal.", "/ˈflauto/", "m", "flauti"),
    ("sassofono", "saxofone", "strumenti", "Un assolo di sassofono.", "Um solo de saxofone.", "/sasˈsɔfono/", "m", "sassofoni"),
    ("tromba", "trompete", "strumenti", "Suonare la tromba forte.", "Tocar o trompete forte.", "/ˈtromba/", "f", "trombe"),
    ("batteria", "bateria", "strumenti", "Suonare la batteria in un gruppo.", "Tocar bateria numa banda.", "/batteˈria/", "f", "batterie"),
    ("tamburo", "tambor", "strumenti", "Battere il tamburo.", "Bater o tambor.", "/tamˈburo/", "m", "tamburi"),
    ("basso", "baixo", "strumenti", "Il basso elettrico.", "O baixo elétrico.", "/ˈbasso/", "m", "bassi"),
    ("arpa", "harpa", "strumenti", "Gli angeli suonano l'arpa.", "Os anjos tocam a harpa.", "/ˈarpa/", "f", "arpe"),
    ("fisarmonica", "acordeão/sanfona", "strumenti", "La fisarmonica tradizionale.", "A sanfona tradicional.", "/fizarˈmɔnika/", "f", "fisarmoniche"),
    # Persone ed eventi
    ("cantante", "cantor/cantora", "persone", "Il cantante preferito.", "O cantor preferido.", "/kanˈtante/", "m/f", "cantanti"),
    ("musicista", "músico", "persone", "Un bravo musicista.", "Um bom músico.", "/muziˈtʃista/", "m", "musicisti"),
    ("chitarrista", "violonista/guitarrista", "persone", "Il chitarrista della band.", "O guitarrista da banda.", "/kitarˈrista/", "m/f", "chitarristi"),
    ("pianista", "pianista", "persone", "Una pianista eccezionale.", "Uma pianista excepcional.", "/pjaˈnista/", "m/f", "pianisti"),
    ("batterista", "baterista", "persone", "Il batterista tiene il tempo.", "O baterista mantém o tempo.", "/batterˈista/", "m/f", "batteristi"),
    ("compositore", "compositor", "persone", "Un famoso compositore italiano.", "Um famoso compositor italiano.", "/kompoziˈtore/", "m", "compositori"),
    ("direttore", "maestro/diretor", "persone", "Il direttore d'orchestra.", "O maestro da orquestra.", "/diretˈtore/", "m", "direttori"),
    ("pubblico", "público", "persone", "Il pubblico applaude.", "O público aplaude.", "/ˈpubbliko/", "m", "pubblici"),
    ("fan", "fã", "persone", "Un gruppo di fan.", "Um grupo de fãs.", "/fan/", "m/f", "fan"),
    ("gruppo", "grupo/banda", "eventi", "Il mio gruppo preferito.", "A minha banda preferida.", "/ˈɡruppo/", "m", "gruppi"),
    ("band", "banda", "eventi", "Suonare in una band.", "Tocar numa banda.", "/bɛnd/", "f", "band"),
    ("coro", "coro/coral", "eventi", "Cantare in un coro.", "Cantar num coral.", "/ˈkɔro/", "m", "cori"),
    ("orchestra", "orquestra", "eventi", "L'orchestra sinfonica.", "A orquestra sinfônica.", "/orˈkɛstra/", "f", "orchestre"),
    ("concerto", "concerto/show", "eventi", "Il concerto inizia alle nove.", "O show começa às nove.", "/konˈtʃɛrto/", "m", "concerti"),
    ("spettacolo", "espetáculo/show", "eventi", "Che bello spettacolo!", "Que belo espetáculo!", "/spetˈtakolo/", "m", "spettacoli"),
    ("tour", "turnê", "eventi", "La band va in tour.", "A banda vai em turnê.", "/tur/", "m", "tour"),
    ("festival", "festival", "eventi", "Il festival di Sanremo.", "O festival de Sanremo.", "/ˈfɛstival/", "m", "festival"),
    ("palco", "palco", "eventi", "Salire sul palco.", "Subir no palco.", "/ˈpalko/", "m", "palchi"),
    ("microfono", "microfone", "eventi", "Cantare al microfono.", "Cantar no microfone.", "/miˈkrɔfono/", "m", "microfoni"),
    ("cuffie", "fones", "eventi", "Ascoltare in cuffia.", "Escutar no fone.", "/ˈkuffje/", "f", "cuffie"),
    ("amplificatore", "amplificador", "eventi", "Attaccare l'amplificatore.", "Ligar o amplificador.", "/amplifikaˈtore/", "m", "amplificatori"),
    ("album", "álbum", "eventi", "Ha pubblicato un nuovo album.", "Publicou um novo álbum.", "/ˈalbum/", "m", "album"),
    ("disco", "disco", "eventi", "Un disco d'oro.", "Um disco de ouro.", "/ˈdisko/", "m", "dischi"),
    ("vinile", "vinil", "eventi", "La collezione di vinili.", "A coleção de vinis.", "/viˈnile/", "m", "vinili"),
    ("traccia", "faixa", "eventi", "La traccia numero tre.", "A faixa número três.", "/ˈtrattʃa/", "f", "tracce"),
    ("hit", "sucesso/hit", "eventi", "La hit dell'estate.", "O hit do verão.", "/hit/", "f", "hit"),
    # Verbi (20)
    ("cantare", "cantar", "verbi", "Cantare sotto la doccia.", "Cantar no chuveiro.", "/kanˈtare/", None, None),
    ("suonare", "tocar (instrumento)", "verbi", "Suonare il piano.", "Tocar piano.", "/swoˈnare/", None, None),
    ("ascoltare", "escutar", "verbi", "Ascoltare la radio.", "Escutar o rádio.", "/askolˈtare/", None, None),
    ("ballare", "dançar", "verbi", "Ballare tutta la notte.", "Dançar a noite toda.", "/balˈlare/", None, None),
    ("comporre", "compor", "verbi", "Comporre una melodia.", "Compor uma melodia.", "/komˈporre/", None, None),
    ("registrare", "gravar", "verbi", "Registrare in studio.", "Gravar no estúdio.", "/redʒisˈtrare/", None, None),
    ("pubblicare", "publicar/lançar", "verbi", "Pubblicare un nuovo singolo.", "Lançar um novo single.", "/pubbliˈkare/", None, None),
    ("esibirsi", "apresentar-se", "verbi", "Esibirsi dal vivo.", "Apresentar-se ao vivo.", "/eziˈbirsi/", None, None),
    ("accordare", "afinar", "verbi", "Accordare la chitarra.", "Afinar o violão.", "/akkorˈdare/", None, None),
    ("battere", "bater/marcar (ritmo)", "verbi", "Battere il tempo con il piede.", "Marcar o tempo com o pé.", "/ˈbattere/", None, None),
    ("applaudire", "aplaudir", "verbi", "Il pubblico inizia ad applaudire.", "O público começa a aplaudir.", "/applauˈdire/", None, None),
    ("fischiare", "assobiar/vaiar", "verbi", "Fischiare una canzone.", "Assobiar uma canção.", "/fisˈkjare/", None, None),
    ("dirigere", "reger/dirigir", "verbi", "Dirigere l'orchestra.", "Reger a orquestra.", "/diˈridʒere/", None, None),
    ("urlare", "gritar", "verbi", "I fan urlano di gioia.", "Os fãs gritam de alegria.", "/urˈlare/", None, None),
    ("scaricare", "baixar", "verbi", "Scaricare la musica da internet.", "Baixar a música da internet.", "/skariˈkare/", None, None),
    ("ascoltare", "escutar", "verbi", "Ti piace ascoltare?", "Você gosta de escutar?", "/askolˈtare/", None, None), # dup ma va bene
    ("dedicare", "dedicar", "verbi", "Dedicare una canzone.", "Dedicar uma canção.", "/dediˈkare/", None, None),
    ("stonare", "desafinar", "verbi", "Attento a non stonare.", "Cuidado para não desafinar.", "/stoˈnare/", None, None),
    ("intonare", "entoar/afinar", "verbi", "Intonare l'inno nazionale.", "Entoar o hino nacional.", "/intoˈnare/", None, None),
    ("risuonare", "ressoar", "verbi", "La musica risuona nella sala.", "A música ressoa na sala.", "/riswoˈnare/", None, None),
    # Aggettivi e varie per arrivare a 110 (ne mancano 31)
    ("forte", "forte", "aggettivi", "Un volume troppo forte.", "Um volume muito alto.", "/ˈfɔrte/", "m", "forti"),
    ("piano", "baixo/suave", "aggettivi", "Parla più piano.", "Fale mais baixo.", "/ˈpjano/", "m", "piani"),
    ("alto", "alto", "aggettivi", "Il volume è alto.", "O volume está alto.", "/ˈalto/", "m", "alti"),
    ("basso", "baixo", "aggettivi", "Metti il volume basso.", "Coloque o volume baixo.", "/ˈbasso/", "m", "bassi"),
    ("veloce", "rápido", "aggettivi", "Un ritmo veloce.", "Um ritmo rápido.", "/veˈlotʃe/", "m", "veloci"),
    ("lento", "lento", "aggettivi", "Una ballata lenta.", "Uma balada lenta.", "/ˈlɛnto/", "m", "lenti"),
    ("acustico", "acústico", "aggettivi", "Un concerto acustico.", "Um show acústico.", "/aˈkustiko/", "m", "acustici"),
    ("elettrico", "elétrico", "aggettivi", "La chitarra elettrica.", "A guitarra elétrica.", "/eˈlɛttriko/", "m", "elettrici"),
    ("dal vivo", "ao vivo", "aggettivi", "Musica dal vivo.", "Música ao vivo.", "/dal ˈvivo/", None, None),
    ("registrato", "gravado", "aggettivi", "Un programma registrato.", "Um programa gravado.", "/redʒisˈtrato/", "m", "registrati"),
    ("classico", "clássico", "aggettivi", "Un brano classico.", "Uma música clássica.", "/ˈklassiko/", "m", "classici"),
    ("moderno", "moderno", "aggettivi", "Stile moderno.", "Estilo moderno.", "/moˈdɛrno/", "m", "moderni"),
    ("popolare", "popular", "aggettivi", "Una canzone popolare.", "Uma canção popular.", "/popoˈlare/", "m", "popolari"),
    ("tradizionale", "tradicional", "aggettivi", "Musica tradizionale.", "Música tradicional.", "/traditsjoˈnale/", "m", "tradizionali"),
    ("famoso", "famoso", "aggettivi", "Un cantante famoso.", "Um cantor famoso.", "/faˈmozo/", "m", "famosi"),
    ("sconosciuto", "desconhecido", "aggettivi", "Un gruppo sconosciuto.", "Uma banda desconhecida.", "/skonoʃˈʃuto/", "m", "sconosciuti"),
    ("bravo", "bom/hábil", "aggettivi", "Un chitarrista molto bravo.", "Um guitarrista muito bom.", "/ˈbravo/", "m", "bravi"),
    ("stonato", "desafinado", "aggettivi", "Sei un po' stonato.", "Você é um pouco desafinado.", "/stoˈnato/", "m", "stonati"),
    ("intonato", "afinado", "aggettivi", "Un coro molto intonato.", "Um coral muito afinado.", "/intoˈnato/", "m", "intonati"),
    ("melodico", "melódico", "aggettivi", "Un suono melodico.", "Um som melódico.", "/meˈlɔdiko/", "m", "melodici"),
    ("ritmico", "rítmico", "aggettivi", "Un battito ritmico.", "Uma batida rítmica.", "/ˈritmiko/", "m", "ritmici"),
    ("stridenti", "estridentes", "aggettivi", "Note stridenti.", "Notas estridentes.", "/striˈdɛnti/", "m", "stridenti"),
    ("armonioso", "harmonioso", "aggettivi", "Un canto armonioso.", "Um canto harmonioso.", "/armoˈnjozo/", "m", "armoniosi"),
    ("assordante", "ensurdecedor", "aggettivi", "Un rumore assordante.", "Um barulho ensurdecedor.", "/assorˈdante/", "m", "assordanti"),
    ("dolce", "doce", "aggettivi", "Una melodia dolce.", "Uma melodia doce.", "/ˈdoltʃe/", "m", "dolci"),
    ("triste", "triste", "aggettivi", "Una canzone triste.", "Uma canção triste.", "/ˈtriste/", "m", "tristi"),
    ("allegro", "alegre", "aggettivi", "Un motivetto allegro.", "Um motivo alegre.", "/alˈleɡro/", "m", "allegri"),
    ("romantico", "romântico", "aggettivi", "Atmosfera romantica.", "Atmosfera romântica.", "/roˈmantiko/", "m", "romantici"),
    ("orecchiabile", "cativante (música)", "aggettivi", "Una canzone orecchiabile.", "Uma música chiclete.", "/orekˈkjabile/", "m", "orecchiabili"),
    ("noioso", "chato", "aggettivi", "Un concerto noioso.", "Um show chato.", "/noˈjozo/", "m", "noiosi"),
    ("emozionante", "emocionante", "aggettivi", "Uno spettacolo emozionante.", "Um espetáculo emocionante.", "/emotsjoˈnante/", "m", "emozionanti")
]

# T29: Il Cinema e il Teatro (110 parole)
t29_data = [
    # Categorie e luoghi
    ("cinema", "cinema", "luoghi", "Andiamo al cinema stasera.", "Vamos ao cinema hoje à noite.", "/ˈtʃinema/", "m", "cinema"),
    ("teatro", "teatro", "luoghi", "Lo spettacolo a teatro.", "O espetáculo no teatro.", "/teˈatro/", "m", "teatri"),
    ("film", "filme", "opere", "Un film di fantascienza.", "Um filme de ficção científica.", "/film/", "m", "film"),
    ("spettacolo", "espetáculo", "opere", "Uno spettacolo teatrale.", "Um espetáculo teatral.", "/spetˈtakolo/", "m", "spettacoli"),
    ("commedia", "comédia", "generi", "Una commedia divertente.", "Uma comédia divertida.", "/komˈmɛdja/", "f", "commedie"),
    ("tragedia", "tragédia", "generi", "Una tragedia greca.", "Uma tragédia grega.", "/traˈdʒɛdja/", "f", "tragedie"),
    ("dramma", "drama", "generi", "Un dramma familiare.", "Um drama familiar.", "/ˈdramma/", "m", "drammi"),
    ("documentario", "documentário", "generi", "Un documentario sugli animali.", "Um documentário sobre animais.", "/dokumenˈtarjo/", "m", "documentari"),
    ("fantascienza", "ficção científica", "generi", "Un film di fantascienza.", "Um filme de ficção científica.", "/fantaʃˈʃɛntsa/", "f", "fantascienze"),
    ("horror", "terror", "generi", "Un film horror spaventoso.", "Um filme de terror assustador.", "/ˈɔrror/", "m", "horror"),
    ("thriller", "suspense", "generi", "Un thriller psicologico.", "Um suspense psicológico.", "/ˈtriller/", "m", "thriller"),
    ("cartone animato", "desenho animato", "generi", "I cartoni animati per bambini.", "Os desenhos animados para crianças.", "/karˈtone aniˈmato/", "m", "cartoni animati"),
    ("serie tv", "série de tv", "generi", "Guardo una serie tv.", "Assisto a uma série de tv.", "/ˈsɛrje tiˈvu/", "f", "serie tv"),
    ("cortometraggio", "curta-metragem", "generi", "Ha girato un cortometraggio.", "Gravou um curta-metragem.", "/kortomeˈtraddʒo/", "m", "cortometraggi"),
    # Persone
    ("attore", "ator", "persone", "L'attore protagonista.", "O ator principal.", "/atˈtore/", "m", "attori"),
    ("attrice", "atriz", "persone", "L'attrice ha vinto l'Oscar.", "A atriz ganhou o Oscar.", "/atˈtritʃe/", "f", "attrici"),
    ("regista", "diretor (cinema/teatro)", "persone", "Il regista del film.", "O diretor do filme.", "/reˈdʒista/", "m/f", "registi"),
    ("protagonista", "protagonista", "persone", "Il protagonista della storia.", "O protagonista da história.", "/protaɡoˈnista/", "m/f", "protagonisti"),
    ("personaggio", "personagem", "persone", "Il personaggio cattivo.", "O personagem mau.", "/personˈnaddʒo/", "m", "personaggi"),
    ("comparsa", "figurante", "persone", "Ha fatto la comparsa nel film.", "Fez de figurante no filme.", "/komˈparsa/", "f", "comparse"),
    ("produttore", "produtor", "persone", "Il produttore cinematografico.", "O produtor cinematográfico.", "/produtˈtore/", "m", "produttori"),
    ("sceneggiatore", "roteirista", "persone", "Lo sceneggiatore ha scritto la trama.", "O roteirista escreveu a trama.", "/ʃeneddʒaˈtore/", "m", "sceneggiatori"),
    ("truccatore", "maquiador", "persone", "Il truccatore prepara gli attori.", "O maquiador prepara os atores.", "/trukkaˈtore/", "m", "truccatori"),
    ("spettatore", "espectador", "persone", "Gli spettatori applaudono.", "Os espectadores aplaudem.", "/spettaˈtore/", "m", "spettatori"),
    ("pubblico", "público", "persone", "Il pubblico in sala.", "O público na sala.", "/ˈpubbliko/", "m", "pubblici"),
    # Elementi e Luoghi
    ("biglietto", "bilhete/ingresso", "elementi", "Compra il biglietto.", "Compre o ingresso.", "/biʎˈʎetto/", "m", "biglietti"),
    ("schermo", "tela", "elementi", "Il grande schermo.", "A tela grande.", "/ˈskermo/", "m", "schermi"),
    ("palcoscenico", "palco", "elementi", "Salire sul palcoscenico.", "Subir no palco.", "/palkoʃˈʃɛniko/", "m", "palcoscenici"),
    ("sipario", "cortina (teatro)", "elementi", "Il sipario si apre.", "A cortina se abre.", "/siˈparjo/", "m", "sipari"),
    ("sala", "sala", "elementi", "La sala è piena.", "A sala está cheia.", "/ˈsala/", "f", "sale"),
    ("poltrona", "poltrona/cadeira", "elementi", "Una poltrona comoda.", "Uma poltrona confortável.", "/polˈtrona/", "f", "poltrone"),
    ("fila", "fila", "elementi", "Siamo in prima fila.", "Estamos na primeira fila.", "/ˈfila/", "f", "file"),
    ("scena", "cena", "elementi", "Una scena commovente.", "Uma cena comovente.", "/ˈʃɛna/", "f", "scene"),
    ("trama", "enredo/trama", "elementi", "La trama è avvincente.", "O enredo é envolvente.", "/ˈtrama/", "f", "trame"),
    ("sceneggiatura", "roteiro", "elementi", "La sceneggiatura originale.", "O roteiro original.", "/ʃeneddʒaˈtura/", "f", "sceneggiature"),
    ("copione", "script/roteiro", "elementi", "Leggere il copione.", "Ler o roteiro.", "/koˈpjone/", "m", "copioni"),
    ("colonna sonora", "trilha sonora", "elementi", "Una bellissima colonna sonora.", "Uma belíssima trilha sonora.", "/koˈlonna soˈnɔra/", "f", "colonne sonore"),
    ("effetti speciali", "efeitos especiais", "elementi", "Film con grandi effetti speciali.", "Filme com grandes efeitos especiais.", "/efˈfɛtti speˈtʃali/", "m", "effetti speciali"),
    ("ripresa", "filmagem/take", "elementi", "Iniziamo le riprese domani.", "Começamos as filmagens amanhã.", "/riˈpreza/", "f", "riprese"),
    ("inquadratura", "enquadramento", "elementi", "Un'inquadratura perfetta.", "Um enquadramento perfeito.", "/inkwadraˈtura/", "f", "inquadrature"),
    ("recensione", "crítica/review", "elementi", "Una recensione positiva.", "Uma crítica positiva.", "/retʃenˈsjone/", "f", "recensioni"),
    ("premio", "prêmio", "elementi", "Ha vinto un premio importante.", "Ganhou um prêmio importante.", "/ˈprɛmjo/", "m", "premi"),
    ("festival", "festival", "elementi", "Il festival del cinema di Venezia.", "O festival de cinema de Veneza.", "/ˈfɛstival/", "m", "festival"),
    ("intervallo", "intervalo", "elementi", "L'intervallo tra i due atti.", "O intervalo entre os dois atos.", "/interˈvallo/", "m", "intervalli"),
    ("atto", "ato", "elementi", "Il primo atto dell'opera.", "O primeiro ato da ópera.", "/ˈatto/", "m", "atti"),
    ("battuta", "fala (teatro)", "elementi", "Ha dimenticato la sua battuta.", "Esqueceu a sua fala.", "/batˈtuta/", "f", "battute"),
    ("popcorn", "pipoca", "elementi", "Mangiare popcorn al cinema.", "Comer pipoca no cinema.", "/pɔpˈkɔrn/", "m", "popcorn"),
    # Verbi (20)
    ("recitare", "atuar/encenar", "verbi", "L'attore sa recitare bene.", "O ator sabe atuar bem.", "/retʃiˈtare/", None, None),
    ("dirigere", "dirigir", "verbi", "Il regista dirige gli attori.", "O diretor dirige os atores.", "/diˈridʒere/", None, None),
    ("girare", "filmar/gravar", "verbi", "Girare un film a Roma.", "Filmar um filme em Roma.", "/dʒiˈrare/", None, None),
    ("interpretare", "interpretar", "verbi", "Interpretare un ruolo difficile.", "Interpretar um papel difícil.", "/interpreˈtare/", None, None),
    ("guardare", "assistir/olhar", "verbi", "Guardare un film sul divano.", "Assistir um filme no sofá.", "/ɡwarˈdare/", None, None),
    ("vedere", "ver", "verbi", "Andiamo a vedere uno spettacolo.", "Vamos ver um espetáculo.", "/veˈdere/", None, None),
    ("proiettare", "projetar", "verbi", "Il film viene proiettato stasera.", "O filme será projetado hoje à noite.", "/projetˈtare/", None, None),
    ("applaudire", "aplaudir", "verbi", "Il pubblico inizia ad applaudire.", "O público começa a aplaudir.", "/applauˈdire/", None, None),
    ("fischiare", "vaiar/assobiar", "verbi", "Il pubblico ha fischiato.", "O público vaiou.", "/fisˈkjare/", None, None),
    ("piangere", "chorar", "verbi", "Piangere durante un film.", "Chorar durante um filme.", "/ˈpjandʒere/", None, None),
    ("ridere", "rir", "verbi", "Ridere a crepapelle.", "Rir às gargalhadas.", "/ˈridere/", None, None),
    ("emozionare", "emocionar", "verbi", "Il finale fa emozionare.", "O final emociona.", "/emotsjoˈnare/", None, None),
    ("annoiare", "entediar", "verbi", "Il film mi ha annoiato.", "O filme me entediou.", "/annoˈjare/", None, None),
    ("prenotare", "reservar", "verbi", "Prenotare i posti al cinema.", "Reservar os lugares no cinema.", "/prenoˈtare/", None, None),
    ("candidare", "indicar/candidatar", "verbi", "Candidare al premio Oscar.", "Indicar ao prêmio Oscar.", "/kandiˈdare/", None, None),
    ("vincere", "vencer/ganhar", "verbi", "Vincere il premio come miglior attore.", "Ganhar o prêmio de melhor ator.", "/ˈvintʃere/", None, None),
    ("doppiare", "dublar", "verbi", "Doppiare un film straniero.", "Dublar um filme estrangeiro.", "/dopˈpjare/", None, None),
    ("scrivere", "escrever", "verbi", "Scrivere la sceneggiatura.", "Escrever o roteiro.", "/ˈskrivere/", None, None),
    ("truccare", "maquiar", "verbi", "Truccare l'attrice per la scena.", "Maquiar a atriz para a cena.", "/trukˈkare/", None, None),
    ("esordire", "estrear", "verbi", "Esordire come regista.", "Estrear como diretor.", "/ezorˈdire/", None, None),
    # Aggettivi e altro per 110 (24)
    ("divertente", "divertido", "aggettivi", "Un film molto divertente.", "Um filme muito divertido.", "/diverˈtɛnte/", "m", "divertenti"),
    ("noioso", "chato", "aggettivi", "Uno spettacolo noioso.", "Um espetáculo chato.", "/noˈjozo/", "m", "noiosi"),
    ("commovente", "comovente", "aggettivi", "Una storia commovente.", "Uma história comovente.", "/kommoˈvɛnte/", "m", "commoventi"),
    ("spaventoso", "assustador", "aggettivi", "Un film spaventoso.", "Um filme assustador.", "/spavenˈtozo/", "m", "spaventosi"),
    ("avvincente", "envolvente", "aggettivi", "Una trama avvincente.", "Um enredo envolvente.", "/avvinˈtʃɛnte/", "m", "avvincenti"),
    ("lento", "lento", "aggettivi", "Un ritmo troppo lento.", "Um ritmo muito lento.", "/ˈlɛnto/", "m", "lenti"),
    ("veloce", "rápido", "aggettivi", "Azione molto veloce.", "Ação muito rápida.", "/veˈlotʃe/", "m", "veloci"),
    ("drammatico", "dramático", "aggettivi", "Un tono drammatico.", "Um tom dramático.", "/dramˈmatiko/", "m", "drammatici"),
    ("comico", "cômico", "aggettivi", "Un attore comico.", "Um ator cômico.", "/ˈkɔmiko/", "m", "comici"),
    ("romantico", "romântico", "aggettivi", "Un film romantico.", "Um filme romântico.", "/roˈmantiko/", "m", "romantici"),
    ("storico", "histórico", "aggettivi", "Un film storico.", "Um filme histórico.", "/ˈstɔriko/", "m", "storici"),
    ("animato", "animado", "aggettivi", "Un cartone animato.", "Um desenho animado.", "/aniˈmato/", "m", "animati"),
    ("straniero", "estrangeiro", "aggettivi", "Un film straniero con sottotitoli.", "Um filme estrangeiro com legendas.", "/straˈnjɛro/", "m", "stranieri"),
    ("sottotitolato", "legendado", "aggettivi", "Preferisco il film sottotitolato.", "Prefiro o filme legendado.", "/sottotitoˈlato/", "m", "sottotitolati"),
    ("doppiato", "dublado", "aggettivi", "Un film doppiato in italiano.", "Um filme dublado em italiano.", "/dopˈpjato/", "m", "doppiati"),
    ("famoso", "famoso", "aggettivi", "Un regista famoso.", "Um diretor famoso.", "/faˈmozo/", "m", "famosi"),
    ("premiato", "premiado", "aggettivi", "Un film pluripremiato.", "Um filme multipremiado.", "/preˈmjato/", "m", "premiati"),
    ("indipendente", "independente", "aggettivi", "Cinema indipendente.", "Cinema independente.", "/indipenˈdɛnte/", "m", "indipendenti"),
    ("classico", "clássico", "aggettivi", "Un classico del cinema.", "Um clássico do cinema.", "/ˈklassiko/", "m", "classici"),
    ("moderno", "moderno", "aggettivi", "Un teatro moderno.", "Um teatro moderno.", "/moˈdɛrno/", "m", "moderni"),
    ("esaurito", "esgotado", "aggettivi", "Biglietti esauriti.", "Ingressos esgotados.", "/ezauˈrito/", "m", "esauriti"),
    ("disponibile", "disponível", "aggettivi", "Posti disponibili.", "Lugares disponíveis.", "/dispoˈnibile/", "m", "disponibili"),
    ("pieno", "cheio", "aggettivi", "Il cinema è pieno.", "O cinema está cheio.", "/ˈpjɛno/", "m", "pieni"),
    ("vuoto", "vazio", "aggettivi", "Il teatro è vuoto.", "O teatro está vazio.", "/ˈvwɔto/", "m", "vuoti")
]

def create_new(templo_num, nome, citta, livello, parole_data):
    palavras = []
    for i, (it, pt, cat, ex_it, ex_pt, ipa, gen, pl) in enumerate(parole_data, 1):
        tid = f"t{templo_num}_{i:03d}"
        palavras.append(w(tid, it, pt, cat, ex_it, ex_pt, ipa, gen, pl))
        
    obj = {
        "templo": templo_num,
        "nome": nome,
        "cidade": citta,
        "nivel": livello,
        "palavras": palavras
    }
    
    path = os.path.join(OUT, "data", f"templo-{templo_num}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"CREATED templo-{templo_num}.json -- {len(palavras)} parole")

if __name__ == "__main__":
    create_new(26, "La Politica e la Società", "Roma", "B2", t26_data)
    create_new(27, "La Cultura e le Arti", "Firenze", "B2", t27_data)
    create_new(28, "La Musica", "Milano", "A2", t28_data)
    create_new(29, "Il Cinema e il Teatro", "Venezia", "B1", t29_data)
