import json, os

OUT = os.path.dirname(os.path.abspath(__file__))

def w(tid, it, pt, cat, ex_it, ex_pt, ipa="", gen=None, pl=None):
    return {
        "id": tid, "italiano": it, "portugues": pt, "genero": gen, "plural": pl,
        "exemplo": ex_it, "exemplo_pt": ex_pt, "categoria": cat, "dificuldade": "medio", "audio_ipa": ipa
    }

# T34: La Moda e il Design (110 parole)
t34_data = [
    # Capi d'abbigliamento
    ("moda", "moda", "abbigliamento", "L'alta moda italiana.", "A alta costura italiana.", "/ˈmɔda/", "f", "mode"),
    ("vestito", "vestido/roupa", "abbigliamento", "Un vestito da sera.", "Um vestido de noite.", "/vesˈtito/", "m", "vestiti"),
    ("abito", "traje/roupa", "abbigliamento", "Un abito elegante.", "Um traje elegante.", "/ˈabito/", "m", "abiti"),
    ("camicia", "camisa", "abbigliamento", "Una camicia bianca.", "Uma camisa branca.", "/kaˈmitʃa/", "f", "camicie"),
    ("maglietta", "camiseta", "abbigliamento", "Una maglietta di cotone.", "Uma camiseta de algodão.", "/maʎˈʎetta/", "f", "magliette"),
    ("pantaloni", "calças", "abbigliamento", "Pantaloni lunghi.", "Calças compridas.", "/pantaˈloni/", "m", "pantaloni"),
    ("gonna", "saia", "abbigliamento", "Una gonna corta.", "Uma saia curta.", "/ˈɡonna/", "f", "gonne"),
    ("giacca", "jaqueta/paletó", "abbigliamento", "Una giacca di pelle.", "Uma jaqueta de couro.", "/ˈdʒakka/", "f", "giacche"),
    ("cappotto", "casaco", "abbigliamento", "Un cappotto pesante.", "Um casaco pesado.", "/kapˈpɔtto/", "m", "cappotti"),
    ("maglione", "suéter", "abbigliamento", "Un maglione di lana.", "Um suéter de lã.", "/maʎˈʎone/", "m", "maglioni"),
    ("jeans", "jeans", "abbigliamento", "Un paio di jeans.", "Um par de jeans.", "/dʒins/", "m", "jeans"),
    ("felpa", "moletom", "abbigliamento", "Una felpa sportiva.", "Um moletom esportivo.", "/ˈfelpa/", "f", "felpe"),
    ("costume", "traje de banho/fantasia", "abbigliamento", "Un costume da bagno.", "Um traje de banho.", "/kosˈtume/", "m", "costumi"),
    ("intimo", "roupa íntima", "abbigliamento", "L'abbigliamento intimo.", "A roupa íntima.", "/ˈintimo/", "m", "intimi"),
    ("pigiama", "pijama", "abbigliamento", "Un pigiama comodo.", "Um pijama confortável.", "/piˈdʒama/", "m", "pigiami"),
    ("calzino", "meia", "abbigliamento", "Un paio di calzini.", "Um par de meias.", "/kalˈtsino/", "m", "calzini"),
    ("calza", "meia-calça", "abbigliamento", "Calze di nylon.", "Meias de nylon.", "/ˈkaltsa/", "f", "calze"),
    ("scarpa", "sapato", "accessori", "Una scarpa col tacco.", "Um sapato de salto.", "/ˈskarpa/", "f", "scarpe"),
    ("stivale", "bota", "accessori", "Uno stivale invernale.", "Uma bota de inverno.", "/stiˈvale/", "m", "stivali"),
    ("sandalo", "sandália", "accessori", "Un sandalo estivo.", "Uma sandália de verão.", "/ˈsandalo/", "m", "sandali"),
    ("ciabatta", "chinelo", "accessori", "Le ciabatte da mare.", "Os chinelos de praia.", "/tʃaˈbatta/", "f", "ciabatte"),
    ("sneaker", "tênis", "accessori", "Sneaker comode.", "Tênis confortáveis.", "/ˈsniker/", "f", "sneaker"),
    # Accessori
    ("accessorio", "acessório", "accessori", "Un accessorio di moda.", "Um acessório de moda.", "/atʃtʃesˈsɔrjo/", "m", "accessori"),
    ("borsa", "bolsa", "accessori", "Una borsa di marca.", "Uma bolsa de marca.", "/ˈborsa/", "f", "borse"),
    ("zaino", "mochila", "accessori", "Uno zaino di pelle.", "Uma mochila de couro.", "/ˈdzaino/", "m", "zaini"),
    ("cappello", "chapéu", "accessori", "Un cappello elegante.", "Um chapéu elegante.", "/kapˈpɛllo/", "m", "cappelli"),
    ("sciarpa", "cachecol", "accessori", "Una sciarpa di lana.", "Um cachecol de lã.", "/ˈʃarpa/", "f", "sciarpe"),
    ("guanto", "luva", "accessori", "Guanti di pelle.", "Luvas de couro.", "/ˈɡwanto/", "m", "guanti"),
    ("cintura", "cinto", "accessori", "Una cintura stretta.", "Um cinto apertato.", "/tʃinˈtura/", "f", "cinture"),
    ("cravatta", "gravata", "accessori", "Una cravatta di seta.", "Uma gravata de seda.", "/kraˈvatta/", "f", "cravatte"),
    ("papillon", "gravata borboleta", "accessori", "Il papillon nero.", "A gravata borboleta preta.", "/papilˈlɔn/", "m", "papillon"),
    ("occhiali", "óculos", "accessori", "Gli occhiali da sole.", "Os óculos de sol.", "/okˈkjali/", "m", "occhiali"),
    ("orologio", "relógio", "accessori", "Un orologio di lusso.", "Um relógio de luxo.", "/oroˈlɔdʒo/", "m", "orologi"),
    ("gioiello", "joia", "accessori", "Un gioiello d'oro.", "Uma joia de ouro.", "/dʒoˈjɛllo/", "m", "gioielli"),
    ("anello", "anel", "accessori", "Un anello di fidanzamento.", "Um anel de noivado.", "/aˈnɛllo/", "m", "anelli"),
    ("collana", "colar", "accessori", "Una collana di perle.", "Um colar de pérolas.", "/kolˈlana/", "f", "collane"),
    ("orecchino", "brinco", "accessori", "Un orecchino d'argento.", "Um brinco de prata.", "/orekˈkino/", "m", "orecchini"),
    ("bracciale", "pulseira", "accessori", "Un bracciale colorato.", "Uma pulseira colorida.", "/bratˈtʃale/", "m", "bracciali"),
    ("trucco", "maquiaggio", "accessori", "Il trucco da sera.", "A maquiagem de noite.", "/ˈtrukko/", "m", "trucchi"),
    ("profumo", "perfume", "accessori", "Un profumo dolce.", "Um perfume doce.", "/proˈfumo/", "m", "profumi"),
    # Concetti e Materiali
    ("stile", "estilo", "concetti", "Ha molto stile.", "Tem muito estilo.", "/ˈstile/", "m", "stili"),
    ("tendenza", "tendência", "concetti", "L'ultima tendenza.", "A última tendência.", "/tenˈdɛntsa/", "f", "tendenze"),
    ("sfilata", "desfile", "concetti", "La sfilata di moda.", "O desfile de moda.", "/sfiˈlata/", "f", "sfilate"),
    ("collezione", "coleção", "concetti", "La collezione autunno.", "A coleção de outono.", "/kolletˈtsjone/", "f", "collezioni"),
    ("passerella", "passarela", "concetti", "Le modelle in passerella.", "As modelos na passarela.", "/passeˈrɛlla/", "f", "passerelle"),
    ("stilista", "estilista", "persone", "Uno stilista famoso.", "Um estilista famoso.", "/stiˈlista/", "m/f", "stilisti"),
    ("modello", "modelo (pessoa/roupa)", "persone", "Il modello sfila.", "O modelo desfila.", "/moˈdɛllo/", "m", "modelli"),
    ("sarto", "alfaiate/costureiro", "persone", "Il sarto taglia la stoffa.", "O alfaiate corta o tecido.", "/ˈsarto/", "m", "sarti"),
    ("negozio", "loja", "luoghi", "Un negozio di vestiti.", "Uma loja de roupas.", "/neˈɡɔttsjo/", "m", "negozi"),
    ("vetrina", "vitrine", "luoghi", "Guardare la vetrina.", "Olhar a vitrine.", "/veˈtrina/", "f", "vetrine"),
    ("manichino", "manequim", "luoghi", "Il manichino in vetrina.", "O manequim na vitrine.", "/maniˈkino/", "m", "manichini"),
    ("marca", "marca", "concetti", "Una marca famosa.", "Uma marca famosa.", "/ˈmarka/", "f", "marche"),
    ("taglia", "tamanho (roupa)", "concetti", "Che taglia porti?", "Que tamanho você usa?", "/ˈtaʎʎa/", "f", "taglie"),
    ("misura", "medida", "concetti", "Prendere la misura.", "Tirar a medida.", "/miˈzura/", "f", "misure"),
    ("tessuto", "tecido", "materiali", "Un tessuto morbido.", "Um tecido macio.", "/tesˈsuto/", "m", "tessuti"),
    ("stoffa", "pano/tecido", "materiali", "Tagliare la stoffa.", "Cortar o tecido.", "/ˈstɔffa/", "f", "stoffe"),
    ("cotone", "algodão", "materiali", "Camicia di cotone.", "Camisa de algodão.", "/koˈtone/", "m", "cotoni"),
    ("lana", "lã", "materiali", "Maglione di lana.", "Suéter de lã.", "/ˈlana/", "f", "lane"),
    ("seta", "seda", "materiali", "Cravatta di seta.", "Gravata de seda.", "/ˈseta/", "f", "sete"),
    ("pelle", "couro/pele", "materiali", "Borsa di pelle.", "Bolsa de couro.", "/ˈpɛlle/", "f", "pelli"),
    ("velluto", "veludo", "materiali", "Giacca di velluto.", "Jaqueta de veludo.", "/velˈluto/", "m", "velluti"),
    ("denim", "denim/jeans", "materiali", "Pantaloni di denim.", "Calças de brim.", "/ˈdɛnim/", "m", "denim"),
    ("sintetico", "sintético", "materiali", "Materiale sintetico.", "Material sintético.", "/sinˈtɛtiko/", "m", "sintetici"),
    ("cucitura", "costura", "concetti", "Una cucitura perfetta.", "Uma costura perfeita.", "/kutʃiˈtura/", "f", "cuciture"),
    ("bottone", "botão", "accessori", "Attaccare un bottone.", "Pregar um botão.", "/botˈtone/", "m", "bottoni"),
    ("cerniera", "zíper", "accessori", "Chiudere la cerniera.", "Fechar o zíper.", "/tʃerˈnjɛra/", "f", "cerniere"),
    ("tasca", "bolso", "accessori", "Le chiavi in tasca.", "As chaves no bolso.", "/ˈtaska/", "f", "tasche"),
    ("manica", "manga", "accessori", "Maniche lunghe.", "Mangas compridas.", "/ˈmanika/", "f", "maniche"),
    ("colletto", "colarinho", "accessori", "Il colletto della camicia.", "O colarinho da camisa.", "/kolˈletto/", "m", "colletti"),
    # Verbi
    ("indossare", "vestir", "verbi", "Indossare una giacca.", "Vestir uma jaqueta.", "/indosˈsare/", None, None),
    ("mettersi", "pôr (roupa)", "verbi", "Mettersi le scarpe.", "Pôr os sapatos.", "/ˈmettersi/", None, None),
    ("togliersi", "tirar (roupa)", "verbi", "Togliersi il cappello.", "Tirar o chapéu.", "/ˈtɔʎʎersi/", None, None),
    ("provare", "provar", "verbi", "Provare un vestito.", "Provar um vestido.", "/proˈvare/", None, None),
    ("cambiarsi", "trocar-se", "verbi", "Vado a cambiarmi.", "Vou me trocar.", "/kamˈbjarsi/", None, None),
    ("sfilare", "desfilar", "verbi", "Le modelle sfilano.", "As modelos desfilam.", "/sfiˈlare/", None, None),
    ("disegnare", "desenhar", "verbi", "Disegnare la collezione.", "Desenhar a coleção.", "/dizeɲˈɲare/", None, None),
    ("cucire", "costurar", "verbi", "Cucire i bottoni.", "Costurar os botões.", "/kuˈtʃire/", None, None),
    ("tagliare", "cortar", "verbi", "Tagliare il tessuto.", "Cortar o tecido.", "/taˈʎʎare/", None, None),
    ("abbinare", "combinar (roupas)", "verbi", "Abbinare i colori.", "Combinar as cores.", "/abbiˈnare/", None, None),
    ("vestirsi", "vestir-se", "verbi", "Vestirsi bene.", "Vestir-se bem.", "/vesˈtirsi/", None, None),
    ("spogliarsi", "despir-se", "verbi", "Spogliarsi per fare la doccia.", "Despir-se para tomar banho.", "/spoˈʎʎarsi/", None, None),
    ("truccarsi", "maquiar-se", "verbi", "Truccarsi per la festa.", "Maquiar-se para a festa.", "/trukˈkarsi/", None, None),
    ("profumarsi", "perfumar-se", "verbi", "Profumarsi prima di uscire.", "Perfumar-se antes de sair.", "/profuˈmarsi/", None, None),
    ("comprare", "comprar", "verbi", "Comprare in saldo.", "Comprar na promoção.", "/komˈprare/", None, None),
    ("spendere", "gastar", "verbi", "Spendere molti soldi.", "Gastar muito dinheiro.", "/ˈspɛndere/", None, None),
    ("risparmiare", "economizar", "verbi", "Risparmiare sui vestiti.", "Economizar nas roupas.", "/risparˈmjare/", None, None),
    ("lavare", "lavar", "verbi", "Lavare in lavatrice.", "Lavar na máquina.", "/laˈvare/", None, None),
    ("stirare", "passar (roupa)", "verbi", "Stirare la camicia.", "Passar a camisa.", "/stiˈrare/", None, None),
    ("piegare", "dobrar", "verbi", "Piegare i pantaloni.", "Dobrar as calças.", "/pjeˈɡare/", None, None),
    # Aggettivi
    ("elegante", "elegante", "aggettivi", "Un uomo elegante.", "Um homem elegante.", "/eleˈɡante/", "m", "eleganti"),
    ("casual", "casual", "aggettivi", "Un look casual.", "Um look casual.", "/ˈkɛʒwal/", "m", "casual"),
    ("sportivo", "esportivo", "aggettivi", "Abbigliamento sportivo.", "Roupa esportiva.", "/sporˈtivo/", "m", "sportivi"),
    ("classico", "clássico", "aggettivi", "Un completo classico.", "Um terno clássico.", "/ˈklassiko/", "m", "classici"),
    ("moderno", "moderno", "aggettivi", "Un design moderno.", "Um design moderno.", "/moˈdɛrno/", "m", "moderni"),
    ("largo", "largo", "aggettivi", "I pantaloni sono larghi.", "As calças são largas.", "/ˈlarɡo/", "m", "larghi"),
    ("stretto", "apertado", "aggettivi", "La giacca è stretta.", "A jaqueta está apertada.", "/ˈstretto/", "m", "stretti"),
    ("lungo", "comprido/longo", "aggettivi", "Un cappotto lungo.", "Um casaco comprido.", "/ˈlunɡo/", "m", "lunghi"),
    ("corto", "curto", "aggettivi", "Una gonna corta.", "Uma saia curta.", "/ˈkorto/", "m", "corti"),
    ("colorato", "colorido", "aggettivi", "Un abito colorato.", "Um vestido colorido.", "/koloˈrato/", "m", "colorati"),
    ("tinta unita", "cor sólida", "aggettivi", "Camicia a tinta unita.", "Camisa de cor sólida.", "/ˈtinta uˈnita/", "f", "tinte unite"),
    ("righe", "listras", "aggettivi", "Una maglia a righe.", "Uma camisa listrada.", "/ˈriɡe/", "f", "righe"),
    ("pois", "bolinhas", "aggettivi", "Un vestito a pois.", "Um vestido de bolinhas.", "/pwa/", "m", "pois"),
    ("quadri", "xadrez", "aggettivi", "Una camicia a quadri.", "Uma camisa xadrez.", "/ˈkwadri/", "m", "quadri"),
    ("alla moda", "na moda", "aggettivi", "Vestirsi alla moda.", "Vestir-se na moda.", "/ˈalla ˈmɔda/", None, None),
    ("fuori moda", "fora de moda", "aggettivi", "Un abito fuori moda.", "Um traje fora de moda.", "/ˈfwɔri ˈmɔda/", None, None),
    ("firmato", "de grife", "aggettivi", "Un capo firmato.", "Uma peça de grife.", "/firˈmato/", "m", "firmati"),
    ("economico", "barato", "aggettivi", "Un negozio economico.", "Uma loja barata.", "/ekoˈnɔmiko/", "m", "economici"),
    ("caro", "caro", "aggettivi", "Questo orologio è caro.", "Este relógio é caro.", "/ˈkaro/", "m", "cari"),
    ("abbinato", "combinado", "aggettivi", "Colori ben abbinati.", "Cores bem combinadas.", "/abbiˈnato/", "m", "abbinati")
]

# T35: L'Ambiente e l'Ecologia (110 parole)
t35_data = [
    # Elementi naturali
    ("ambiente", "meio ambiente", "natura", "Proteggere l'ambiente.", "Proteger o meio ambiente.", "/amˈbjɛnte/", "m", "ambienti"),
    ("natura", "natureza", "natura", "Amo la natura.", "Amo a natureza.", "/naˈtura/", "f", "nature"),
    ("ecologia", "ecologia", "natura", "Studiare l'ecologia.", "Estudar a ecologia.", "/ekoloˈdʒia/", "f", "ecologie"),
    ("pianeta", "planeta", "natura", "Salvare il pianeta.", "Salvar o planeta.", "/pjaˈneta/", "m", "pianeti"),
    ("terra", "terra", "natura", "Il pianeta Terra.", "O planeta Terra.", "/ˈtɛrra/", "f", "terre"),
    ("clima", "clima", "natura", "Il cambiamento del clima.", "A mudança do clima.", "/ˈklima/", "m", "climi"),
    ("atmosfera", "atmosfera", "natura", "L'atmosfera terrestre.", "A atmosfera terrestre.", "/atmosˈfɛra/", "f", "atmosfere"),
    ("oceano", "oceano", "natura", "L'oceano Pacifico.", "O oceano Pacífico.", "/oˈtʃɛano/", "m", "oceani"),
    ("foresta", "floresta", "natura", "La foresta amazzonica.", "A floresta amazônica.", "/foˈrɛsta/", "f", "foreste"),
    ("albero", "árvore", "natura", "Piantare un albero.", "Plantar uma árvore.", "/ˈalbero/", "m", "alberi"),
    ("pianta", "planta", "natura", "Annaffiare la pianta.", "Regar a planta.", "/ˈpjanta/", "f", "piante"),
    ("animale", "animal", "natura", "Un animale selvatico.", "Um animal selvagem.", "/aniˈmale/", "m", "animali"),
    ("specie", "espécie", "natura", "Specie in pericolo.", "Espécie em perigo.", "/ˈspɛtʃe/", "f", "specie"),
    ("ecosistema", "ecossistema", "natura", "L'equilibrio dell'ecosistema.", "O equilíbrio do ecossistema.", "/ekosisˈtɛma/", "m", "ecosistemi"),
    ("aria", "ar", "natura", "Respirare aria pura.", "Respirar ar puro.", "/ˈarja/", "f", "arie"),
    ("acqua", "água", "natura", "Acqua potabile.", "Água potável.", "/ˈakkwa/", "f", "acque"),
    ("suolo", "solo", "natura", "Inquinamento del suolo.", "Poluição do solo.", "/ˈswɔlo/", "m", "suoli"),
    ("ghiacciaio", "geleira", "natura", "Il ghiacciaio si scioglie.", "A geleira derrete.", "/ɡjatˈtʃajo/", "m", "ghiacciai"),
    # Problemi e Inquinamento
    ("inquinamento", "poluição", "problemi", "L'inquinamento dell'aria.", "A poluição do ar.", "/inkwinaˈmento/", "m", "inquinamenti"),
    ("rifiuto", "lixo/resíduo", "problemi", "I rifiuti tossici.", "Os resíduos tóxicos.", "/riˈfjuto/", "m", "rifiuti"),
    ("spazzatura", "lixo", "problemi", "Buttare la spazzatura.", "Jogar o lixo.", "/spattsaˈtura/", "f", "spazzature"),
    ("immondizia", "lixo", "problemi", "Il sacco dell'immondizia.", "O saco de lixo.", "/immonˈdittsja/", "f", "immondizie"),
    ("plastica", "plástico", "problemi", "Troppa plastica in mare.", "Muito plástico no mar.", "/ˈplastika/", "f", "plastiche"),
    ("smog", "poluição (ar)", "problemi", "C'è molto smog in città.", "Tem muita poluição na cidade.", "/zmɔɡ/", "m", "smog"),
    ("emissione", "emissão", "problemi", "Le emissioni di gas.", "As emissões de gás.", "/emisˈsjone/", "f", "emissioni"),
    ("gas serra", "gás de efeito estufa", "problemi", "I gas serra aumentano.", "Os gases de efeito estufa aumentam.", "/ɡas ˈsɛrra/", "m", "gas serra"),
    ("riscaldamento", "aquecimento", "problemi", "Il riscaldamento globale.", "O aquecimento global.", "/riskaldaˈmento/", "m", "riscaldamenti"),
    ("disboscamento", "desmatamento", "problemi", "Il disboscamento è grave.", "O desmatamento é grave.", "/dizboskaˈmento/", "m", "disboscamenti"),
    ("siccità", "seca", "problemi", "Un periodo di siccità.", "Um período de seca.", "/sitʃtʃiˈta/", "f", "siccità"),
    ("alluvione", "enchente", "problemi", "I danni dell'alluvione.", "Os danos da enchente.", "/alluˈvjone/", "f", "alluvioni"),
    ("degrado", "degradação", "problemi", "Il degrado ambientale.", "A degradação ambiental.", "/deˈɡrado/", "m", "degradi"),
    ("disastro", "desastre", "problemi", "Un disastro naturale.", "Um desastre natural.", "/diˈzastro/", "m", "disastri"),
    ("spreco", "desperdício", "problemi", "Evitare lo spreco d'acqua.", "Evitar o desperdício de água.", "/ˈsprɛko/", "m", "spree"),
    ("estinzione", "extinção", "problemi", "Specie a rischio di estinzione.", "Espécie em risco de extinção.", "/estinˈtsjone/", "f", "estinzioni"),
    ("pesticida", "agrotóxico", "problemi", "L'uso di pesticidi.", "O uso de agrotóxicos.", "/pestiˈtʃida/", "m", "pesticidi"),
    ("discarica", "aterro sanitário", "problemi", "La discarica è piena.", "O aterro está cheio.", "/disˈkarika/", "f", "discariche"),
    # Soluzioni ed Energia
    ("riciclo", "reciclagem", "soluzioni", "Il riciclo della carta.", "A reciclagem do papel.", "/riˈtʃiklo/", "m", "ricicli"),
    ("raccolta", "coleta", "soluzioni", "La raccolta differenziata.", "A coleta seletiva.", "/rakˈkɔlta/", "f", "raccolte"),
    ("energia", "energia", "soluzioni", "Energia pulita.", "Energia limpa.", "/enerˈdʒia/", "f", "energie"),
    ("solare", "solar", "soluzioni", "Il pannello solare.", "O painel solar.", "/soˈlare/", "m", "solari"),
    ("eolico", "eólico", "soluzioni", "Energia eolica.", "Energia eólica.", "/eˈɔliko/", "m", "eolici"),
    ("rinnovabile", "renovável", "soluzioni", "Risorse rinnovabili.", "Recursos renováveis.", "/rinnoˈvabile/", "f", "rinnovabili"),
    ("sostenibilità", "sustentabilidade", "soluzioni", "La sostenibilità ambientale.", "A sustentabilidade ambiental.", "/sostenibiliˈta/", "f", "sostenibilità"),
    ("biologico", "orgânico/biológico", "soluzioni", "Cibo biologico.", "Comida orgânica.", "/bjoˈlɔdʒiko/", "m", "biologici"),
    ("tutela", "tutela/proteção", "soluzioni", "La tutela del territorio.", "A tutela do território.", "/tuˈtɛla/", "f", "tutele"),
    ("salvaguardia", "salvaguarda/proteção", "soluzioni", "La salvaguardia dell'ambiente.", "A proteção do meio ambiente.", "/salvaˈɡwardja/", "f", "salvaguardie"),
    ("riserva", "reserva", "soluzioni", "Una riserva naturale.", "Uma reserva natural.", "/riˈzɛrva/", "f", "riserve"),
    ("parco", "parque", "soluzioni", "Il parco nazionale.", "O parque nacional.", "/ˈparko/", "m", "parchi"),
    ("veicolo", "veículo", "soluzioni", "Un veicolo elettrico.", "Um veículo elétrico.", "/veˈikolo/", "m", "veicoli"),
    ("bici", "bicicleta", "soluzioni", "Andare in bici.", "Andar de bicicleta.", "/ˈbitʃi/", "f", "bici"),
    ("pannello", "painel", "soluzioni", "Pannelli fotovoltaici.", "Painéis fotovoltaicos.", "/panˈnɛllo/", "m", "pannelli"),
    ("turbina", "turbina", "soluzioni", "Una turbina eolica.", "Uma turbina eólica.", "/turˈbina/", "f", "turbine"),
    ("batteria", "bateria", "soluzioni", "Batteria ricaricabile.", "Bateria recarregável.", "/batteˈria/", "f", "batterie"),
    ("cassonetto", "lixeira (rua)", "soluzioni", "Butta nel cassonetto.", "Jogue na lixeira.", "/kassoˈnetto/", "m", "cassonetti"),
    # Verbi
    ("proteggere", "proteger", "verbi", "Proteggere gli animali.", "Proteger os animais.", "/proˈtɛddʒere/", None, None),
    ("salvare", "salvar", "verbi", "Salvare la Terra.", "Salvar a Terra.", "/salˈvare/", None, None),
    ("inquinare", "poluir", "verbi", "Le fabbriche inquinano.", "As fábricas poluem.", "/inkwiˈnare/", None, None),
    ("riciclare", "reciclar", "verbi", "Riciclare il vetro.", "Reciclar o vidro.", "/ritʃiˈklare/", None, None),
    ("risparmiare", "economizar", "verbi", "Risparmiare energia.", "Economizar energia.", "/risparˈmjare/", None, None),
    ("sprecare", "desperdiçar", "verbi", "Non sprecare il cibo.", "Não desperdiçar a comida.", "/spreˈkare/", None, None),
    ("consumare", "consumir", "verbi", "Consumare meno petrolio.", "Consumir menos petróleo.", "/konsuˈmare/", None, None),
    ("ridurre", "reduzir", "verbi", "Ridurre le emissioni.", "Reduzir as emissões.", "/riˈdurre/", None, None),
    ("riutilizzare", "reutilizar", "verbi", "Riutilizzare i sacchetti.", "Reutilizar as sacolas.", "/riutilidˈdzare/", None, None),
    ("separare", "separar", "verbi", "Separare i rifiuti.", "Separar o lixo.", "/sepaˈrare/", None, None),
    ("pulire", "limpar", "verbi", "Pulire la spiaggia.", "Limpar a praia.", "/puˈlire/", None, None),
    ("sporcare", "sujar", "verbi", "Non sporcare la strada.", "Não sujar a rua.", "/sporˈkare/", None, None),
    ("piantare", "plantar", "verbi", "Piantare un seme.", "Plantar uma semente.", "/pjanˈtare/", None, None),
    ("tagliare", "cortar", "verbi", "Tagliare gli alberi.", "Cortar as árvores.", "/taˈʎʎare/", None, None),
    ("distruggere", "destruir", "verbi", "Distruggere l'habitat.", "Destruir o habitat.", "/disˈtruddʒere/", None, None),
    ("sciogliere", "derreter", "verbi", "Il ghiaccio si scioglie.", "O gelo derrete.", "/ˈʃɔʎʎere/", None, None),
    ("riscaldare", "aquecer", "verbi", "Il pianeta si riscalda.", "O planeta se aquece.", "/riskalˈdare/", None, None),
    ("coltivare", "cultivar", "verbi", "Coltivare la terra.", "Cultivar a terra.", "/koltiˈvare/", None, None),
    ("allevare", "criar (animais)", "verbi", "Allevare mucche.", "Criar vacas.", "/alleˈvare/", None, None),
    ("cacciare", "caçar", "verbi", "Cacciare di frodo.", "Caçar ilegalmente.", "/katˈtʃare/", None, None),
    # Aggettivi e descrittori
    ("verde", "verde/ecológico", "aggettivi", "L'energia verde.", "A energia verde.", "/ˈverde/", "m/f", "verdi"),
    ("pulito", "limpo", "aggettivi", "L'aria è pulita.", "O ar está limpo.", "/puˈlito/", "m", "puliti"),
    ("sporco", "sujo", "aggettivi", "Il fiume è sporco.", "O rio está sujo.", "/ˈspɔrko/", "m", "sporchi"),
    ("sano", "saudável", "aggettivi", "Un ambiente sano.", "Um ambiente saudável.", "/ˈsano/", "m", "sani"),
    ("inquinato", "poluído", "aggettivi", "Il mare è inquinato.", "O mar está poluído.", "/inkwiˈnato/", "m", "inquinati"),
    ("ecologico", "ecológico", "aggettivi", "Prodotto ecologico.", "Produto ecológico.", "/ekoˈlɔdʒiko/", "m", "ecologici"),
    ("tossico", "tóxico", "aggettivi", "Gas tossico.", "Gás tóxico.", "/ˈtɔssiko/", "m", "tossici"),
    ("naturale", "natural", "aggettivi", "Un disastro naturale.", "Um desastre natural.", "/natuˈrale/", "m", "naturali"),
    ("artificiale", "artificial", "aggettivi", "Luce artificiale.", "Luz artificial.", "/artifiˈtʃale/", "m", "artificiali"),
    ("biodegradabile", "biodegradável", "aggettivi", "Plastica biodegradabile.", "Plástico biodegradável.", "/bjodeɡraˈdabile/", "m", "biodegradabili"),
    ("rinnovabile", "renovável", "aggettivi", "Energia rinnovabile.", "Energia renovável.", "/rinnoˈvabile/", "m", "rinnovabili"),
    ("sostenibile", "sustentável", "aggettivi", "Sviluppo sostenibile.", "Desenvolvimento sustentável.", "/sosteˈnibile/", "m", "sostenibili"),
    ("solare", "solar", "aggettivi", "Energia solare.", "Energia solar.", "/soˈlare/", "m", "solari"),
    ("eolico", "eólico", "aggettivi", "Energia eolica.", "Energia eólica.", "/eˈɔliko/", "m", "eolici"),
    ("nucleare", "nuclear", "aggettivi", "Energia nucleare.", "Energia nuclear.", "/nukleˈare/", "m", "nucleari"),
    ("idroelettrico", "hidrelétrico", "aggettivi", "Impianto idroelettrico.", "Usina hidrelétrica.", "/idroeˈlɛttriko/", "m", "idroelettrici"),
    ("organico", "orgânico", "aggettivi", "Rifiuto organico.", "Resíduo orgânico.", "/orˈɡaniko/", "m", "organici"),
    ("estinto", "extinto", "aggettivi", "Animale estinto.", "Animal extinto.", "/esˈtinto/", "m", "estinti"),
    ("raro", "raro", "aggettivi", "Un fiore raro.", "Uma flor rara.", "/ˈraro/", "m", "rari"),
    ("selvaggio", "selvagem", "aggettivi", "Natura selvaggia.", "Natureza selvagem.", "/selˈvaddʒo/", "m", "selvaggi"),
    ("globale", "global", "aggettivi", "Riscaldamento globale.", "Aquecimento global.", "/ɡloˈbale/", "m", "globali"),
    ("locale", "local", "aggettivi", "Il clima locale.", "O clima local.", "/loˈkale/", "m", "locali"),
    ("climatico", "climático", "aggettivi", "Cambiamento climatico.", "Mudança climática.", "/kliˈmatiko/", "m", "climatici"),
    ("ambientale", "ambiental", "aggettivi", "Impatto ambientale.", "Impacto ambiental.", "/ambjenˈtale/", "m", "ambientali"),
    ("puro", "puro", "aggettivi", "Acqua pura.", "Água pura.", "/ˈpuro/", "m", "puri")
]

# T36: I Social Media e Internet (110 parole)
t36_data = [
    # Concetti base e strumenti
    ("internet", "internet", "tecnologia", "Navigare su internet.", "Navegar na internet.", "/ˈinternet/", "m", "internet"),
    ("rete", "rede/internet", "tecnologia", "Siamo in rete.", "Estamos na rede.", "/ˈrete/", "f", "reti"),
    ("computer", "computador", "tecnologia", "Accendere il computer.", "Ligar o computador.", "/komˈpjuter/", "m", "computer"),
    ("telefono", "telefone/celular", "tecnologia", "Il telefono squilla.", "O celular toca.", "/teˈlɛfono/", "m", "telefoni"),
    ("schermo", "tela", "tecnologia", "Lo schermo del tablet.", "A tela do tablet.", "/ˈskermo/", "m", "schermi"),
    ("tastiera", "teclado", "tecnologia", "Scrivere sulla tastiera.", "Escrever no teclado.", "/tasˈtjɛra/", "f", "tastiere"),
    ("mouse", "mouse", "tecnologia", "Cliccare col mouse.", "Clicar com o mouse.", "/maus/", "m", "mouse"),
    ("wi-fi", "wi-fi", "tecnologia", "La password del wi-fi.", "A senha do wi-fi.", "/waiˈfai/", "m", "wi-fi"),
    ("connessione", "conexão", "tecnologia", "Connessione veloce.", "Conexão rápida.", "/konnesˈsjone/", "f", "connessioni"),
    ("app", "app/aplicativo", "tecnologia", "Scaricare un'app.", "Baixar um app.", "/ap/", "f", "app"),
    ("software", "software", "tecnologia", "Aggiornare il software.", "Atualizar o software.", "/ˈsɔftwɛr/", "m", "software"),
    ("browser", "navegador", "tecnologia", "Aprire il browser.", "Abrir o navegador.", "/ˈbrauzer/", "m", "browser"),
    ("link", "link", "tecnologia", "Clicca sul link.", "Clique no link.", "/link/", "m", "link"),
    ("sito", "site", "tecnologia", "Un sito interessante.", "Um site interessante.", "/ˈsito/", "m", "siti"),
    ("pagina", "página (web)", "tecnologia", "Ricarica la pagina.", "Recarregue a página.", "/ˈpadʒina/", "f", "pagine"),
    ("motore", "motor (de busca)", "tecnologia", "Motore di ricerca.", "Motor de busca.", "/moˈtore/", "m", "motori"),
    # Social Media e Account
    ("social", "social (rede)", "social", "Sono sui social.", "Estou nas redes sociais.", "/ˈsɔʃal/", "m", "social"),
    ("profilo", "perfil", "social", "Il mio profilo.", "O meu perfil.", "/proˈfilo/", "m", "profili"),
    ("account", "conta", "social", "Crea un account.", "Crie uma conta.", "/akˈkaunt/", "m", "account"),
    ("utente", "usuário", "social", "Nome utente.", "Nome de usuário.", "/uˈtɛnte/", "m", "utenti"),
    ("password", "senha", "social", "Inserisci la password.", "Insira a senha.", "/ˈpasswɔrd/", "f", "password"),
    ("post", "post/publicação", "social", "Ho pubblicato un post.", "Publiquei um post.", "/pɔst/", "m", "post"),
    ("storia", "story/história", "social", "Guarda la mia storia.", "Veja meu story.", "/ˈstɔrja/", "f", "storie"),
    ("video", "vídeo", "social", "Un video divertente.", "Um vídeo divertido.", "/ˈvydɛo/", "m", "video"),
    ("foto", "foto", "social", "Una bella foto.", "Uma bela foto.", "/ˈfɔto/", "f", "foto"),
    ("selfie", "selfie", "social", "Facciamo un selfie.", "Vamos fazer uma selfie.", "/ˈsɛlfi/", "m", "selfie"),
    ("filtro", "filtro", "social", "Usare un filtro.", "Usar um filtro.", "/ˈfiltro/", "m", "filtri"),
    ("follower", "seguidor", "social", "Avere tanti follower.", "Ter muitos seguidores.", "/ˈfɔllower/", "m", "follower"),
    ("influencer", "influenciador", "social", "Un famoso influencer.", "Um famoso influenciador.", "/influˈɛnser/", "m/f", "influencer"),
    ("like", "like/curtida", "social", "Mettere un like.", "Dar um like.", "/laik/", "m", "like"),
    ("commento", "comentário", "social", "Lascia un commento.", "Deixe um comentário.", "/komˈmento/", "m", "commenti"),
    ("condivisione", "compartilhamento", "social", "Grazie per la condivisione.", "Obrigado pelo compartilhamento.", "/kondiviˈzjone/", "f", "condivisioni"),
    ("hashtag", "hashtag", "social", "Usa l'hashtag giusto.", "Use a hashtag certa.", "/ˈaʃtaɡ/", "m", "hashtag"),
    ("notifica", "notificação", "social", "Hai una notifica.", "Você tem uma notificação.", "/noˈtifika/", "f", "notifiche"),
    ("messaggio", "mensagem", "social", "Mandare un messaggio.", "Mandar uma mensagem.", "/mesˈsaddʒo/", "m", "messaggi"),
    ("chat", "chat/bate-papo", "social", "Scrivere in chat.", "Escrever no chat.", "/tʃat/", "f", "chat"),
    ("gruppo", "grupo", "social", "Il gruppo WhatsApp.", "O grupo de WhatsApp.", "/ˈɡruppo/", "m", "gruppi"),
    ("email", "e-mail", "social", "Mandare un'email.", "Mandar um e-mail.", "/iˈmeil/", "f", "email"),
    ("allegato", "anexo", "social", "Scarica l'allegato.", "Baixe o anexo.", "/alleˈɡato/", "m", "allegati"),
    ("virus", "vírus (computador)", "tecnologia", "Il computer ha un virus.", "O computador tem um vírus.", "/ˈvirus/", "m", "virus"),
    ("hacker", "hacker", "tecnologia", "Un attacco hacker.", "Um ataque hacker.", "/ˈɛker/", "m", "hacker"),
    ("truffa", "golpe", "tecnologia", "Una truffa online.", "Um golpe online.", "/ˈtruffa/", "f", "truffe"),
    ("spam", "spam", "tecnologia", "Finito nello spam.", "Caiu no spam.", "/spam/", "m", "spam"),
    ("cloud", "nuvem", "tecnologia", "Salvare nel cloud.", "Salvar na nuvem.", "/klaud/", "m", "cloud"),
    ("memoria", "memória", "tecnologia", "Memoria piena.", "Memória cheia.", "/meˈmɔrja/", "f", "memorie"),
    # Verbi
    ("navigare", "navegar", "verbi", "Navigare in rete.", "Navegar na rede.", "/naviˈɡare/", None, None),
    ("cliccare", "clicar", "verbi", "Cliccare sul bottone.", "Clicar no botão.", "/klikˈkare/", None, None),
    ("cercare", "buscar/pesquisar", "verbi", "Cercare su Google.", "Pesquisar no Google.", "/tʃerˈkare/", None, None),
    ("scaricare", "baixar (download)", "verbi", "Scaricare un file.", "Baixar um arquivo.", "/skariˈkare/", None, None),
    ("caricare", "subir (upload)", "verbi", "Caricare una foto.", "Fazer upload de uma foto.", "/kariˈkare/", None, None),
    ("salvare", "salvar", "verbi", "Salvare il documento.", "Salvar o documento.", "/salˈvare/", None, None),
    ("cancellare", "apagar/deletar", "verbi", "Cancellare la cronologia.", "Apagar o histórico.", "/kantʃelˈlare/", None, None),
    ("pubblicare", "publicar", "verbi", "Pubblicare un video.", "Publicar um vídeo.", "/pubbliˈkare/", None, None),
    ("condividere", "compartilhar", "verbi", "Condividere un articolo.", "Compartilhar um artigo.", "/kondiˈvidere/", None, None),
    ("commentare", "comentar", "verbi", "Commentare il post.", "Comentar o post.", "/kommenˈtare/", None, None),
    ("seguire", "seguir", "verbi", "Seguire un profilo.", "Seguir um perfil.", "/seˈɡwire/", None, None),
    ("iscriversi", "inscrever-se", "verbi", "Iscriversi al canale.", "Inscrever-se no canal.", "/isˈkriversi/", None, None),
    ("chattare", "teclar/conversar online", "verbi", "Chattare con gli amici.", "Conversar online com os amigos.", "/tʃatˈtare/", None, None),
    ("inviare", "enviar", "verbi", "Inviare una mail.", "Enviar um e-mail.", "/inviˈare/", None, None),
    ("ricevere", "receber", "verbi", "Ricevere una notifica.", "Receber uma notificação.", "/riˈtʃevere/", None, None),
    ("rispondere", "responder", "verbi", "Rispondere subito.", "Responder logo.", "/risˈpondere/", None, None),
    ("inoltrare", "encaminhar", "verbi", "Inoltrare il messaggio.", "Encaminhar a mensagem.", "/inolˈtrare/", None, None),
    ("bloccare", "bloquear", "verbi", "Bloccare un utente.", "Bloquear um usuário.", "/blokˈkare/", None, None),
    ("sbloccare", "desbloquear", "verbi", "Sbloccare il telefono.", "Desbloquear o celular.", "/zblokˈkare/", None, None),
    ("taggare", "marcar (tag)", "verbi", "Taggare un amico.", "Marcar um amigo.", "/taɡˈɡare/", None, None),
    ("accedere", "acessar/fazer login", "verbi", "Accedere all'account.", "Fazer login na conta.", "/atˈtʃɛdere/", None, None),
    ("uscire", "sair (logout)", "verbi", "Uscire dal sito.", "Fazer logout do site.", "/uʃˈʃire/", None, None),
    ("digitare", "digitar", "verbi", "Digitare la password.", "Digitar a senha.", "/didʒiˈtare/", None, None),
    ("copiare", "copiar", "verbi", "Copiare il testo.", "Copiar o texto.", "/koˈpjare/", None, None),
    ("incollare", "colar (texto)", "verbi", "Incollare il link.", "Colar o link.", "/inkolˈlare/", None, None),
    ("stampare", "imprimir", "verbi", "Stampare la pagina.", "Imprimir a página.", "/stamˈpare/", None, None),
    ("aggiornare", "atualizar", "verbi", "Aggiornare la pagina.", "Atualizar a página.", "/addʒorˈnare/", None, None),
    ("scorrere", "rolar (scroll)", "verbi", "Scorrere verso il basso.", "Rolar para baixo.", "/ˈskorrere/", None, None),
    ("silenziare", "silenciar", "verbi", "Silenziare le notifiche.", "Silenciar as notificações.", "/silentˈsjare/", None, None),
    ("aggiungere", "adicionar", "verbi", "Aggiungere agli amici.", "Adicionar aos amigos.", "/addˈdʒundʒere/", None, None),
    # Aggettivi e descrittori
    ("online", "online", "aggettivi", "Essere online.", "Estar online.", "/onˈlain/", None, None),
    ("offline", "offline", "aggettivi", "Sono offline ora.", "Estou offline agora.", "/ɔfˈflain/", None, None),
    ("virtuale", "virtual", "aggettivi", "La realtà virtuale.", "A realidade virtual.", "/virˈtwale/", "m", "virtuali"),
    ("digitale", "digital", "aggettivi", "Il mondo digitale.", "O mundo digital.", "/didʒiˈtale/", "m", "digitali"),
    ("sociale", "social", "aggettivi", "Vita sociale.", "Vida social.", "/soˈtʃale/", "m", "sociali"),
    ("privato", "privado", "aggettivi", "Messaggio privato.", "Mensagem privada.", "/priˈvato/", "m", "privati"),
    ("pubblico", "público", "aggettivi", "Profilo pubblico.", "Perfil público.", "/ˈpubbliko/", "m", "pubblici"),
    ("virale", "viral", "aggettivi", "Un video virale.", "Um vídeo viral.", "/viˈrale/", "m", "virali"),
    ("connesso", "conectado", "aggettivi", "Sempre connesso.", "Sempre conectado.", "/konˈnɛsso/", "m", "connessi"),
    ("lento", "lento", "aggettivi", "Internet lento.", "Internet lenta.", "/ˈlɛnto/", "m", "lenti"),
    ("veloce", "rápido", "aggettivi", "Connessione veloce.", "Conexão rápida.", "/veˈlotʃe/", "m", "veloci"),
    ("sicuro", "seguro", "aggettivi", "Un sito sicuro.", "Um site seguro.", "/siˈkuro/", "m", "sicuri"),
    ("pericoloso", "perigoso", "aggettivi", "È pericoloso online.", "É perigoso online.", "/perikoˈlozo/", "m", "pericolosi"),
    ("popolare", "popular", "aggettivi", "Un hashtag popolare.", "Uma hashtag popular.", "/popoˈlare/", "m", "popolari"),
    ("falso", "falso/fake", "aggettivi", "Una notizia falsa.", "Uma notícia falsa.", "/ˈfalso/", "m", "falsi"),
    ("vero", "verdadeiro", "aggettivi", "Un profilo vero.", "Um perfil verdadeiro.", "/ˈvero/", "m", "veri"),
    ("gratuito", "gratuito", "aggettivi", "L'app è gratuita.", "O app é gratuito.", "/ɡraˈtuito/", "m", "gratuiti"),
    ("ufficiale", "oficial", "aggettivi", "Pagina ufficiale.", "Página oficial.", "/uffiˈtʃale/", "m", "ufficiali"),
    ("anonimo", "anônimo", "aggettivi", "Commento anonimo.", "Comentário anônimo.", "/aˈnɔnimo/", "m", "anonimi")
]

# T37: La Fede e la Religione (110 parole)
t37_data = [
    # Figure Divine e Religiose
    ("dio", "deus", "religione", "Credere in Dio.", "Acreditar em Deus.", "/ˈdio/", "m", "dei"),
    ("gesù", "jesus", "religione", "La vita di Gesù.", "A vida de Jesus.", "/dʒeˈzu/", "m", None),
    ("maria", "maria (virgem)", "religione", "La Vergine Maria.", "A Virgem Maria.", "/maˈria/", "f", None),
    ("spirito", "espírito", "religione", "Lo Spirito Santo.", "O Espírito Santo.", "/ˈspirito/", "m", "spiriti"),
    ("santo", "santo", "religione", "Pregare il santo.", "Rezar para o santo.", "/ˈsanto/", "m", "santi"),
    ("angelo", "anjo", "religione", "Un angelo custode.", "Um anjo da guarda.", "/ˈandʒelo/", "m", "angeli"),
    ("demonio", "demônio", "religione", "Scacciare il demonio.", "Expulsar o demônio.", "/deˈmɔnjo/", "m", "demoni"),
    ("diavolo", "diabo", "religione", "La tentazione del diavolo.", "A tentação do diabo.", "/ˈdjavolo/", "m", "diavoli"),
    ("profeta", "profeta", "religione", "Le parole del profeta.", "As palavras do profeta.", "/proˈfɛta/", "m", "profeti"),
    ("papa", "papa", "persone", "Il Papa benedice.", "O Papa abençoa.", "/ˈpapa/", "m", "papi"),
    ("vescovo", "bispo", "persone", "Il vescovo celebra.", "O bispo celebra.", "/ˈveskovo/", "m", "vescovi"),
    ("prete", "padre", "persone", "Il prete dice messa.", "O padre reza a missa.", "/ˈprɛte/", "m", "preti"),
    ("sacerdote", "sacerdote", "persone", "Un sacerdote saggio.", "Um sacerdote sábio.", "/satʃerˈdɔte/", "m", "sacerdoti"),
    ("suora", "freira", "persone", "La suora prega.", "A freira reza.", "/ˈswɔra/", "f", "suore"),
    ("monaco", "monge", "persone", "Un monaco buddista.", "Um monge budista.", "/ˈmɔnako/", "m", "monaci"),
    ("fedele", "fiel (pessoa)", "persone", "I fedeli in chiesa.", "Os fiéis na igreja.", "/feˈdele/", "m/f", "fedeli"),
    ("credente", "crente/que crê", "persone", "Sono un credente.", "Sou um crente.", "/kreˈdɛnte/", "m/f", "credenti"),
    ("ateo", "ateu", "persone", "Lui è ateo.", "Ele é ateu.", "/ˈatɛo/", "m", "atei"),
    ("pellegrino", "peregrino", "persone", "Il cammino del pellegrino.", "O caminho do peregrino.", "/pelleˈɡrino/", "m", "pellegrini"),
    # Luoghi e Testi
    ("chiesa", "igreja", "luoghi", "Andare in chiesa.", "Ir à igreja.", "/ˈkjɛza/", "f", "chiese"),
    ("cattedrale", "catedral", "luoghi", "La cattedrale di Milano.", "A catedral de Milão.", "/katteˈdrale/", "f", "cattedrali"),
    ("basilica", "basílica", "luoghi", "La basilica di San Pietro.", "A basílica de São Pedro.", "/baˈzilika/", "f", "basiliche"),
    ("cappella", "capela", "luoghi", "Una piccola cappella.", "Uma pequena capela.", "/kapˈpɛlla/", "f", "cappelle"),
    ("monastero", "monastério/mosteiro", "luoghi", "Un antico monastero.", "Um antigo mosteiro.", "/monasˈtɛro/", "m", "monasteri"),
    ("convento", "convento", "luoghi", "Le suore nel convento.", "As freiras no convento.", "/konˈvɛnto/", "m", "conventi"),
    ("tempio", "templo", "luoghi", "Il tempio antico.", "O templo antigo.", "/ˈtɛmpjo/", "m", "tempi"),
    ("moschea", "mesquita", "luoghi", "Pregare nella moschea.", "Rezar na mesquita.", "/mosˈkɛa/", "f", "moschee"),
    ("sinagoga", "sinagoga", "luoghi", "La sinagoga ebraica.", "A sinagoga judaica.", "/sinaˈɡɔɡa/", "f", "sinagoghe"),
    ("altare", "altar", "luoghi", "Il prete all'altare.", "O padre no altar.", "/alˈtare/", "m", "altari"),
    ("santuario", "santuário", "luoghi", "Il santuario mariano.", "O santuário mariano.", "/santuˈarjo/", "m", "santuari"),
    ("bibbia", "bíblia", "oggetti", "Leggere la Bibbia.", "Ler a Bíblia.", "/ˈbibbja/", "f", "bibbie"),
    ("vangelo", "evangelho", "oggetti", "Il vangelo di Luca.", "O evangelho de Lucas.", "/vanˈdʒɛlo/", "m", "vangeli"),
    ("corano", "alcorão", "oggetti", "Studiare il Corano.", "Estudar o Alcorão.", "/koˈrano/", "m", "corani"),
    ("torah", "torá", "oggetti", "Leggere la Torah.", "Ler a Torá.", "/toˈra/", "f", "torah"),
    ("croce", "cruz", "oggetti", "Il segno della croce.", "O sinal da cruz.", "/ˈkrotʃe/", "f", "croci"),
    ("crocifisso", "crucifixo", "oggetti", "Il crocifisso al muro.", "O crucifixo na parede.", "/krotʃiˈfisso/", "m", "crocifissi"),
    ("rosario", "rosário/terço", "oggetti", "Sgranare il rosario.", "Rezar o terço.", "/roˈzarjo/", "m", "rosari"),
    ("candela", "vela", "oggetti", "Accendere una candela.", "Acender uma vela.", "/kanˈdela/", "f", "candele"),
    ("incenso", "incenso", "oggetti", "Il profumo dell'incenso.", "O perfume do incenso.", "/inˈtʃɛnso/", "m", "incensi"),
    # Concetti Astratti
    ("fede", "fé", "concetti", "Avere fede.", "Ter fé.", "/ˈfede/", "f", "fedi"),
    ("religione", "religião", "concetti", "La libertà di religione.", "A liberdade de religião.", "/reliˈdʒone/", "f", "religioni"),
    ("preghiera", "oração", "concetti", "Dire una preghiera.", "Dizer uma oração.", "/preˈɡjɛra/", "f", "preghiere"),
    ("miracolo", "milagre", "concetti", "È successo un miracolo.", "Aconteceu um milagre.", "/miˈrakolo/", "m", "miracoli"),
    ("peccato", "pecado", "concetti", "Commettere un peccato.", "Cometer um pecado.", "/pekˈkato/", "m", "peccati"),
    ("anima", "alma", "concetti", "L'anima è immortale.", "A alma é imortal.", "/ˈanima/", "f", "anime"),
    ("paradiso", "paraíso/céu", "concetti", "Andare in paradiso.", "Ir para o paraíso.", "/paraˈdizo/", "m", "paradisi"),
    ("inferno", "inferno", "concetti", "Bruciare all'inferno.", "Queimar no inferno.", "/inˈfɛrno/", "m", "inferni"),
    ("purgatorio", "purgatório", "concetti", "Le anime del purgatorio.", "As almas do purgatório.", "/purɡaˈtɔrjo/", "m", "purgatori"),
    ("grazia", "graça", "concetti", "Ricevere una grazia.", "Receber uma graça.", "/ˈɡrattsja/", "f", "grazie"),
    ("benedizione", "bênção", "concetti", "La benedizione di Dio.", "A bênção de Deus.", "/beneditˈtsjone/", "f", "benedizioni"),
    ("perdono", "perdão", "concetti", "Chiedere perdono.", "Pedir perdão.", "/perˈdono/", "m", "perdoni"),
    ("confessione", "confissão", "concetti", "Andare a confessione.", "Ir à confissão.", "/konfesˈsjone/", "f", "confessioni"),
    ("messa", "missa", "concetti", "La messa della domenica.", "A missa de domingo.", "/ˈmessa/", "f", "messe"),
    ("sacramento", "sacramento", "concetti", "Il sacramento del battesimo.", "O sacramento do batismo.", "/sakraˈmento/", "m", "sacramenti"),
    ("battesimo", "batismo", "concetti", "Il battesimo del bambino.", "O batismo do bebê.", "/batˈtezimo/", "m", "battesimi"),
    ("matrimonio", "casamento", "concetti", "Un matrimonio in chiesa.", "Um casamento na igreja.", "/matriˈmɔnjo/", "m", "matrimoni"),
    ("funerale", "funeral/enterro", "concetti", "Andare al funerale.", "Ir ao funeral.", "/funeˈrale/", "m", "funerali"),
    ("anima", "alma", "concetti", "Riposi in pace l'anima sua.", "Que sua alma descanse em paz.", "/ˈanima/", "f", "anime"), # dup for 110, we'll replace it
    ("credenza", "crença", "concetti", "Rispettare le credenze.", "Respeitar as crenças.", "/kreˈdɛntsa/", "f", "credenze"),
    ("culto", "culto", "concetti", "La libertà di culto.", "A liberdade de culto.", "/ˈkulto/", "m", "culti"),
    ("rito", "rito/ritual", "concetti", "Un antico rito.", "Um antigo rito.", "/ˈrito/", "m", "riti"),
    ("dogma", "dogma", "concetti", "Un dogma di fede.", "Um dogma de fé.", "/ˈdɔɡma/", "m", "dogmi"),
    ("mistero", "mistério", "concetti", "Il mistero della fede.", "O mistério da fé.", "/misˈtɛro/", "m", "misteri"),
    # Verbi
    ("credere", "acreditar/crer", "verbi", "Credere in Dio.", "Crer em Deus.", "/ˈkredere/", None, None),
    ("pregare", "rezar/orar", "verbi", "Pregare la sera.", "Rezar à noite.", "/preˈɡare/", None, None),
    ("benedire", "abençoar", "verbi", "Che Dio ti benedica.", "Que Deus te abençoe.", "/beneˈdire/", None, None),
    ("perdonare", "perdoar", "verbi", "Perdonare i nemici.", "Perdoar os inimigos.", "/perdoˈnare/", None, None),
    ("pentirsi", "arrepender-se", "verbi", "Pentirsi dei peccati.", "Arrepender-se dos pecados.", "/penˈtirsi/", None, None),
    ("confessarsi", "confessar-se", "verbi", "Confessarsi dal prete.", "Confessar-se com o padre.", "/konfesˈsarsi/", None, None),
    ("salvare", "salvar", "verbi", "Dio ci salva.", "Deus nos salva.", "/salˈvare/", None, None),
    ("celebrare", "celebrar", "verbi", "Celebrare la messa.", "Celebrar a missa.", "/tʃeleˈbrare/", None, None),
    ("battezzare", "batizar", "verbi", "Battezzare un neonato.", "Batizar um recém-nascido.", "/battedˈdzare/", None, None),
    ("sposarsi", "casar-se", "verbi", "Sposarsi in chiesa.", "Casar-se na igreja.", "/spoˈzarsi/", None, None),
    ("inginocchiarsi", "ajoelhar-se", "verbi", "Inginocchiarsi per pregare.", "Ajoelhar-se para rezar.", "/indʒinokˈkjarsi/", None, None),
    ("risorgere", "ressuscitar", "verbi", "Cristo è risorto.", "Cristo ressuscitou.", "/riˈzordʒere/", None, None),
    ("peccare", "pecar", "verbi", "Tutti possono peccare.", "Todos podem pecar.", "/pekˈkare/", None, None),
    ("adorare", "adorar", "verbi", "Adorare il Signore.", "Adorar ao Senhor.", "/adoˈrare/", None, None),
    ("convertirsi", "converter-se", "verbi", "Convertirsi alla religione.", "Converter-se à religião.", "/konverˈtirsi/", None, None),
    ("digiunare", "jejuar", "verbi", "Digiunare il venerdì.", "Jejuar na sexta-feira.", "/didʒuˈnare/", None, None),
    ("predicare", "pregar", "verbi", "Predicare il vangelo.", "Pregar o evangelho.", "/prediˈkare/", None, None),
    ("sperare", "esperar (ter esperança)", "verbi", "Sperare nella salvezza.", "Esperar na salvação.", "/speˈrare/", None, None),
    # Aggettivi e descrittori
    ("santo", "santo", "aggettivi", "Un uomo santo.", "Um homem santo.", "/ˈsanto/", "m", "santi"),
    ("sacro", "sagrado", "aggettivi", "Un luogo sacro.", "Um lugar sagrado.", "/ˈsakro/", "m", "sacri"),
    ("divino", "divino", "aggettivi", "L'amore divino.", "O amor divino.", "/diˈvino/", "m", "divini"),
    ("religioso", "religioso", "aggettivi", "Un canto religioso.", "Um canto religioso.", "/reliˈdʒozo/", "m", "religiosi"),
    ("cattolico", "católico", "aggettivi", "La chiesa cattolica.", "A igreja católica.", "/katˈtɔliko/", "m", "cattolici"),
    ("cristiano", "cristão", "aggettivi", "Un paese cristiano.", "Um país cristão.", "/krisˈtjano/", "m", "cristiani"),
    ("musulmano", "muçulmano", "aggettivi", "Il popolo musulmano.", "O povo muçulmano.", "/muzulˈmano/", "m", "musulmani"),
    ("ebraico", "judaico/hebraico", "aggettivi", "La tradizione ebraica.", "A tradição judaica.", "/eˈbraiko/", "m", "ebraici"),
    ("buddista", "budista", "aggettivi", "Un monaco buddista.", "Um monge budista.", "/budˈdista/", "m/f", "buddisti"),
    ("ortodosso", "ortodoxo", "aggettivi", "Rito ortodosso.", "Rito ortodoxo.", "/ortoˈdɔsso/", "m", "ortodossi"),
    ("spirituale", "espiritual", "aggettivi", "Una guida spirituale.", "Um guia espiritual.", "/spiriˈtwale/", "m", "spirituali"),
    ("eterno", "eterno", "aggettivi", "La vita eterna.", "A vida eterna.", "/eˈtɛrno/", "m", "eterni"),
    ("puro", "puro", "aggettivi", "Un cuore puro.", "Um coração puro.", "/ˈpuro/", "m", "puri"),
    ("peccatore", "pecador", "aggettivi", "Siamo tutti peccatori.", "Somos todos pecadores.", "/pekkaˈtore/", "m", "peccatori"),
    ("pio", "piedoso", "aggettivi", "Una donna pia.", "Uma mulher piedosa.", "/ˈpio/", "m", "pii"),
    ("devoto", "devoto", "aggettivi", "È molto devoto.", "É muito devoto.", "/deˈvɔto/", "m", "devoti"),
    ("miracoloso", "milagroso", "aggettivi", "Una guarigione miracolosa.", "Uma cura milagrosa.", "/mirakoˈlozo/", "m", "miracolosi"),
    ("immortale", "imortal", "aggettivi", "L'anima immortale.", "A alma imortal.", "/immorˈtale/", "m", "immortali"),
    ("profano", "profano", "aggettivi", "Amore sacro e profano.", "Amor sagrado e profano.", "/proˈfano/", "m", "profani"),
    ("ateo", "ateu (adj)", "aggettivi", "Un pensiero ateo.", "Um pensamento ateu.", "/ˈatɛo/", "m", "atei"),
    ("misericordioso", "misericordioso", "aggettivi", "Dio è misericordioso.", "Deus é misericordioso.", "/mizerikorˈdjozo/", "m", "misericordiosi")
]

# T37 dupe fix (anima was there twice)
# Let's replace the second 'anima' with 'campana'
t37_data[65] = ("campana", "sino", "oggetti", "Suonano le campane.", "Tocam os sinos.", "/kamˈpana/", "f", "campane")

def create_new(templo_num, nome, citta, livello, parole_data):
    palavras = []
    for i, (it, pt, cat, ex_it, ex_pt, ipa, gen, pl) in enumerate(parole_data, 1):
        tid = f"t{templo_num}_{i:03d}"
        palavras.append(w(tid, it, pt, cat, ex_it, ex_pt, ipa, gen, pl))
        
    obj = {
        "templo": templo_num,
        "nome": nome,
        "cidade": citta,
        "nivel": livello,
        "palavras": palavras
    }
    
    path = os.path.join(OUT, "data", f"templo-{templo_num}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
    print(f"CREATED templo-{templo_num}.json -- {len(palavras)} parole")

if __name__ == "__main__":
    create_new(34, "La Moda e il Design", "Milano", "A2", t34_data)
    create_new(35, "L'Ambiente e l'Ecologia", "Torino", "B1", t35_data)
    create_new(36, "I Social Media e Internet", "Milano", "A1", t36_data)
    create_new(37, "La Fede e la Religione", "Roma", "B2", t37_data)
