import json, sys
sys.stdout.reconfigure(encoding='utf-8')

d = json.load(open('data/storie.json', encoding='utf-8'))
storie = d['storie']

# Fix 1: stor_003 missing descricao
for s in storie:
    if s['id'] == 'stor_003':
        s['descricao'] = "Il celebre romanzo di Carlo Collodi: le avventure di un burattino che sogna di diventare un bambino vero."
        s['descricao_pt'] = "O célebre romance de Carlo Collodi: as aventuras de um boneco que sonha em se tornar um menino de verdade."
        print("Fix stor_003: descricao adicionada")

# Fix 2: Remove stor_011 (duplicata Inferno Canto I = mesmo que stor_008)
antes = len(storie)
storie = [s for s in storie if s['id'] != 'stor_011']
print(f"Removida stor_011 (duplicata): {antes} -> {len(storie)}")

# Novas histórias
novas = [
  {
    "id": "stor_013",
    "titulo": "Una Giornata a Roma",
    "titulo_pt": "Um Dia em Roma",
    "nivel": "A2",
    "icone": "🏛️",
    "autor": "Racconto didattico",
    "tema": "viaggio",
    "descricao": "Marco, uno studente brasiliano, trascorre una giornata indimenticabile nella città eterna.",
    "descricao_pt": "Marco, um estudante brasileiro, passa um dia inesquecível na cidade eterna.",
    "xp_recompensa": 70,
    "testo": [
      {"id":"stor_013_p1","italiano":"Marco arriva a Roma in treno. La stazione Termini è grande e piena di gente. Lui cerca l'uscita principale e poi prende la metropolitana.","portugues":"Marco chega a Roma de trem. A estação Termini é grande e cheia de gente. Ele procura a saída principal e depois pega o metrô.",
       "parole":[{"parola":"arriva","traduzione":"chega","ipa":"/arˈriːva/","categoria":"verbo"},{"parola":"stazione","traduzione":"estação","ipa":"/statˈtsjoːne/","categoria":"sostantivo"},{"parola":"grande","traduzione":"grande","ipa":"/ˈɡrande/","categoria":"aggettivo"},{"parola":"metropolitana","traduzione":"metrô","ipa":"/metropoliˈtaːna/","categoria":"sostantivo"}]},
      {"id":"stor_013_p2","italiano":"La prima tappa è il Colosseo. Marco vede l'anfiteatro romano e rimane senza parole. È bellissimo e molto antico.","portugues":"A primeira parada é o Coliseu. Marco vê o anfiteatro romano e fica sem palavras. É belíssimo e muito antigo.",
       "parole":[{"parola":"tappa","traduzione":"parada/etapa","ipa":"/ˈtappa/","categoria":"sostantivo"},{"parola":"anfiteatro","traduzione":"anfiteatro","ipa":"/anfiteˈaːtro/","categoria":"sostantivo"},{"parola":"bellissimo","traduzione":"belíssimo","ipa":"/belˈlissimo/","categoria":"aggettivo"},{"parola":"antico","traduzione":"antigo","ipa":"/anˈtiːko/","categoria":"aggettivo"}]},
      {"id":"stor_013_p3","italiano":"Dopo il Colosseo, Marco cammina verso il Foro Romano. Qui ci sono le rovine degli antichi edifici romani. Una guida spiega la storia del luogo.","portugues":"Depois do Coliseu, Marco caminha em direção ao Foro Romano. Aqui há as ruínas dos antigos edifícios romanos. Um guia explica a história do lugar.",
       "parole":[{"parola":"rovine","traduzione":"ruínas","ipa":"/roˈviːne/","categoria":"sostantivo"},{"parola":"edifici","traduzione":"edifícios","ipa":"/ediˈfiːtʃi/","categoria":"sostantivo"},{"parola":"guida","traduzione":"guia","ipa":"/ˈɡwiːda/","categoria":"sostantivo"},{"parola":"spiega","traduzione":"explica","ipa":"/ˈspjɛːɡa/","categoria":"verbo"}]},
      {"id":"stor_013_p4","italiano":"A mezzogiorno Marco ha fame. Va in una trattoria vicino al Pantheon. Ordina una pasta all'amatriciana e un bicchiere di acqua naturale.","portugues":"Ao meio-dia Marco está com fome. Vai a uma trattoria perto do Panteão. Pede uma massa all'amatriciana e um copo de água sem gás.",
       "parole":[{"parola":"trattoria","traduzione":"restaurante típico","ipa":"/trattoria/","categoria":"sostantivo"},{"parola":"ordina","traduzione":"pede/encomenda","ipa":"/ˈɔrdina/","categoria":"verbo"},{"parola":"bicchiere","traduzione":"copo","ipa":"/bikˈkjɛːre/","categoria":"sostantivo"},{"parola":"naturale","traduzione":"natural/sem gás","ipa":"/natuˈraːle/","categoria":"aggettivo"}]},
      {"id":"stor_013_p5","italiano":"Il cibo è delizioso. Il cameriere è gentile e parla un po' di inglese. Il conto è ragionevole per il centro di Roma.","portugues":"A comida é deliciosa. O garçom é gentil e fala um pouco de inglês. A conta é razoável para o centro de Roma.",
       "parole":[{"parola":"delizioso","traduzione":"delicioso","ipa":"/deliˈtsjoso/","categoria":"aggettivo"},{"parola":"cameriere","traduzione":"garçom","ipa":"/kameˈrjɛːre/","categoria":"sostantivo"},{"parola":"gentile","traduzione":"gentil","ipa":"/dʒenˈtiːle/","categoria":"aggettivo"},{"parola":"conto","traduzione":"conta","ipa":"/ˈkonto/","categoria":"sostantivo"}]},
      {"id":"stor_013_p6","italiano":"Nel pomeriggio, Marco visita il Pantheon. L'edificio ha quasi duemila anni ed è in ottimo stato. La cupola è impressionante.","portugues":"À tarde, Marco visita o Panteão. O edifício tem quase dois mil anos e está em ótimo estado. A cúpula é impressionante.",
       "parole":[{"parola":"pomeriggio","traduzione":"tarde","ipa":"/pomeˈriddʒo/","categoria":"sostantivo"},{"parola":"cupola","traduzione":"cúpula","ipa":"/ˈkuːpola/","categoria":"sostantivo"},{"parola":"impressionante","traduzione":"impressionante","ipa":"/impressjoˈnante/","categoria":"aggettivo"},{"parola":"edificio","traduzione":"edifício","ipa":"/ediˈfiːtʃo/","categoria":"sostantivo"}]},
      {"id":"stor_013_p7","italiano":"Poi Marco va a Piazza Navona. Ci sono tre fontane magnifiche. La più famosa è la Fontana dei Quattro Fiumi, opera di Gian Lorenzo Bernini.","portugues":"Depois Marco vai à Piazza Navona. Há três fontes magníficas. A mais famosa é a Fontana dei Quattro Fiumi, obra de Gian Lorenzo Bernini.",
       "parole":[{"parola":"fontana","traduzione":"fonte","ipa":"/fonˈtaːna/","categoria":"sostantivo"},{"parola":"magnifica","traduzione":"magnífica","ipa":"/maɲˈɲiːfika/","categoria":"aggettivo"},{"parola":"opera","traduzione":"obra","ipa":"/ˈɔːpera/","categoria":"sostantivo"},{"parola":"piazza","traduzione":"praça","ipa":"/ˈpjattsa/","categoria":"sostantivo"}]},
      {"id":"stor_013_p8","italiano":"Marco lancia una moneta nella Fontana di Trevi. Si dice che chi lancia una moneta tornerà a Roma. Lui sorride e fa un desiderio.","portugues":"Marco joga uma moeda na Fontana di Trevi. Diz-se que quem joga uma moeda voltará a Roma. Ele sorri e faz um desejo.",
       "parole":[{"parola":"lancia","traduzione":"joga/lança","ipa":"/ˈlantʃa/","categoria":"verbo"},{"parola":"moneta","traduzione":"moeda","ipa":"/moˈnɛːta/","categoria":"sostantivo"},{"parola":"desiderio","traduzione":"desejo","ipa":"/deziˈdɛːrjo/","categoria":"sostantivo"},{"parola":"sorride","traduzione":"sorri","ipa":"/sorˈriːde/","categoria":"verbo"}]},
      {"id":"stor_013_p9","italiano":"La sera, Marco sale sulla collina del Gianicolo. Da lassù si vede tutta Roma al tramonto. I tetti arancioni brillano nella luce dorata.","portugues":"À noite, Marco sobe à colina do Gianicolo. De lá se vê toda Roma ao pôr do sol. Os telhados alaranjados brilham na luz dourada.",
       "parole":[{"parola":"collina","traduzione":"colina","ipa":"/kolˈliːna/","categoria":"sostantivo"},{"parola":"tramonto","traduzione":"pôr do sol","ipa":"/traˈmonto/","categoria":"sostantivo"},{"parola":"tetti","traduzione":"telhados","ipa":"/ˈtetti/","categoria":"sostantivo"},{"parola":"brillano","traduzione":"brilham","ipa":"/ˈbrillano/","categoria":"verbo"}]},
      {"id":"stor_013_p10","italiano":"È stata una giornata meravigliosa. Marco torna in albergo stanco ma felice. Domani partirà per Firenze, la prossima tappa del suo viaggio in Italia.","portugues":"Foi um dia maravilhoso. Marco volta ao hotel cansado mas feliz. Amanhã partirá para Florença, a próxima parada de sua viagem pela Itália.",
       "parole":[{"parola":"meravigliosa","traduzione":"maravilhosa","ipa":"/meraviˈʎoːza/","categoria":"aggettivo"},{"parola":"albergo","traduzione":"hotel","ipa":"/alˈbɛrɡo/","categoria":"sostantivo"},{"parola":"stanco","traduzione":"cansado","ipa":"/ˈstaŋko/","categoria":"aggettivo"},{"parola":"partirà","traduzione":"partirá","ipa":"/partiˈra/","categoria":"verbo"}]}
    ]
  },
  {
    "id": "stor_014",
    "titulo": "San Francesco e il Lupo di Gubbio",
    "titulo_pt": "São Francisco e o Lobo de Gubbio",
    "nivel": "B1",
    "icone": "🐺",
    "autor": "Leggenda italiana",
    "tema": "leggenda",
    "descricao": "Una delle leggende più amate d'Italia: San Francesco d'Assisi addomestica un lupo feroce che terrorizzava la città di Gubbio.",
    "descricao_pt": "Uma das lendas mais amadas da Itália: São Francisco de Assis domestica um lobo feroz que aterrorizava a cidade de Gubbio.",
    "xp_recompensa": 85,
    "testo": [
      {"id":"stor_014_p1","italiano":"Molti secoli fa, nella città umbra di Gubbio, viveva un lupo enorme e feroce. La bestia attaccava gli animali domestici e perfino gli uomini. I cittadini avevano paura di uscire dalla città.","portugues":"Muitos séculos atrás, na cidade úmbria de Gubbio, vivia um lobo enorme e feroz. A fera atacava os animais domésticos e até os homens. Os cidadãos tinham medo de sair da cidade.",
       "parole":[{"parola":"feroce","traduzione":"feroz","ipa":"/feˈroːtʃe/","categoria":"aggettivo"},{"parola":"bestia","traduzione":"fera","ipa":"/ˈbɛstja/","categoria":"sostantivo"},{"parola":"attaccava","traduzione":"atacava","ipa":"/attakˈkaːva/","categoria":"verbo"},{"parola":"cittadini","traduzione":"cidadãos","ipa":"/tʃittaˈdiːni/","categoria":"sostantivo"}]},
      {"id":"stor_014_p2","italiano":"Un giorno, Francesco d'Assisi arrivò a Gubbio. Sapeva della terribile situazione. Decise di andare incontro al lupo, anche se tutti cercavano di fermarlo.","portugues":"Um dia, Francisco de Assis chegou a Gubbio. Sabia da terrível situação. Decidiu ir ao encontro do lobo, mesmo que todos tentassem detê-lo.",
       "parole":[{"parola":"terribile","traduzione":"terrível","ipa":"/terˈriːbile/","categoria":"aggettivo"},{"parola":"decise","traduzione":"decidiu","ipa":"/deˈtʃiːze/","categoria":"verbo"},{"parola":"incontro","traduzione":"encontro","ipa":"/iŋˈkontro/","categoria":"sostantivo"},{"parola":"fermarlo","traduzione":"detê-lo","ipa":"/ferˈmarlo/","categoria":"verbo"}]},
      {"id":"stor_014_p3","italiano":"Francesco uscì dalla porta della città da solo. I cittadini lo guardavano dalla cima delle mura, pieni di timore. Il lupo apparve subito, correndo verso di lui a gran velocità.","portugues":"Francisco saiu da porta da cidade sozinho. Os cidadãos o observavam do alto das muralhas, cheios de temor. O lobo apareceu logo, correndo em direção a ele em grande velocidade.",
       "parole":[{"parola":"mura","traduzione":"muralhas","ipa":"/ˈmuːra/","categoria":"sostantivo"},{"parola":"timore","traduzione":"temor","ipa":"/tiˈmoːre/","categoria":"sostantivo"},{"parola":"apparve","traduzione":"apareceu","ipa":"/apˈparve/","categoria":"verbo"},{"parola":"velocità","traduzione":"velocidade","ipa":"/veloˈtʃita/","categoria":"sostantivo"}]},
      {"id":"stor_014_p4","italiano":"Francesco levò la mano e disse: Vieni qui, fratello lupo. Ti comando di non fare del male a nessuno. Il lupo si fermò e abbassò la testa.","portugues":"Francisco levantou a mão e disse: Vem aqui, irmão lobo. Ordeno-te que não faças mal a ninguém. O lobo parou e abaixou a cabeça.",
       "parole":[{"parola":"levò","traduzione":"levantou","ipa":"/leˈvɔ/","categoria":"verbo"},{"parola":"fratello","traduzione":"irmão","ipa":"/fraˈtɛllo/","categoria":"sostantivo"},{"parola":"comando","traduzione":"ordeno","ipa":"/koˈmando/","categoria":"verbo"},{"parola":"abbassò","traduzione":"abaixou","ipa":"/abbassˈɔ/","categoria":"verbo"}]},
      {"id":"stor_014_p5","italiano":"Il lupo si avvicinò a Francesco come un agnello mansueto. Il santo gli accarezzò la testa. Tutti i presenti erano stupefatti e commossi.","portugues":"O lobo aproximou-se de Francisco como um cordeiro manso. O santo acariciou sua cabeça. Todos os presentes ficaram estupefatos e comovidos.",
       "parole":[{"parola":"agnello","traduzione":"cordeiro","ipa":"/aɲˈɲɛllo/","categoria":"sostantivo"},{"parola":"mansueto","traduzione":"manso","ipa":"/manˈswɛːto/","categoria":"aggettivo"},{"parola":"accarezzò","traduzione":"acariciou","ipa":"/akkaretˈtsɔ/","categoria":"verbo"},{"parola":"commossi","traduzione":"comovidos","ipa":"/komˈmɔssi/","categoria":"aggettivo"}]},
      {"id":"stor_014_p6","italiano":"Francesco parlò al lupo con dolcezza: Fratello, tu hai fatto molto male. Ma ora farai pace con questi uomini. Loro ti daranno il cibo ogni giorno.","portugues":"Francisco falou ao lobo com suavidade: Irmão, tu fizeste muito mal. Mas agora farás paz com estes homens. Eles te darão comida todo dia.",
       "parole":[{"parola":"dolcezza","traduzione":"suavidade/doçura","ipa":"/dolˈtʃettsa/","categoria":"sostantivo"},{"parola":"pace","traduzione":"paz","ipa":"/ˈpaːtʃe/","categoria":"sostantivo"},{"parola":"cibo","traduzione":"comida","ipa":"/ˈtʃiːbo/","categoria":"sostantivo"},{"parola":"ogni","traduzione":"cada/todo","ipa":"/ˈoɲɲi/","categoria":"aggettivo"}]},
      {"id":"stor_014_p7","italiano":"Il lupo mosse la testa su e giù, come per dire di sì. Poi pose la zampa destra nella mano di Francesco, come segno di accordo. Era il patto tra il lupo e la città.","portugues":"O lobo moveu a cabeça para cima e para baixo, como para dizer sim. Depois colocou a pata direita na mão de Francisco, como sinal de acordo. Era o pacto entre o lobo e a cidade.",
       "parole":[{"parola":"zampa","traduzione":"pata","ipa":"/ˈdzampa/","categoria":"sostantivo"},{"parola":"segno","traduzione":"sinal","ipa":"/ˈseɲɲo/","categoria":"sostantivo"},{"parola":"accordo","traduzione":"acordo","ipa":"/akˈkɔrdo/","categoria":"sostantivo"},{"parola":"patto","traduzione":"pacto","ipa":"/ˈpatto/","categoria":"sostantivo"}]},
      {"id":"stor_014_p8","italiano":"Francesco rientrò in città con il lupo accanto. I cittadini erano meravigliati. I bambini uscirono per vedere il lupo, che ora sembrava un cane domestico.","portugues":"Francisco retornou à cidade com o lobo ao lado. Os cidadãos ficaram maravilhados. As crianças saíram para ver o lobo, que agora parecia um cão doméstico.",
       "parole":[{"parola":"meravigliati","traduzione":"maravilhados","ipa":"/meraviˈʎaːti/","categoria":"aggettivo"},{"parola":"sembrava","traduzione":"parecia","ipa":"/semˈbraːva/","categoria":"verbo"},{"parola":"domestico","traduzione":"doméstico","ipa":"/doˈmɛstiko/","categoria":"aggettivo"},{"parola":"accanto","traduzione":"ao lado","ipa":"/akˈkanto/","categoria":"avverbio"}]},
      {"id":"stor_014_p9","italiano":"Da quel giorno, il lupo visse a Gubbio per due anni. Girava per le strade senza fare del male a nessuno. Le famiglie lo nutrivano con amore e lui proteggeva la città.","portugues":"Daquele dia, o lobo viveu em Gubbio por dois anos. Circulava pelas ruas sem fazer mal a ninguém. As famílias o alimentavam com amor e ele protegia a cidade.",
       "parole":[{"parola":"girava","traduzione":"circulava","ipa":"/dʒiˈraːva/","categoria":"verbo"},{"parola":"nutrivano","traduzione":"alimentavam","ipa":"/nutriˈvaːno/","categoria":"verbo"},{"parola":"proteggeva","traduzione":"protegia","ipa":"/proteˈdʒɛːva/","categoria":"verbo"},{"parola":"strade","traduzione":"ruas","ipa":"/ˈstraːde/","categoria":"sostantivo"}]},
      {"id":"stor_014_p10","italiano":"Quando il lupo morì, i cittadini di Gubbio piansero. Avevano perso un amico fedele. Ancora oggi, la leggenda di San Francesco e il lupo è viva nel cuore degli italiani.","portugues":"Quando o lobo morreu, os cidadãos de Gubbio choraram. Haviam perdido um amigo fiel. Ainda hoje, a lenda de São Francisco e o lobo está viva no coração dos italianos.",
       "parole":[{"parola":"piansero","traduzione":"choraram","ipa":"/ˈpjansero/","categoria":"verbo"},{"parola":"fedele","traduzione":"fiel","ipa":"/feˈdɛːle/","categoria":"aggettivo"},{"parola":"leggenda","traduzione":"lenda","ipa":"/ledˈdʒɛnda/","categoria":"sostantivo"},{"parola":"cuore","traduzione":"coração","ipa":"/ˈkwɔːre/","categoria":"sostantivo"}]}
    ]
  },
  {
    "id": "stor_015",
    "titulo": "La Vita di Leonardo da Vinci",
    "titulo_pt": "A Vida de Leonardo da Vinci",
    "nivel": "B2",
    "icone": "🎨",
    "autor": "Racconto storico",
    "tema": "storia",
    "descricao": "La straordinaria vita del genio universale italiano: pittore, scultore, scienziato e inventore del Rinascimento.",
    "descricao_pt": "A extraordinária vida do gênio universal italiano: pintor, escultor, cientista e inventor do Renascimento.",
    "xp_recompensa": 95,
    "testo": [
      {"id":"stor_015_p1","italiano":"Leonardo da Vinci nacque il 15 aprile 1452 ad Anchiano, un piccolo borgo vicino a Vinci, in Toscana. Era figlio illegittimo del notaio Ser Piero da Vinci e di una contadina di nome Caterina.","portugues":"Leonardo da Vinci nasceu em 15 de abril de 1452 em Anchiano, uma pequena aldeia perto de Vinci, na Toscana. Era filho ilegítimo do notário Ser Piero da Vinci e de uma camponesa chamada Caterina.",
       "parole":[{"parola":"illegittimo","traduzione":"ilegítimo","ipa":"/illedˈdʒittimo/","categoria":"aggettivo"},{"parola":"notaio","traduzione":"notário","ipa":"/noˈtaːjo/","categoria":"sostantivo"},{"parola":"contadina","traduzione":"camponesa","ipa":"/kontaˈdiːna/","categoria":"sostantivo"},{"parola":"borgo","traduzione":"aldeia/vilarejo","ipa":"/ˈborɡo/","categoria":"sostantivo"}]},
      {"id":"stor_015_p2","italiano":"Da bambino, Leonardo mostrava un talento straordinario per il disegno. Il padre lo portò a Firenze e lo affidò alla bottega del pittore Andrea del Verrocchio, uno dei migliori artisti dell'epoca.","portugues":"Desde criança, Leonardo mostrava um talento extraordinário para o desenho. O pai o levou a Florença e o confiou à oficina do pintor Andrea del Verrocchio, um dos melhores artistas da época.",
       "parole":[{"parola":"talento","traduzione":"talento","ipa":"/taˈlɛnto/","categoria":"sostantivo"},{"parola":"bottega","traduzione":"oficina/ateliê","ipa":"/botˈtɛːɡa/","categoria":"sostantivo"},{"parola":"affidò","traduzione":"confiou","ipa":"/affiˈdɔ/","categoria":"verbo"},{"parola":"epoca","traduzione":"época","ipa":"/ˈɛːpoka/","categoria":"sostantivo"}]},
      {"id":"stor_015_p3","italiano":"Nella bottega del Verrocchio, Leonardo imparò la pittura, la scultura, l'architettura e l'ingegneria. Il suo maestro rimase stupito dal talento del giovane apprendista.","portugues":"Na oficina de Verrocchio, Leonardo aprendeu pintura, escultura, arquitetura e engenharia. Seu mestre ficou impressionado com o talento do jovem aprendiz.",
       "parole":[{"parola":"scultura","traduzione":"escultura","ipa":"/skulˈtuːra/","categoria":"sostantivo"},{"parola":"architettura","traduzione":"arquitetura","ipa":"/arkitetˈtuːra/","categoria":"sostantivo"},{"parola":"ingegneria","traduzione":"engenharia","ipa":"/indʒeɲˈɲɛːrja/","categoria":"sostantivo"},{"parola":"apprendista","traduzione":"aprendiz","ipa":"/apprɛnˈdista/","categoria":"sostantivo"}]},
      {"id":"stor_015_p4","italiano":"A Milano, Leonardo realizzò l'Ultima Cena, uno dei dipinti più famosi della storia dell'arte. Il dipinto si trova ancora oggi nel refettorio della chiesa di Santa Maria delle Grazie.","portugues":"Em Milão, Leonardo realizou A Última Ceia, um dos quadros mais famosos da história da arte. O quadro ainda se encontra hoje no refeitório da igreja de Santa Maria delle Grazie.",
       "parole":[{"parola":"refettorio","traduzione":"refeitório","ipa":"/refetˈtɔːrjo/","categoria":"sostantivo"},{"parola":"chiesa","traduzione":"igreja","ipa":"/ˈkjɛːza/","categoria":"sostantivo"},{"parola":"dipinto","traduzione":"quadro/pintura","ipa":"/diˈpinto/","categoria":"sostantivo"},{"parola":"realizzò","traduzione":"realizou","ipa":"/realitˈtsɔ/","categoria":"verbo"}]},
      {"id":"stor_015_p5","italiano":"Leonardo non era solo pittore. Studiava anatomia, botanica, geologia, matematica e astronomia. Riempiva migliaia di fogli con disegni e appunti scritti al contrario, da destra a sinistra.","portugues":"Leonardo não era apenas pintor. Estudava anatomia, botânica, geologia, matemática e astronomia. Enchia milhares de folhas com desenhos e notas escritas ao contrário, da direita para a esquerda.",
       "parole":[{"parola":"anatomia","traduzione":"anatomia","ipa":"/anatoˈmiːa/","categoria":"sostantivo"},{"parola":"appunti","traduzione":"notas/apontamentos","ipa":"/apˈpunti/","categoria":"sostantivo"},{"parola":"contrario","traduzione":"contrário","ipa":"/konˈtraːrjo/","categoria":"aggettivo"},{"parola":"riempiva","traduzione":"enchia","ipa":"/rjemˈpiːva/","categoria":"verbo"}]},
      {"id":"stor_015_p6","italiano":"Tra le sue invenzioni ci sono macchine volanti, carri armati, pompe idrauliche e ponti mobili. Molte delle sue idee erano così avanzate che il mondo non era ancora pronto per realizzarle.","portugues":"Entre suas invenções estão máquinas voadoras, tanques de guerra, bombas hidráulicas e pontes móveis. Muitas de suas ideias eram tão avançadas que o mundo ainda não estava pronto para realizá-las.",
       "parole":[{"parola":"invenzioni","traduzione":"invenções","ipa":"/inventˈtsjoːni/","categoria":"sostantivo"},{"parola":"volanti","traduzione":"voadoras","ipa":"/voˈlanti/","categoria":"aggettivo"},{"parola":"idrauliche","traduzione":"hidráulicas","ipa":"/idˈrauːlike/","categoria":"aggettivo"},{"parola":"avanzate","traduzione":"avançadas","ipa":"/avanˈtsaːte/","categoria":"aggettivo"}]},
      {"id":"stor_015_p7","italiano":"Tra il 1503 e il 1519, Leonardo dipinse la Gioconda, forse il ritratto più famoso del mondo. Il sorriso enigmatico di Monna Lisa ha affascinato generazioni di osservatori e ancora oggi rimane un mistero.","portugues":"Entre 1503 e 1519, Leonardo pintou a Gioconda, talvez o retrato mais famoso do mundo. O sorriso enigmático de Mona Lisa tem fascinado gerações de observadores e ainda hoje permanece um mistério.",
       "parole":[{"parola":"ritratto","traduzione":"retrato","ipa":"/riˈtratto/","categoria":"sostantivo"},{"parola":"enigmatico","traduzione":"enigmático","ipa":"/eniɡˈmaːtiko/","categoria":"aggettivo"},{"parola":"affascinato","traduzione":"fascinado","ipa":"/affaʃʃiˈnaːto/","categoria":"aggettivo"},{"parola":"mistero","traduzione":"mistério","ipa":"/misˈtɛːro/","categoria":"sostantivo"}]},
      {"id":"stor_015_p8","italiano":"Negli ultimi anni della sua vita, Leonardo lavorò in Francia, ospite del re Francesco I nel castello di Cloux. Il re francese lo ammirava profondamente e lo chiamava il suo amico più caro.","portugues":"Nos últimos anos de sua vida, Leonardo trabalhou na França, hóspede do rei Francisco I no castelo de Cloux. O rei francês o admirava profundamente e o chamava de seu amigo mais querido.",
       "parole":[{"parola":"ospite","traduzione":"hóspede","ipa":"/ˈɔspite/","categoria":"sostantivo"},{"parola":"castello","traduzione":"castelo","ipa":"/kasˈtɛllo/","categoria":"sostantivo"},{"parola":"ammirava","traduzione":"admirava","ipa":"/ammiˈraːva/","categoria":"verbo"},{"parola":"profondamente","traduzione":"profundamente","ipa":"/profondaˈmente/","categoria":"avverbio"}]},
      {"id":"stor_015_p9","italiano":"Leonardo da Vinci morì il 2 maggio 1519, all'età di sessantasette anni. Lasciò al mondo un'eredità immensa: dipinti immortali, migliaia di pagine di note scientifiche e un esempio straordinario di mente umana.","portugues":"Leonardo da Vinci morreu em 2 de maio de 1519, aos sessenta e sete anos. Deixou ao mundo uma herança imensa: pinturas imortais, milhares de páginas de notas científicas e um exemplo extraordinário de mente humana.",
       "parole":[{"parola":"eredità","traduzione":"herança","ipa":"/ereˈdita/","categoria":"sostantivo"},{"parola":"immortali","traduzione":"imortais","ipa":"/immortˈtaːli/","categoria":"aggettivo"},{"parola":"scientifiche","traduzione":"científicas","ipa":"/ʃʃenˈtiːfike/","categoria":"aggettivo"},{"parola":"esempio","traduzione":"exemplo","ipa":"/eˈzɛmpjo/","categoria":"sostantivo"}]}
    ]
  },
  {
    "id": "stor_016",
    "titulo": "Il Palio di Siena",
    "titulo_pt": "O Palio de Siena",
    "nivel": "B2",
    "icone": "🐎",
    "autor": "Racconto storico",
    "tema": "tradizione",
    "descricao": "La storia e le leggende della corsa di cavalli più famosa d'Italia, che si tiene due volte l'anno nella magnifica Piazza del Campo.",
    "descricao_pt": "A história e as lendas da corrida de cavalos mais famosa da Itália, realizada duas vezes ao ano na magnífica Piazza del Campo.",
    "xp_recompensa": 90,
    "testo": [
      {"id":"stor_016_p1","italiano":"Il Palio di Siena è una delle tradizioni più antiche e spettacolari d'Italia. Si tratta di una corsa di cavalli che si svolge due volte l'anno nella magnifica Piazza del Campo, nel cuore della città medievale di Siena.","portugues":"O Palio de Siena é uma das tradições mais antigas e espetaculares da Itália. Trata-se de uma corrida de cavalos que ocorre duas vezes ao ano na magnífica Piazza del Campo, no coração da cidade medieval de Siena.",
       "parole":[{"parola":"corsa","traduzione":"corrida","ipa":"/ˈkorsa/","categoria":"sostantivo"},{"parola":"spettacolari","traduzione":"espetaculares","ipa":"/spettakoˈlaːri/","categoria":"aggettivo"},{"parola":"medievale","traduzione":"medieval","ipa":"/medjeˈvaːle/","categoria":"aggettivo"},{"parola":"svolge","traduzione":"ocorre/realiza-se","ipa":"/zˈvɔldʒe/","categoria":"verbo"}]},
      {"id":"stor_016_p2","italiano":"Siena è divisa in diciassette contrade, cioè quartieri storici con una propria identità e tradizione. Ogni contrada ha il proprio simbolo animale: la Tartuca, l'Aquila, il Drago, il Liocorno e molte altre.","portugues":"Siena é dividida em dezessete contrade, ou seja, bairros históricos com identidade e tradição próprias. Cada contrada tem seu próprio símbolo animal: a Tartaruga, a Águia, o Dragão, o Unicórnio e muitos outros.",
       "parole":[{"parola":"contrade","traduzione":"bairros históricos","ipa":"/konˈtraːde/","categoria":"sostantivo"},{"parola":"identità","traduzione":"identidade","ipa":"/identiˈta/","categoria":"sostantivo"},{"parola":"simbolo","traduzione":"símbolo","ipa":"/ˈsimbolo/","categoria":"sostantivo"},{"parola":"Liocorno","traduzione":"Unicórnio","ipa":"/ljoˈkorno/","categoria":"sostantivo"}]},
      {"id":"stor_016_p3","italiano":"Al Palio partecipano solo dieci delle diciassette contrade. La scelta avviene tramite sorteggio. I contradaioli esclusi soffrono molto per non poter partecipare alla corsa più importante dell'anno.","portugues":"No Palio participam apenas dez das dezessete contrade. A escolha ocorre por sorteio. Os moradores das contrade excluídas sofrem muito por não poder participar da corrida mais importante do ano.",
       "parole":[{"parola":"sorteggio","traduzione":"sorteio","ipa":"/sorˈtɛddʒo/","categoria":"sostantivo"},{"parola":"contradaioli","traduzione":"moradores da contrada","ipa":"/kontraˈdaːjoli/","categoria":"sostantivo"},{"parola":"soffrono","traduzione":"sofrem","ipa":"/ˈsɔffrono/","categoria":"verbo"},{"parola":"esclusi","traduzione":"excluídos","ipa":"/esˈkluːzi/","categoria":"aggettivo"}]},
      {"id":"stor_016_p4","italiano":"Il giorno del Palio, la piazza è trasformata in una pista di terra battuta. Ottantamila spettatori si affollano nel Campo. La tensione è altissima e ogni contradaiolo ha il cuore in gola.","portugues":"No dia do Palio, a praça é transformada em uma pista de terra batida. Oitenta mil espectadores se aglomeram no Campo. A tensão é altíssima e cada morador da contrada tem o coração na garganta.",
       "parole":[{"parola":"pista","traduzione":"pista","ipa":"/ˈpista/","categoria":"sostantivo"},{"parola":"spettatori","traduzione":"espectadores","ipa":"/spettatˈtoːri/","categoria":"sostantivo"},{"parola":"tensione","traduzione":"tensão","ipa":"/tenˈsjoːne/","categoria":"sostantivo"},{"parola":"affollano","traduzione":"aglomeram-se","ipa":"/affolˈlaːno/","categoria":"verbo"}]},
      {"id":"stor_016_p5","italiano":"Prima della corsa, ha luogo la sfilata storica. Figuranti in costumi medievali sfilano in corteo solenne. Vengono esibiti gli stendardi delle contrade e il Palio, il drappo dipinto che sarà il premio del vincitore.","portugues":"Antes da corrida, ocorre o desfile histórico. Figurantes em trajes medievais desfilam em cortejo solene. São exibidos os estandartes das contrade e o Palio, o pano pintado que será o prêmio do vencedor.",
       "parole":[{"parola":"sfilata","traduzione":"desfile","ipa":"/sfiˈlaːta/","categoria":"sostantivo"},{"parola":"figuranti","traduzione":"figurantes","ipa":"/fiɡuˈranti/","categoria":"sostantivo"},{"parola":"stendardi","traduzione":"estandartes","ipa":"/stenˈdaːrdi/","categoria":"sostantivo"},{"parola":"drappo","traduzione":"pano/estandarte","ipa":"/ˈdrappo/","categoria":"sostantivo"}]},
      {"id":"stor_016_p6","italiano":"La corsa dura solo novanta secondi, ma è il momento più intenso dell'anno senese. I cavalli corrono tre volte intorno alla piazza. Cadute e scontri tra i fantini sono frequenti e consentiti dal regolamento.","portugues":"A corrida dura apenas noventa segundos, mas é o momento mais intenso do ano sienês. Os cavalos correm três vezes ao redor da praça. Quedas e choques entre os jóqueis são frequentes e permitidos pelo regulamento.",
       "parole":[{"parola":"fantini","traduzione":"jóqueis","ipa":"/fanˈtiːni/","categoria":"sostantivo"},{"parola":"cadute","traduzione":"quedas","ipa":"/kaˈduːte/","categoria":"sostantivo"},{"parola":"scontri","traduzione":"choques/confrontos","ipa":"/ˈskontri/","categoria":"sostantivo"},{"parola":"regolamento","traduzione":"regulamento","ipa":"/reɡolaˈmento/","categoria":"sostantivo"}]},
      {"id":"stor_016_p7","italiano":"Una particolarità del Palio è che può vincere anche il cavallo senza il fantino. Se il cavallo arriva primo senza il suo cavaliere, la vittoria è ugualmente valida per la contrada.","portugues":"Uma particularidade do Palio é que pode ganhar também o cavalo sem o jóquei. Se o cavalo chegar primeiro sem seu cavaleiro, a vitória é igualmente válida para a contrada.",
       "parole":[{"parola":"particolarità","traduzione":"particularidade","ipa":"/partikolariˈta/","categoria":"sostantivo"},{"parola":"cavaliere","traduzione":"cavaleiro","ipa":"/kavalˈjɛːre/","categoria":"sostantivo"},{"parola":"vittoria","traduzione":"vitória","ipa":"/vitˈtɔːrja/","categoria":"sostantivo"},{"parola":"valida","traduzione":"válida","ipa":"/ˈvaːlida/","categoria":"aggettivo"}]},
      {"id":"stor_016_p8","italiano":"La vittoria scatena una gioia incontenibile nella contrada vincitrice. I contradaioli si abbracciano, piangono e cantano. La festa può durare giorni interi. I bambini crescono con il Palio nel sangue.","portugues":"A vitória desencadeia uma alegria incontível na contrada vencedora. Os moradores se abraçam, choram e cantam. A festa pode durar dias inteiros. As crianças crescem com o Palio no sangue.",
       "parole":[{"parola":"scatena","traduzione":"desencadeia","ipa":"/skaˈtɛːna/","categoria":"verbo"},{"parola":"incontenibile","traduzione":"incontível","ipa":"/inkonteniˈbiːle/","categoria":"aggettivo"},{"parola":"abbracciano","traduzione":"abraçam-se","ipa":"/abˈbratʃano/","categoria":"verbo"},{"parola":"crescono","traduzione":"crescem","ipa":"/ˈkrɛʃʃono/","categoria":"verbo"}]},
      {"id":"stor_016_p9","italiano":"Per i senesi, il Palio non è solo una corsa: è identità, storia e passione. È il modo in cui questa città medievale mantiene viva la sua anima, anno dopo anno, secolo dopo secolo.","portugues":"Para os sienenses, o Palio não é apenas uma corrida: é identidade, história e paixão. É a maneira pela qual esta cidade medieval mantém viva sua alma, ano após ano, século após século.",
       "parole":[{"parola":"identità","traduzione":"identidade","ipa":"/identiˈta/","categoria":"sostantivo"},{"parola":"passione","traduzione":"paixão","ipa":"/pasˈsjoːne/","categoria":"sostantivo"},{"parola":"mantiene","traduzione":"mantém","ipa":"/manˈtjɛːne/","categoria":"verbo"},{"parola":"anima","traduzione":"alma","ipa":"/ˈaːnima/","categoria":"sostantivo"}]}
    ]
  },
  {
    "id": "stor_017",
    "titulo": "La Leggenda della Befana",
    "titulo_pt": "A Lenda da Befana",
    "nivel": "A2",
    "icone": "🧙",
    "autor": "Tradizione italiana",
    "tema": "tradizione",
    "descricao": "La storia della vecchina volante che porta doni ai bambini italiani la notte del 5 gennaio, una tradizione tipicamente italiana.",
    "descricao_pt": "A história da velhinha voadora que traz presentes para as crianças italianas na noite de 5 de janeiro, uma tradição tipicamente italiana.",
    "xp_recompensa": 65,
    "testo": [
      {"id":"stor_017_p1","italiano":"In Italia c'è una tradizione molto speciale: la Befana. La Befana è una vecchina gentile che vola su una scopa magica. Porta i doni ai bambini la notte del 5 gennaio.","portugues":"Na Itália há uma tradição muito especial: a Befana. A Befana é uma velhinha gentil que voa em uma vassoura mágica. Traz presentes para as crianças na noite de 5 de janeiro.",
       "parole":[{"parola":"vecchina","traduzione":"velhinha","ipa":"/vekˈkiːna/","categoria":"sostantivo"},{"parola":"scopa","traduzione":"vassoura","ipa":"/ˈskoːpa/","categoria":"sostantivo"},{"parola":"doni","traduzione":"presentes","ipa":"/ˈdoːni/","categoria":"sostantivo"},{"parola":"magica","traduzione":"mágica","ipa":"/ˈmaːdʒika/","categoria":"aggettivo"}]},
      {"id":"stor_017_p2","italiano":"Secondo la leggenda, i Re Magi invitarono la Befana a portare doni al Gesù Bambino. Lei disse di sì, ma poi rimase a casa a fare le pulizie. Quando uscì, non trovò più i Re Magi e si perse.","portugues":"Segundo a lenda, os Reis Magos convidaram a Befana para levar presentes ao Menino Jesus. Ela disse sim, mas depois ficou em casa fazendo a limpeza. Quando saiu, não encontrou mais os Reis Magos e se perdeu.",
       "parole":[{"parola":"leggenda","traduzione":"lenda","ipa":"/ledˈdʒɛnda/","categoria":"sostantivo"},{"parola":"pulizie","traduzione":"limpeza","ipa":"/puˈliːtsje/","categoria":"sostantivo"},{"parola":"invitarono","traduzione":"convidaram","ipa":"/invitˈaːrono/","categoria":"verbo"},{"parola":"rimase","traduzione":"ficou/permaneceu","ipa":"/riˈmaːze/","categoria":"verbo"}]},
      {"id":"stor_017_p3","italiano":"La Befana cercò il bambino da sola. Si fermava in ogni casa con un bambino dentro e lasciava doni per tutti, sperando che uno fosse il Gesù Bambino. Da allora, visita ogni casa ogni anno.","portugues":"A Befana procurou o menino sozinha. Parava em cada casa com uma criança dentro e deixava presentes para todos, esperando que uma fosse o Menino Jesus. Desde então, visita cada casa todo ano.",
       "parole":[{"parola":"cercò","traduzione":"procurou","ipa":"/tʃerˈkɔ/","categoria":"verbo"},{"parola":"lasciava","traduzione":"deixava","ipa":"/laˈʃʃaːva/","categoria":"verbo"},{"parola":"sperando","traduzione":"esperando","ipa":"/speˈrando/","categoria":"verbo"},{"parola":"allora","traduzione":"então","ipa":"/alˈloːra/","categoria":"avverbio"}]},
      {"id":"stor_017_p4","italiano":"Ancora oggi, la notte del 5 gennaio, i bambini italiani appendono una calza al camino o vicino alla finestra. Se sono stati bravi, trovano dolci e regali. Se sono stati cattivi, trovano il carbone.","portugues":"Ainda hoje, na noite de 5 de janeiro, as crianças italianas penduam uma meia na lareira ou perto da janela. Se foram bons, encontram doces e presentes. Se foram maus, encontram carvão.",
       "parole":[{"parola":"calza","traduzione":"meia","ipa":"/ˈkaltsa/","categoria":"sostantivo"},{"parola":"camino","traduzione":"lareira","ipa":"/kaˈmiːno/","categoria":"sostantivo"},{"parola":"carbone","traduzione":"carvão","ipa":"/karˈboːne/","categoria":"sostantivo"},{"parola":"appendono","traduzione":"penduam","ipa":"/apˈpɛndono/","categoria":"verbo"}]},
      {"id":"stor_017_p5","italiano":"La Befana veste abiti vecchi e porta un cappello a punta. Ha il viso rugoso e il naso lungo. Nonostante il suo aspetto un po' spaventoso, è una figura amata da tutti i bambini italiani.","portugues":"A Befana veste roupas velhas e usa um chapéu pontudo. Tem o rosto enrugado e o nariz comprido. Apesar de sua aparência um pouco assustadora, é uma figura amada por todas as crianças italianas.",
       "parole":[{"parola":"rugoso","traduzione":"enrugado","ipa":"/ruˈɡoːzo/","categoria":"aggettivo"},{"parola":"cappello","traduzione":"chapéu","ipa":"/kapˈpɛllo/","categoria":"sostantivo"},{"parola":"aspetto","traduzione":"aparência","ipa":"/asˈpɛtto/","categoria":"sostantivo"},{"parola":"spaventoso","traduzione":"assustador","ipa":"/spavɛnˈtoːzo/","categoria":"aggettivo"}]},
      {"id":"stor_017_p6","italiano":"Il 6 gennaio si chiama Festa dell'Epifania. È un giorno di festa in tutta Italia. In molte città ci sono sfilate e spettacoli con la Befana protagonista. I bambini aspettano questo giorno con grande gioia.","portugues":"O dia 6 de janeiro se chama Festa dell'Epifania. É um dia de festa em toda a Itália. Em muitas cidades há desfiles e espetáculos com a Befana como protagonista. As crianças esperam esse dia com grande alegria.",
       "parole":[{"parola":"Epifania","traduzione":"Epifania","ipa":"/epiˈfaːnja/","categoria":"sostantivo"},{"parola":"sfilate","traduzione":"desfiles","ipa":"/sfiˈlaːte/","categoria":"sostantivo"},{"parola":"spettacoli","traduzione":"espetáculos","ipa":"/spetˈtaːkoli/","categoria":"sostantivo"},{"parola":"gioia","traduzione":"alegria","ipa":"/ˈdʒɔːja/","categoria":"sostantivo"}]},
      {"id":"stor_017_p7","italiano":"C'è anche un detto popolare italiano: L'Epifania tutte le feste porta via. Significa che dopo il 6 gennaio, il periodo delle feste natalizie è finito e si torna alla vita normale.","portugues":"Há também um ditado popular italiano: A Epifania leva todas as festas embora. Significa que depois de 6 de janeiro, o período das festas natalinas acabou e se volta à vida normal.",
       "parole":[{"parola":"detto","traduzione":"ditado","ipa":"/ˈdetto/","categoria":"sostantivo"},{"parola":"popolare","traduzione":"popular","ipa":"/popoˈlaːre/","categoria":"aggettivo"},{"parola":"natalizie","traduzione":"natalinas","ipa":"/nataˈliːtsje/","categoria":"aggettivo"},{"parola":"normale","traduzione":"normal","ipa":"/norˈmaːle/","categoria":"aggettivo"}]},
      {"id":"stor_017_p8","italiano":"Oggi la tradizione della Befana è viva in tutta Italia. I bambini amano questa figura magica e attendono con ansia la notte del 5 gennaio, proprio come aspettano Babbo Natale il 25 dicembre.","portugues":"Hoje a tradição da Befana está viva em toda a Itália. As crianças amam essa figura mágica e aguardam ansiosamente a noite de 5 de janeiro, assim como esperam o Papai Noel no dia 25 de dezembro.",
       "parole":[{"parola":"attendono","traduzione":"aguardam","ipa":"/atˈtɛndono/","categoria":"verbo"},{"parola":"ansia","traduzione":"ansiedade","ipa":"/ˈansja/","categoria":"sostantivo"},{"parola":"Babbo Natale","traduzione":"Papai Noel","ipa":"/ˈbabbo naˈtaːle/","categoria":"sostantivo"},{"parola":"tradizione","traduzione":"tradição","ipa":"/traditˈtsjoːne/","categoria":"sostantivo"}]}
    ]
  },
  {
    "id": "stor_018",
    "titulo": "Galileo Galilei — Il Padre della Scienza",
    "titulo_pt": "Galileu Galilei — O Pai da Ciência Moderna",
    "nivel": "B1",
    "icone": "🔭",
    "autor": "Racconto storico",
    "tema": "scienza",
    "descricao": "La vita del grande scienziato pisano che rivoluzionò la nostra comprensione dell'universo e pagò un caro prezzo per la verità.",
    "descricao_pt": "A vida do grande cientista pisano que revolucionou nossa compreensão do universo e pagou um alto preço pela verdade.",
    "xp_recompensa": 80,
    "testo": [
      {"id":"stor_018_p1","italiano":"Galileo Galilei nacque a Pisa il 15 febbraio 1564. Era figlio di un musicista colto. Da giovane studiò medicina all'Università di Pisa, ma ben presto il suo vero amore divenne la matematica e la fisica.","portugues":"Galileu Galilei nasceu em Pisa em 15 de fevereiro de 1564. Era filho de um músico culto. Quando jovem estudou medicina na Universidade de Pisa, mas logo seu verdadeiro amor tornou-se a matemática e a física.",
       "parole":[{"parola":"musicista","traduzione":"músico","ipa":"/muziˈtʃista/","categoria":"sostantivo"},{"parola":"medicina","traduzione":"medicina","ipa":"/mediˈtʃiːna/","categoria":"sostantivo"},{"parola":"matematica","traduzione":"matemática","ipa":"/matemˈaːtika/","categoria":"sostantivo"},{"parola":"fisica","traduzione":"física","ipa":"/ˈfiːzika/","categoria":"sostantivo"}]},
      {"id":"stor_018_p2","italiano":"La leggenda narra che Galileo osservò la caduta di oggetti dalla Torre Pendente di Pisa. Scoprì così che oggetti di peso diverso cadono alla stessa velocità, contraddicendo le teorie di Aristotele.","portugues":"A lenda conta que Galileu observou a queda de objetos da Torre Inclinada de Pisa. Descobriu assim que objetos de peso diferente caem com a mesma velocidade, contradizendo as teorias de Aristóteles.",
       "parole":[{"parola":"caduta","traduzione":"queda","ipa":"/kaˈduːta/","categoria":"sostantivo"},{"parola":"oggetti","traduzione":"objetos","ipa":"/odˈdʒɛtti/","categoria":"sostantivo"},{"parola":"velocità","traduzione":"velocidade","ipa":"/veloˈtʃita/","categoria":"sostantivo"},{"parola":"contraddicendo","traduzione":"contradizendo","ipa":"/kontraddiˈtʃɛndo/","categoria":"verbo"}]},
      {"id":"stor_018_p3","italiano":"Nel 1609, Galileo costruì il suo cannocchiale, molto più potente di quelli esistenti. Puntandolo verso il cielo, fece scoperte straordinarie: vide le montagne della Luna e le lune di Giove.","portugues":"Em 1609, Galileu construiu seu telescópio, muito mais poderoso do que os existentes. Apontando-o para o céu, fez descobertas extraordinárias: viu as montanhas da Lua e as luas de Júpiter.",
       "parole":[{"parola":"cannocchiale","traduzione":"telescópio","ipa":"/kannokkˈjaːle/","categoria":"sostantivo"},{"parola":"potente","traduzione":"poderoso","ipa":"/poˈtɛnte/","categoria":"aggettivo"},{"parola":"scoperte","traduzione":"descobertas","ipa":"/skoˈpɛrte/","categoria":"sostantivo"},{"parola":"montagne","traduzione":"montanhas","ipa":"/monˈtaɲɲe/","categoria":"sostantivo"}]},
      {"id":"stor_018_p4","italiano":"Le osservazioni di Galileo confermarono la teoria di Copernico: la Terra gira intorno al Sole, non il contrario. Questa idea era pericolosa per la Chiesa cattolica dell'epoca.","portugues":"As observações de Galileu confirmaram a teoria de Copérnico: a Terra gira em torno do Sol, e não o contrário. Essa ideia era perigosa para a Igreja Católica da época.",
       "parole":[{"parola":"osservazioni","traduzione":"observações","ipa":"/osservatˈtsjoːni/","categoria":"sostantivo"},{"parola":"confermarono","traduzione":"confirmaram","ipa":"/konfermˈaːrono/","categoria":"verbo"},{"parola":"pericolosa","traduzione":"perigosa","ipa":"/perikoˈloːza/","categoria":"aggettivo"},{"parola":"gira","traduzione":"gira","ipa":"/ˈdʒiːra/","categoria":"verbo"}]},
      {"id":"stor_018_p5","italiano":"Nel 1633, il Tribunale dell'Inquisizione processò Galileo per eresia. Lo costrinsero ad abiurare le sue teorie. Secondo una leggenda, dopo aver firmato, Galileo mormorò: Eppur si muove!","portugues":"Em 1633, o Tribunal da Inquisição processou Galileu por heresia. O obrigaram a abjurar suas teorias. Segundo uma lenda, após assinar, Galileu murmurou: E ainda assim se move!",
       "parole":[{"parola":"eresia","traduzione":"heresia","ipa":"/ereˈziːa/","categoria":"sostantivo"},{"parola":"abiurare","traduzione":"abjurar","ipa":"/abjuˈraːre/","categoria":"verbo"},{"parola":"firmato","traduzione":"assinado","ipa":"/firˈmaːto/","categoria":"verbo"},{"parola":"mormorò","traduzione":"murmurou","ipa":"/mormoˈrɔ/","categoria":"verbo"}]},
      {"id":"stor_018_p6","italiano":"Galileo fu condannato agli arresti domiciliari per il resto della sua vita. Visse ad Arcetri, vicino a Firenze, dove continuò a lavorare fino alla cecità totale. Non smise mai di fare scienza.","portugues":"Galileu foi condenado a prisão domiciliar pelo resto de sua vida. Viveu em Arcetri, perto de Florença, onde continuou a trabalhar até a cegueira total. Nunca parou de fazer ciência.",
       "parole":[{"parola":"condannato","traduzione":"condenado","ipa":"/kondanˈnaːto/","categoria":"aggettivo"},{"parola":"cecità","traduzione":"cegueira","ipa":"/tʃeˈtʃita/","categoria":"sostantivo"},{"parola":"continuò","traduzione":"continuou","ipa":"/kontiˈnwɔ/","categoria":"verbo"},{"parola":"smise","traduzione":"parou/deixou de","ipa":"/ˈzmiːze/","categoria":"verbo"}]},
      {"id":"stor_018_p7","italiano":"Galileo morì nel 1642. Nel 1992, trecentosessant'anni dopo il processo, Papa Giovanni Paolo II riconobbe ufficialmente che la Chiesa aveva sbagliato a condannare Galileo. Un atto tardivo ma importante.","portugues":"Galileu morreu em 1642. Em 1992, trezentos e sessenta anos após o julgamento, o Papa João Paulo II reconheceu oficialmente que a Igreja havia errado ao condenar Galileu. Um ato tardio mas importante.",
       "parole":[{"parola":"riconobbe","traduzione":"reconheceu","ipa":"/rikoˈnobbe/","categoria":"verbo"},{"parola":"ufficialmente","traduzione":"oficialmente","ipa":"/uffitʃalˈmente/","categoria":"avverbio"},{"parola":"tardivo","traduzione":"tardio","ipa":"/tarˈdiːvo/","categoria":"aggettivo"},{"parola":"sbagliato","traduzione":"errado","ipa":"/zbaʎˈʎaːto/","categoria":"aggettivo"}]},
      {"id":"stor_018_p8","italiano":"Oggi Galileo è considerato il padre della scienza moderna. Il suo metodo sperimentale — osservare, misurare, verificare — è ancora la base di tutta la ricerca scientifica nel mondo.","portugues":"Hoje Galileu é considerado o pai da ciência moderna. Seu método experimental — observar, medir, verificar — ainda é a base de toda pesquisa científica no mundo.",
       "parole":[{"parola":"sperimentale","traduzione":"experimental","ipa":"/sperimɛnˈtaːle/","categoria":"aggettivo"},{"parola":"misurare","traduzione":"medir","ipa":"/mizuˈraːre/","categoria":"verbo"},{"parola":"verificare","traduzione":"verificar","ipa":"/verificˈkaːre/","categoria":"verbo"},{"parola":"ricerca","traduzione":"pesquisa","ipa":"/riˈtʃɛrka/","categoria":"sostantivo"}]}
    ]
  }
]

storie.extend(novas)
d['storie'] = storie

print(f'\nTotal final: {len(storie)} histórias')
niveis = {}
for s in storie:
    n = s['nivel']
    niveis[n] = niveis.get(n,0)+1
print('Distribuição:', niveis)

json.dump(d, open('data/storie.json','w',encoding='utf-8'), ensure_ascii=False, indent=2)
print('storie.json salvo!')
